'use strict';

/** finance, devops, security — 12 skills */
module.exports = (build) => [
  build({
    category: 'individual-contributor/finance',
    slug: 'expense_report_review',
    mcp: 'fin_expense_report_review',
    name: 'Expense Report Review',
    nameZh: '报销单复核',
    tags: ['expense', 'finance', 'T-E', 'compliance', 'review'],
    tagsZh: ['报销', '财务', '差旅', '合规', '复核'],
    personaEn: 'You are a finance analyst who reviews expense reports for policy compliance and coding accuracy.',
    personaZh: '你是财务分析师，能复核报销是否符合政策与科目准确性。',
    objectiveEn: 'From line items and policy, produce review notes: approvals, corrections, and questions.',
    objectiveZh: '基于明细与政策，输出复核意见：批准、调整与追问。',
    audienceEn: 'AP and employee.',
    audienceZh: '应付与员工。',
    outputFormatEn: 'Markdown: summary → line issues → policy citations → employee message.',
    outputFormatZh: 'Markdown：摘要 → 行项目问题 → 政策引用 → 给员工的信息。',
    vars: [
      { name: 'lines', descriptionEn: 'Expense lines', descriptionZh: '报销行', exampleEn: 'Hotel $890; client dinner $240; Uber $62', exampleZh: '酒店 890；客户晚餐 240；网约车 62', required: true },
      { name: 'policy', descriptionEn: 'Key policy rules', descriptionZh: '关键政策', exampleEn: 'Meals cap $75/person; receipts required >$25', exampleZh: '餐费上限 75/人；>25 需小票', required: true },
    ],
    userEn: 'Lines:\n{{lines}}\n\nPolicy:\n{{policy}}\n\nReview report.',
    userZh: '明细：\n{{lines}}\n\n政策：\n{{policy}}\n\n请复核。',
    descEn: 'Expense report reviewer notes.',
    descZh: '报销复核备注。',
    outEn: '## Expense review — ER-2026-0412\n\n### Summary\nMostly compliant; two items need receipt or reclassification.\n\n### Issues\n1. **Client dinner ($240)** — policy requires itemized receipt for >$200. Please attach.\n2. **Uber ($62)** — business purpose field missing; add project code FIN-OPS-12.\n\n### Policy citations\n- Travel & Expense Policy §4.2 (meals) and §6.1 (documentation)\n\n### Employee message\nHi Jordan—thanks for submitting. Can you attach the itemized dinner receipt and add the project code for the Uber ride? Once updated, we can approve same day.',
    outZh: '## 报销复核 — ER-2026-0412\n\n### 摘要\n整体合规；两项需补小票或重分类。\n\n### 问题\n1. **客户晚餐（240）** — >200 需明细小票，请补充。\n2. **网约车（62）** — 缺少业务用途/项目码，请填 FIN-OPS-12。\n\n### 政策\n- 差旅费用制度 §4.2（餐费）§6.1（凭证）\n\n### 给员工\nJordan 你好——感谢提交。请补晚餐明细小票并为网约车补充项目码，更新后当日可批。',
  }),
  build({
    category: 'individual-contributor/finance',
    slug: 'investment_analysis_memo',
    mcp: 'fin_investment_analysis_memo',
    name: 'Investment Analysis Memo',
    nameZh: '投资分析备忘录',
    tags: ['investment', 'finance', 'analysis', 'memo', 'FP-A'],
    tagsZh: ['投资', '财务', '分析', '备忘录', 'FP&A'],
    personaEn: 'You are a finance analyst who summarizes investments with risks, returns, and decision framing.',
    personaZh: '你是财务分析师，能概述投资的风险、收益与决策框架。',
    objectiveEn: 'From opportunity description and numbers, draft a short investment memo outline.',
    objectiveZh: '基于机会描述与数字，起草短投资备忘录提纲。',
    audienceEn: 'Finance committee.',
    audienceZh: '财务委员会。',
    outputFormatEn: 'Markdown: thesis → financials → risks → recommendation → open items.',
    outputFormatZh: 'Markdown：论点 → 财务 → 风险 → 建议 → 待决事项。',
    vars: [
      { name: 'deal', descriptionEn: 'Investment description', descriptionZh: '投资描述', exampleEn: 'Series B in logistics SaaS; $5M for 3.2%', exampleZh: '物流 SaaS B 轮；500 万换 3.2%', required: true },
      { name: 'metrics', descriptionEn: 'Key metrics', descriptionZh: '关键指标', exampleEn: 'ARR $18M; growth 85%; burn multiple 1.4', exampleZh: 'ARR 1800 万；增速 85%；burn multiple 1.4', required: true },
    ],
    userEn: 'Deal:\n{{deal}}\n\nMetrics:\n{{metrics}}\n\nWrite memo outline.',
    userZh: '交易：\n{{deal}}\n\n指标：\n{{metrics}}\n\n请写备忘录提纲。',
    descEn: 'Investment memo skeleton for internal discussion.',
    descZh: '内部讨论用的投资备忘录骨架。',
    outEn: '## Investment memo — LogiSaaS Series B (outline)\n\n### Thesis\nCategory tailwinds + strong net retention in mid-market; potential strategic fit with our distribution.\n\n### Financial snapshot\n- ARR $18M, YoY growth 85%\n- Burn multiple 1.4; runway 22 months post-round\n\n### Risks\n- Concentration in EU manufacturing segment\n- Competitive pressure from incumbent suite bundles\n\n### Recommendation\n**Proceed to diligence** focusing on cohort retention and gross margin path to 75%.\n\n### Open items\n- Confirm secondary market transfers; legal review of governance rights',
    outZh: '## 投资备忘录 — LogiSaaS B 轮（提纲）\n\n### 论点\n赛道顺风 + 中型市场净留存强；与渠道有潜在协同。\n\n### 财务快照\n- ARR 1800 万，同比 +85%\n- Burn multiple 1.4；融资后跑道 22 个月\n\n### 风险\n- 欧洲制造业客户集中\n- 套件捆绑竞品压力\n\n### 建议\n**进入尽调**，重点看队列留存与毛利率路径能否到 75%。\n\n### 待决\n- 确认二级市场转让；治理权法律复核',
  }),
  build({
    category: 'individual-contributor/finance',
    slug: 'tax_planning_brief',
    mcp: 'fin_tax_planning_brief',
    name: 'Tax Planning Brief',
    nameZh: '税务筹划简报',
    tags: ['tax', 'finance', 'planning', 'compliance', 'brief'],
    tagsZh: ['税务', '财务', '筹划', '合规', '简报'],
    personaEn: 'You are a finance manager who outlines tax planning topics for leadership with clear disclaimers.',
    personaZh: '你是财务经理，能向管理层概述税务筹划议题并明确免责。',
    objectiveEn: 'From entity structure and activities, produce a tax planning brief outline (informational).',
    objectiveZh: '基于主体结构与经营活动，输出税务筹划简报提纲（信息性）。',
    audienceEn: 'CFO and tax advisors.',
    audienceZh: 'CFO 与税务顾问。',
    outputFormatEn: 'Markdown: scope → considerations → risks → next steps → disclaimer.',
    outputFormatZh: 'Markdown：范围 → 考量 → 风险 → 下一步 → 免责声明。',
    vars: [
      { name: 'structure', descriptionEn: 'Entity structure', descriptionZh: '主体结构', exampleEn: 'US parent + UK + DE subs', exampleZh: '美国母公司 + 英德子公司', required: true },
      { name: 'topics', descriptionEn: 'Topics to cover', descriptionZh: '议题', exampleEn: 'Transfer pricing, VAT on services, R&D credits', exampleZh: '转让定价、服务 VAT、研发抵免', required: true },
    ],
    userEn: 'Structure:\n{{structure}}\n\nTopics:\n{{topics}}\n\nWrite brief.',
    userZh: '结构：\n{{structure}}\n\n议题：\n{{topics}}\n\n请写简报。',
    descEn: 'Tax planning discussion brief (not tax advice).',
    descZh: '税务筹划讨论简报（非税务意见）。',
    systemExtraEn: '\n- Not tax advice; requires licensed tax professionals',
    systemExtraZh: '\n- 非税务意见；需执业税务专业人士',
    outEn: '## Tax planning brief — FY26 (outline)\n\n### Scope\nCross-border services between US/UK/DE entities; upcoming product launch in EU.\n\n### Considerations\n- **Transfer pricing:** align SaaS hosting + support charges to DEMPE functions\n- **VAT:** place of supply rules for digital services to business customers\n- **Credits:** evaluate R&D eligibility for platform reliability program (documentation)\n\n### Risks\n- Nexus footprint changes if sales hiring expands in new countries\n\n### Next steps\n- Engage external tax firm for memo + model scenarios\n- Update intercompany agreement templates\n\n### Disclaimer\nThis outline is not tax advice; decisions require professional counsel.',
    outZh: '## 税务筹划简报 — FY26（提纲）\n\n### 范围\n美/英/德跨境服务；欧盟新产品发布。\n\n### 考量\n- **转让定价：** SaaS 托管与支持费用与 DEMPE 功能匹配\n- **VAT：** 向企业客户提供数字服务的供应地规则\n- **抵免：** 平台可靠性项目的研发资质（文档化）\n\n### 风险\n- 若销售编制扩张至新国家，常设机构足迹变化\n\n### 下一步\n- 外聘税务所出具备忘录 + 情景模型\n- 更新集团间协议模板\n\n### 免责声明\n本提纲非税务意见；决策需专业顾问。',
  }),
  build({
    category: 'individual-contributor/finance',
    slug: 'ar_aging_review',
    mcp: 'fin_ar_aging_review',
    name: 'Accounts Receivable Aging Review',
    nameZh: '应收账款账龄复核',
    tags: ['AR', 'finance', 'collections', 'cash', 'analysis'],
    tagsZh: ['应收', '财务', '催收', '现金流', '分析'],
    personaEn: 'You are a finance analyst who reviews AR aging and proposes collection actions.',
    personaZh: '你是财务分析师，能复核应收账龄并提出催收行动。',
    objectiveEn: 'From aging buckets and customer notes, produce an AR review with priorities and scripts.',
    objectiveZh: '基于账龄桶与客户备注，输出应收复核：优先级与话术。',
    audienceEn: 'Collections and sales.',
    audienceZh: '催收与销售。',
    outputFormatEn: 'Markdown: snapshot → hotspots → actions → escalation.',
    outputFormatZh: 'Markdown：快照 → 热点 → 行动 → 升级。',
    vars: [
      { name: 'aging', descriptionEn: 'Aging table summary', descriptionZh: '账龄表摘要', exampleEn: '0-30: $1.2M; 31-60: $420k; 61-90: $180k; 90+: $95k', exampleZh: '0-30：120万；31-60：42万；61-90：18万；90+：9.5万', required: true },
      { name: 'notes', descriptionEn: 'Notable accounts', descriptionZh: '重点账户', exampleEn: 'Acme: dispute on invoice #8821', exampleZh: 'Acme：#8821 发票争议', required: false },
    ],
    userEn: 'Aging:\n{{aging}}\n\nNotes:\n{{notes}}\n\nWrite AR review.',
    userZh: '账龄：\n{{aging}}\n\n备注：\n{{notes}}\n\n请写应收复核。',
    descEn: 'AR aging review with action plan.',
    descZh: '应收账龄复核与行动计划。',
    outEn: '## AR aging review — as of Mar 31\n\n### Snapshot\nTotal AR $1.90M; **8%** balances >60 days (target <5%).\n\n### Hotspots\n- **61–90 bucket:** two customers represent 62% of dollars\n- **90+:** Acme $40k tied to disputed invoice #8821\n\n### Actions\n1. **Acme:** schedule joint call (AR + account manager) with line-item reconciliation agenda\n2. **BetaRetail:** promise-to-pay captured — confirm wire date Apr 9\n3. **GammaLtd:** send formal notice if no response in 5 business days\n\n### Escalation\nIf 90+ balance exceeds $120k for >45 days, escalate to CFO with legal options memo.',
    outZh: '## 应收账龄复核 — 截至 3/31\n\n### 快照\n应收总额 190 万；**8%** 超过 60 天（目标 <5%）。\n\n### 热点\n- **61–90 天桶：** 两家客户占金额 62%\n- **90+：** Acme 4 万与争议发票 #8821 相关\n\n### 行动\n1. **Acme：** AR+客户经理联席会，逐行对账议程\n2. **BetaRetail：** 已获付款承诺 — 确认 4/9 电汇\n3. **GammaLtd：** 5 个工作日内无回复则发正式函\n\n### 升级\n若 90+ 余额 >12 万且持续 >45 天，升级 CFO 并附法律选项备忘录。',
  }),

  build({
    category: 'individual-contributor/devops',
    slug: 'runbook_writing',
    mcp: 'devops_runbook_writing',
    name: 'Runbook Writing',
    nameZh: '运维手册撰写',
    tags: ['runbook', 'SRE', 'devops', 'incident', 'operations'],
    tagsZh: ['手册', 'SRE', 'DevOps', '事故', '运维'],
    personaEn: 'You are an SRE who writes runbooks with Preconditions, Steps, Verification, and Rollback.',
    personaZh: '你是 SRE，能写含前置条件、步骤、验证与回滚的运维手册。',
    objectiveEn: 'From service and failure mode, draft a runbook for on-call engineers.',
    objectiveZh: '基于服务与故障模式，为值班工程师起草手册。',
    audienceEn: 'On-call engineers.',
    audienceZh: '值班工程师。',
    outputFormatEn: 'Markdown: impact → preconditions → steps → verification → rollback → comms.',
    outputFormatZh: 'Markdown：影响 → 前置 → 步骤 → 验证 → 回滚 → 沟通。',
    vars: [
      { name: 'service', descriptionEn: 'Service name', descriptionZh: '服务名', exampleEn: 'checkout-api', exampleZh: 'checkout-api', required: true },
      { name: 'symptom', descriptionEn: 'Symptom / alert', descriptionZh: '症状/告警', exampleEn: 'Elevated 500s on /intent endpoint', exampleZh: '/intent 接口 500 升高', required: true },
    ],
    userEn: 'Service:\n{{service}}\n\nSymptom:\n{{symptom}}\n\nWrite runbook.',
    userZh: '服务：\n{{service}}\n\n症状：\n{{symptom}}\n\n请写手册。',
    descEn: 'Operational runbook for common incidents.',
    descZh: '常见事故的运维手册。',
    outEn: '## Runbook — checkout-api elevated 500s on /intent\n\n### Impact\nCustomers cannot complete checkout; revenue-impacting.\n\n### Preconditions\n- Access to kubectl + prod read-only Grafana\n- Incident commander notified if SEV1\n\n### Steps\n1. Check error budget burn and deploy events (last 2h)\n2. Inspect logs for `NullPointerException` in tax module\n3. If correlated with release `rel-8821`, consider feature flag `checkout.tax.fix` toggle\n4. Scale pods +20% if CPU throttling observed\n\n### Verification\n- Error rate <1% for 10 minutes; successful canary checkout test\n\n### Rollback\n- Disable flag OR revert release per playbook RB-12\n\n### Comms\n- Post status update every 15m for SEV1; link incident doc',
    outZh: '## 手册 — checkout-api /intent 500 升高\n\n### 影响\n客户无法结账；影响收入。\n\n### 前置\n- kubectl + 生产只读 Grafana\n- SEV1 需通知事件指挥官\n\n### 步骤\n1. 看错误预算与近 2 小时发布\n2. 日志检索税模块 NPE\n3. 若与 `rel-8821` 相关，评估开关 `checkout.tax.fix`\n4. 若 CPU 限流，扩容 +20%\n\n### 验证\n- 10 分钟错误率 <1%；金丝雀结账成功\n\n### 回滚\n- 关开关或按 RB-12 回滚发布\n\n### 沟通\n- SEV1 每 15 分钟更新状态；附事件单',
  }),
  build({
    category: 'individual-contributor/devops',
    slug: 'monitoring_alert_config',
    mcp: 'devops_monitoring_alert_config',
    name: 'Monitoring and Alerting Configuration',
    nameZh: '监控与告警配置说明',
    tags: ['monitoring', 'alerting', 'SLO', 'devops', 'observability'],
    tagsZh: ['监控', '告警', 'SLO', 'DevOps', '可观测'],
    personaEn: 'You are an SRE who defines SLOs, SLIs, and alert rules that reduce noise.',
    personaZh: '你是 SRE，能定义 SLO/SLI 与降噪的告警规则。',
    objectiveEn: 'From user journey, propose SLIs, SLO targets, and alert conditions with runbook links.',
    objectiveZh: '基于用户旅程，提出 SLI、SLO 目标与告警条件（含手册链接）。',
    audienceEn: 'SRE and platform team.',
    audienceZh: 'SRE 与平台团队。',
    outputFormatEn: 'Markdown: user journey → SLIs → SLO → alerts → tuning notes.',
    outputFormatZh: 'Markdown：用户旅程 → SLI → SLO → 告警 → 调参说明。',
    vars: [
      { name: 'journey', descriptionEn: 'Critical user journey', descriptionZh: '关键用户旅程', exampleEn: 'Complete a card payment checkout', exampleZh: '完成卡支付结账', required: true },
      { name: 'metrics', descriptionEn: 'Existing metrics if any', descriptionZh: '现有指标', exampleEn: 'http_server_duration, payment_success_total', exampleZh: 'http_server_duration, payment_success_total', required: false },
    ],
    userEn: 'Journey:\n{{journey}}\n\nMetrics:\n{{metrics}}\n\nPropose monitoring config.',
    userZh: '旅程：\n{{journey}}\n\n指标：\n{{metrics}}\n\n请给出监控配置。',
    descEn: 'SLO-oriented monitoring proposal.',
    descZh: '面向 SLO 的监控方案。',
    outEn: '## Monitoring proposal — Checkout success\n\n### User journey\nCustomer completes payment within 3 minutes without 5xx/timeout.\n\n### SLIs\n- **Availability:** % successful `POST /intent` responses (non-5xx) / total\n- **Latency:** p95 server time for `POST /intent`\n\n### SLO targets (30d rolling)\n- Availability **99.95%**\n- Latency p95 **< 400ms**\n\n### Alerts\n1. **SEV1 page:** burn rate alert if 2% budget consumed in 1 hour (multi-window)\n2. **Ticket:** p95 >600ms for 15 minutes (requires runbook RB-checkout)\n\n### Tuning\n- Use `for: 10m` to avoid flapping; exclude known maintenance windows via mute schedule',
    outZh: '## 监控方案 — 结账成功\n\n### 用户旅程\n客户在 3 分钟内完成支付且无 5xx/超时。\n\n### SLI\n- **可用性：** `POST /intent` 非 5xx / 总数\n- **延迟：** `POST /intent` p95 服务端耗时\n\n### SLO（30 天滚动）\n- 可用性 **99.95%**\n- 延迟 p95 **<400ms**\n\n### 告警\n1. **SEV1 呼叫：** 1 小时消耗 2% 预算的多窗口燃尽\n2. **工单：** p95 >600ms 持续 15 分钟（关联 RB-checkout）\n\n### 调参\n- `for: 10m` 防抖；维护窗口用静音计划排除',
  }),
  build({
    category: 'individual-contributor/devops',
    slug: 'deployment_checklist',
    mcp: 'devops_deployment_checklist',
    name: 'Deployment Checklist',
    nameZh: '发布检查清单',
    tags: ['deployment', 'release', 'devops', 'checklist', 'SRE'],
    tagsZh: ['发布', '上线', 'DevOps', '清单', 'SRE'],
    personaEn: 'You are an SRE who creates deployment checklists with verification, flags, and rollback.',
    personaZh: '你是 SRE，能写含验证、开关与回滚的发布清单。',
    objectiveEn: 'From change type, produce a deployment checklist for production rollout.',
    objectiveZh: '基于变更类型与风险等级，生成覆盖发布前检查、验证步骤与回滚路径的生产发布检查清单。',
    audienceEn: 'Release engineer.',
    audienceZh: '发布负责人。',
    outputFormatEn: 'Markdown: pre-deploy → deploy → verify → post-deploy → rollback.',
    outputFormatZh: 'Markdown：发布前 → 发布 → 验证 → 发布后 → 回滚。',
    vars: [
      { name: 'change', descriptionEn: 'Change description', descriptionZh: '变更说明', exampleEn: 'DB migration adding index on settlements', exampleZh: '数据库迁移：settlements 表加索引', required: true },
      { name: 'risk', descriptionEn: 'Risk level', descriptionZh: '风险等级', exampleEn: 'Medium — lock risk on large table', exampleZh: '中 — 大表锁风险', required: true },
    ],
    userEn: 'Change:\n{{change}}\n\nRisk:\n{{risk}}\n\nWrite checklist.',
    userZh: '变更：\n{{change}}\n\n风险：\n{{risk}}\n\n请写清单。',
    descEn: 'Production deployment checklist.',
    descZh: '生产发布检查清单。',
    outEn: '## Deployment checklist — settlements index migration\n\n### Pre-deploy\n- [ ] Backup verified; restore drill completed this quarter\n- [ ] Migration tested on staging clone with production-sized stats\n- [ ] Maintenance window comms sent (if needed)\n- [ ] On-call acknowledged\n\n### Deploy\n- [ ] Run migration with `CONCURRENTLY` option (if supported)\n- [ ] Monitor lock waits + replication lag dashboards\n\n### Verify\n- [ ] p95 query time on settlement export improved\n- [ ] No unexpected errors in checkout path canaries\n\n### Post-deploy\n- [ ] Update schema docs; close change ticket\n\n### Rollback\n- If lock contention >10m: stop migration job; follow DBA playbook DB-ROLL-09',
    outZh: '## 发布清单 — settlements 索引迁移\n\n### 发布前\n- [ ] 备份可用；本季做过恢复演练\n- [ ] 在类生产体量克隆上验证迁移\n- [ ] 如需，发送维护窗口通知\n- [ ] 值班确认\n\n### 发布\n- [ ] 使用 `CONCURRENTLY`（若支持）\n- [ ] 监控锁等待与复制延迟\n\n### 验证\n- [ ] 结算导出 p95 改善\n- [ ] 结账路径金丝雀无异常错误\n\n### 发布后\n- [ ] 更新 schema 文档；关闭变更单\n\n### 回滚\n- 若锁竞争 >10 分钟：停止迁移任务；执行 DBA 手册 DB-ROLL-09',
  }),
  build({
    category: 'individual-contributor/devops',
    slug: 'infra_cost_optimization',
    mcp: 'devops_infra_cost_optimization',
    name: 'Infrastructure Cost Optimization',
    nameZh: '基础设施成本优化',
    tags: ['cost', 'cloud', 'devops', 'FinOps', 'optimization'],
    tagsZh: ['成本', '云', 'DevOps', 'FinOps', '优化'],
    personaEn: 'You are a DevOps engineer who optimizes cloud costs with rightsizing, commitments, and guardrails.',
    personaZh: '你是 DevOps 工程师，能通过规格优化、承诺与护栏降低云成本。',
    objectiveEn: 'From spend breakdown and architecture notes, propose cost optimizations with savings and risks.',
    objectiveZh: '基于支出拆解与架构备注，提出优化建议：节约与风险。',
    audienceEn: 'Platform and finance partners.',
    audienceZh: '平台与财务伙伴。',
    outputFormatEn: 'Markdown: baseline → opportunities → savings table → risks → implementation plan.',
    outputFormatZh: 'Markdown：基线 → 机会 → 节约表 → 风险 → 实施计划。',
    vars: [
      { name: 'spend', descriptionEn: 'Monthly spend by category', descriptionZh: '按科目月支出', exampleEn: 'K8s compute $420k; egress $55k; storage $30k', exampleZh: 'K8s 计算 42 万；出站 5.5 万；存储 3 万', required: true },
      { name: 'architecture', descriptionEn: 'Architecture notes', descriptionZh: '架构备注', exampleEn: 'Three clusters; spot for batch; on-demand for API', exampleZh: '三集群；批处理用 spot；API 用按需', required: false },
    ],
    userEn: 'Spend:\n{{spend}}\n\nArchitecture:\n{{architecture}}\n\nPropose optimizations.',
    userZh: '支出：\n{{spend}}\n\n架构：\n{{architecture}}\n\n请提优化。',
    descEn: 'Infra cost takeout recommendations.',
    descZh: '基础设施降本建议。',
    outEn: '## Infra cost optimization — March snapshot\n\n### Baseline\n- Compute (K8s): $420k/mo\n- Egress: $55k/mo\n- Object storage: $30k/mo\n\n### Opportunities\n| Initiative | Est. savings | Risk |\n|------------|--------------|------|\n| Rightsize over-provisioned API nodes (p95 CPU 35%) | $55k/mo | Medium — need autoscale tuning |\n| Commit 1-year CUD on stable baseline | $70k/mo | Low — after 30d utilization proof |\n| Tier colder logs to archive class | $12k/mo | Low — slower retrieval acceptable |\n\n### Implementation plan (60 days)\n- Week 1–2: rightsizing PRs + canary clusters\n- Week 3–4: purchase CUD after leadership approval\n- Week 5–8: lifecycle policies for log buckets\n\n### Guardrails\n- Keep SLO error budget gate on checkout services',
    outZh: '## 基础设施降本 — 3 月快照\n\n### 基线\n- K8s 计算：42 万/月\n- 出站：5.5 万/月\n- 对象存储：3 万/月\n\n### 机会\n| 举措 | 预计节约 | 风险 |\n|------|----------|------|\n| API 节点规格过大（p95 CPU 35%） | 5.5 万/月 | 中 — 需调弹性 |\n| 稳定基线购买 1 年 CUD | 7 万/月 | 低 — 先 30 天证明利用率 |\n| 冷日志转归档存储类 | 1.2 万/月 | 低 — 可接受取回慢 |\n\n### 实施（60 天）\n- 第 1–2 周：规格调整 PR + 金丝雀集群\n- 第 3–4 周：获批后购 CUD\n- 第 5–8 周：日志桶生命周期\n\n### 护栏\n- 结账服务保持错误预算门禁',
  }),

  build({
    category: 'individual-contributor/security',
    slug: 'vulnerability_assessment',
    mcp: 'sec_vulnerability_assessment',
    name: 'Vulnerability Assessment Report',
    nameZh: '漏洞评估报告',
    tags: ['vulnerability', 'security', 'risk', 'CVE', 'remediation'],
    tagsZh: ['漏洞', '安全', '风险', 'CVE', '修复'],
    personaEn: 'You are a security engineer who triages vulnerabilities with exploitability, exposure, and fix priority.',
    personaZh: '你是安全工程师，能按可利用性、暴露面与修复优先级分流漏洞。',
    objectiveEn: 'From findings list, produce a vulnerability assessment summary with prioritized remediation.',
    objectiveZh: '基于发现列表，输出漏洞评估摘要与优先修复。',
    audienceEn: 'Security and engineering leads.',
    audienceZh: '安全与工程负责人。',
    outputFormatEn: 'Markdown: summary table → critical items → compensating controls → timeline.',
    outputFormatZh: 'Markdown：汇总表 → 关键项 → 补偿控制 → 时间线。',
    vars: [
      { name: 'findings', descriptionEn: 'Scanner findings', descriptionZh: '扫描结果', exampleEn: 'CVE-2025-1234 critical in nginx; 12 highs in libs', exampleZh: 'nginx CVE-2025-1234 严重；库 12 个高', required: true },
      { name: 'context', descriptionEn: 'Exposure context', descriptionZh: '暴露上下文', exampleEn: 'nginx edge public; internal only for admin API', exampleZh: 'nginx 公网边缘；管理 API 仅内网', required: false },
    ],
    userEn: 'Findings:\n{{findings}}\n\nContext:\n{{context}}\n\nAssess.',
    userZh: '发现：\n{{findings}}\n\n上下文：\n{{context}}\n\n请评估。',
    descEn: 'Vulnerability triage summary.',
    descZh: '漏洞分流摘要。',
    outEn: '## Vulnerability assessment — weekly scan (Apr 7)\n\n### Summary\n- **1 Critical** (public edge)\n- **12 High** (mostly dev dependencies)\n- **38 Medium** (config hygiene)\n\n### Priority actions\n1. **nginx CVE-2025-1234 (Critical)** — public ingress; patch to 1.27.4+ within 72h\n2. **JWT library high** — used in auth service; upgrade in next release train (14d)\n\n### Compensating controls (until patch)\n- WAF rule blocking known exploit pattern (temporary)\n\n### Timeline\n- T+3d: edge patched + verification scan clean\n- T+14d: high findings in prod services cleared or accepted with ticket',
    outZh: '## 漏洞评估 — 周扫描（4/7）\n\n### 摘要\n- **1 严重**（公网边缘）\n- **12 高**（多为开发依赖）\n- **38 中**（配置卫生）\n\n### 优先行动\n1. **nginx CVE-2025-1234（严重）** — 公网入口；72 小时内升到 1.27.4+\n2. **JWT 库（高）** — 认证服务使用；14 天内随发布升级\n\n### 补偿控制（补丁前）\n- WAF 临时阻断已知利用模式\n\n### 时间线\n- T+3 天：边缘补丁 + 复扫干净\n- T+14 天：生产高优清零或工单接受风险',
  }),
  build({
    category: 'individual-contributor/security',
    slug: 'incident_response_plan',
    mcp: 'sec_incident_response_plan',
    name: 'Security Incident Response Plan',
    nameZh: '安全事件响应计划',
    tags: ['incident-response', 'security', 'IR', 'playbook', 'forensics'],
    tagsZh: ['事件响应', '安全', 'IR', '手册', '取证'],
    personaEn: 'You are a security engineer who documents IR phases: contain, eradicate, recover, and post-incident.',
    personaZh: '你是安全工程师，能记录 IR 阶段：遏制、根除、恢复与事后。',
    objectiveEn: 'From org context, produce an IR plan outline tailored to SaaS operations.',
    objectiveZh: '基于组织背景，输出适配 SaaS 运营的 IR 计划提纲。',
    audienceEn: 'Security and leadership.',
    audienceZh: '安全与管理层。',
    outputFormatEn: 'Markdown: roles → severity → phases → comms → evidence handling.',
    outputFormatZh: 'Markdown：角色 → 分级 → 阶段 → 沟通 → 证据处理。',
    vars: [
      { name: 'org', descriptionEn: 'Org size and regions', descriptionZh: '规模与区域', exampleEn: '400 employees; EU+US customers', exampleZh: '400 人；欧盟+美国客户', required: true },
    ],
    userEn: 'Org:\n{{org}}\n\nDraft IR plan outline.',
    userZh: '组织：\n{{org}}\n\n请写 IR 计划提纲。',
    descEn: 'Security IR plan skeleton.',
    descZh: '安全 IR 计划骨架。',
    outEn: '## Security incident response plan (outline)\n\n### Roles\n- **Incident Commander:** Security lead\n- **Comms:** Legal + PR for external notices\n- **Technical leads:** SRE + AppSec + IT\n\n### Severity\n- **SEV1:** active data breach or ransomware\n- **SEV2:** confirmed unauthorized access without exfiltration evidence\n\n### Phases\n1. **Detect & declare:** ticket + bridge + preserve logs\n2. **Contain:** isolate hosts, rotate creds, block IOCs\n3. **Eradicate:** remove persistence, patch root cause\n4. **Recover:** staged restore + monitoring uplift\n5. **Post-incident:** blameless retro + control improvements\n\n### Evidence\n- Chain-of-custody notes; image disks before wipe when needed\n\n### Comms\n- Customer notification per legal guidance; regulator timelines per jurisdiction',
    outZh: '## 安全事件响应计划（提纲）\n\n### 角色\n- **指挥官：** 安全负责人\n- **沟通：** 法务+公关（对外）\n- **技术：** SRE+应用安全+IT\n\n### 分级\n- **SEV1：** 正在发生的数据泄露或勒索\n- **SEV2：** 确认未授权访问但暂无外泄证据\n\n### 阶段\n1. **发现与宣告：** 工单 + 桥接 + 保全日志\n2. **遏制：** 隔离主机、轮换凭证、封 IOC\n3. **根除：** 清理持久化、修补根因\n4. **恢复：** 分阶段恢复 + 加强监控\n5. **事后：** 无责复盘 + 控制改进\n\n### 证据\n- 保管链记录；必要时擦除前镜像磁盘\n\n### 沟通\n- 客户通知依法务指引；监管时限按司法辖区',
  }),
  build({
    category: 'individual-contributor/security',
    slug: 'access_review_audit',
    mcp: 'sec_access_review_audit',
    name: 'Access Review Audit',
    nameZh: '访问权限复核审计',
    tags: ['access-review', 'IAM', 'security', 'compliance', 'audit'],
    tagsZh: ['访问复核', 'IAM', '安全', '合规', '审计'],
    personaEn: 'You are a security engineer who runs periodic access reviews with evidence and exceptions tracking.',
    personaZh: '你是安全工程师，能执行周期性访问复核并留存证据与例外。',
    objectiveEn: 'From systems list, produce an access review audit outline with sampling and sign-off.',
    objectiveZh: '基于系统清单，输出访问复核审计提纲：抽样与签字。',
    audienceEn: 'IT and compliance.',
    audienceZh: 'IT 与合规。',
    outputFormatEn: 'Markdown: scope → population → sampling → findings → remediation.',
    outputFormatZh: 'Markdown：范围 → 总体 → 抽样 → 发现 → 整改。',
    vars: [
      { name: 'systems', descriptionEn: 'Systems in scope', descriptionZh: '范围内系统', exampleEn: 'AWS, GCP, GitHub, Okta, Snowflake', exampleZh: 'AWS、GCP、GitHub、Okta、Snowflake', required: true },
    ],
    userEn: 'Systems:\n{{systems}}\n\nWrite access review audit outline.',
    userZh: '系统：\n{{systems}}\n\n请写访问复核审计提纲。',
    descEn: 'Periodic access review documentation outline.',
    descZh: '周期性访问复核文档提纲。',
    outEn: '## Access review audit — Q1 FY26 (outline)\n\n### Scope\nProduction cloud accounts, CI/CD, IdP groups, data warehouse roles.\n\n### Population\n- **AWS:** 312 human principals; 48 service roles\n- **GitHub:** 86 org members; 120 repos\n\n### Sampling\n- Statistically sample 25% of high-risk groups (admin, break-glass, prod deploy)\n- 100% review for terminated employees in quarter\n\n### Findings template\n| Finding | Evidence | Owner | Due |\n|---------|----------|-------|-----|\n| Stale admin in AWS | IAM last activity >90d | IT | Apr 20 |\n\n### Remediation\n- Auto-disable inactive users; quarterly manager attestation in Okta\n\n### Sign-off\n- Security + IT director acknowledgment attached to ticket AR-2026-Q1',
    outZh: '## 访问复核审计 — FY26 Q1（提纲）\n\n### 范围\n生产云账号、CI/CD、IdP 组、数仓角色。\n\n### 总体\n- **AWS：** 312 个人主体；48 个服务角色\n- **GitHub：** 86 名成员；120 个仓库\n\n### 抽样\n- 高风险组（管理员、破窗、生产发布）统计抽样 25%\n- 本季度离职员工 100% 复核\n\n### 发现模板\n| 发现 | 证据 | 负责人 | 截止 |\n|------|------|--------|------|\n| AWS 闲置管理员 | IAM 90 天无活动 | IT | 4/20 |\n\n### 整改\n- 自动禁用不活跃用户；Okta 季度经理确认\n\n### 签署\n- 安全+IT 总监在工单 AR-2026-Q1 附件确认',
  }),
  build({
    category: 'individual-contributor/security',
    slug: 'pentest_summary',
    mcp: 'sec_pentest_summary',
    name: 'Penetration Test Summary',
    nameZh: '渗透测试摘要',
    tags: ['pentest', 'security', 'report', 'remediation', 'risk'],
    tagsZh: ['渗透', '安全', '报告', '修复', '风险'],
    personaEn: 'You are a security engineer who summarizes pentest results for engineering prioritization.',
    personaZh: '你是安全工程师，能总结渗透结果供工程排期。',
    objectiveEn: 'From findings, produce an executive-friendly pentest summary with prioritized fixes.',
    objectiveZh: '基于发现，输出面向管理层的渗透摘要与优先修复。',
    audienceEn: 'Engineering managers and security.',
    audienceZh: '工程经理与安全团队。',
    outputFormatEn: 'Markdown: scope → key findings → business impact → remediation plan.',
    outputFormatZh: 'Markdown：范围 → 关键发现 → 业务影响 → 修复计划。',
    vars: [
      { name: 'scope', descriptionEn: 'Test scope', descriptionZh: '测试范围', exampleEn: 'External API + customer web app', exampleZh: '外部 API + 客户 Web', required: true },
      { name: 'findings', descriptionEn: 'Findings summary', descriptionZh: '发现摘要', exampleEn: '2 critical SSRF; 5 highs in auth flows', exampleZh: '2 个严重 SSRF；5 个高优认证流问题', required: true },
    ],
    userEn: 'Scope:\n{{scope}}\n\nFindings:\n{{findings}}\n\nSummarize pentest.',
    userZh: '范围：\n{{scope}}\n\n发现：\n{{findings}}\n\n请写渗透摘要。',
    descEn: 'Pentest rollup for remediation planning.',
    descZh: '用于修复规划的渗透汇总。',
    outEn: '## Penetration test summary — Apr 2026 engagement\n\n### Scope\nExternal attack surface: `api.*` + `app.*` production; excluded partner integrations.\n\n### Key findings\n- **CRITICAL:** SSRF via webhook callback URL allowing metadata service access\n- **HIGH:** OAuth redirect parameter allows open redirects on login\n- **HIGH:** IDOR on document export endpoint for shared links\n\n### Business impact\nPotential tenant data exposure and account takeover paths; elevated urgency for customer trust.\n\n### Remediation plan (30/60/90)\n- **0–30d:** patch SSRF with URL allowlist + block private IP ranges; hotfix open redirect\n- **31–60d:** unify authorization checks on export endpoints; add integration tests\n- **61–90d:** implement continuous DAST in CI for top routes\n\n### Status tracking\nFindings logged as SEC-1201..SEC-1210 with owners in Jira project SEC.',
    outZh: '## 渗透测试摘要 — 2026 年 4 月\n\n### 范围\n外部攻击面：`api.*` + `app.*` 生产；不含伙伴集成。\n\n### 关键发现\n- **严重：** Webhook 回调 SSRF 可访问元数据服务\n- **高：** OAuth 重定向开放重定向\n- **高：** 共享链接导出接口 IDOR\n\n### 业务影响\n可能导致租户数据暴露与账户接管路径；对客户信任影响大。\n\n### 修复（30/60/90）\n- **0–30 天：** SSRF 修 URL 白名单 + 阻断私网；热修开放重定向\n- **31–60 天：** 导出接口统一鉴权；补集成测试\n- **61–90 天：** CI 对核心路由持续 DAST\n\n### 跟踪\n发现登记为 SEC-1201..SEC-1210，负责人在 Jira SEC 项目',
  }),
];
