'use strict';

/** engineering-manager, product-manager, sales-manager, hr-manager (13 skills) */
module.exports = (build) => [
  build({
    category: 'management/engineering-manager',
    slug: 'sprint_retro_summary',
    mcp: 'em_sprint_retro_summary',
    name: 'Sprint Retrospective Summary',
    nameZh: '迭代回顾总结',
    tags: ['sprint', 'retrospective', 'agile', 'engineering', 'action-items'],
    tagsZh: ['迭代', '回顾', '敏捷', '工程', '行动项'],
    personaEn:
      'You are an engineering manager who facilitates blameless sprint retrospectives and converts discussion into owned, measurable improvements.',
    personaZh: '你是工程经理，擅长无责迭代回顾，能把讨论转化为有负责人、可衡量的改进项。',
    objectiveEn:
      'From sprint context, team notes, and optional metrics, produce a structured retro summary with highlights, improvements, root causes, decisions, and an action table.',
    objectiveZh: '基于迭代背景、团队纪要与可选指标，输出结构化回顾：亮点、改进、根因、决策与行动表。',
    audienceEn: 'Engineering team and stakeholders who need a concise retro record.',
    audienceZh: '工程团队与需要回顾纪要的干系人。',
    outputFormatEn:
      'Markdown: highlights → what went well → what to improve → root causes → decisions → action table (owner, due date, success metric).',
    outputFormatZh:
      'Markdown：亮点 → 做得好 → 待改进 → 根因 → 决策 → 行动表（负责人、截止日期、成功指标）。',
    vars: [
      {
        name: 'sprint_name',
        descriptionEn: 'Sprint name or date range',
        descriptionZh: '迭代名称或周期',
        exampleEn: 'Sprint 24 (Apr 1–14)',
        exampleZh: '迭代 24（4/1–4/14）',
        required: true,
      },
      {
        name: 'team_notes',
        descriptionEn: 'Raw notes, themes, or survey bullets',
        descriptionZh: '原始纪要、主题或问卷要点',
        exampleEn: 'Deploy pain; unclear priorities; flaky tests in CI',
        exampleZh: '发布痛苦；优先级不清；CI 测试不稳定',
        required: true,
      },
      {
        name: 'metrics_snapshot',
        descriptionEn: 'Optional velocity or quality metrics',
        descriptionZh: '可选的速度或质量指标',
        exampleEn: 'Velocity 34 points; 2 incidents; 18% flaky reruns',
        exampleZh: '速度 34 点；2 次事故；18% 重跑',
        required: false,
      },
    ],
    userEn:
      'Sprint: {{sprint_name}}\n\nNotes:\n{{team_notes}}\n\nMetrics (optional):\n{{metrics_snapshot}}\n\nProduce the retrospective summary.',
    userZh:
      '迭代：{{sprint_name}}\n\n纪要：\n{{team_notes}}\n\n指标（可选）：\n{{metrics_snapshot}}\n\n请生成回顾总结。',
    descEn: 'Turns retro notes into a blameless summary with clear owners and dates.',
    descZh: '把回顾纪要整理为无责总结，并明确负责人与日期。',
    outEn:
      '## Sprint 24 retrospective summary\n\n### Highlights\n- Shipped payments exporter behind a feature flag with no SEVs.\n\n### What went well\n- Pairing between backend and SRE reduced rollout time.\n\n### What to improve\n- CI flakiness drove ~18% unnecessary reruns.\n\n### Root causes\n- Shared fixtures carried hidden state; jobs raced on the same sandbox bucket.\n\n### Decisions\n- Quarantine flaky tests; block merges only on the stable suite.\n\n### Actions\n| Action | Owner | Due | Metric |\n|--------|-------|-----|--------|\n| Fix top flaky tests | QA Lead | Apr 21 | Flaky rate <3% |\n| Document sandbox isolation | SRE | Apr 18 | Zero cross-job collisions |',
    outZh:
      '## 迭代 24 回顾总结\n\n### 亮点\n- 支付导出在特性开关保护下上线，无严重事故。\n\n### 做得好\n- 后端与 SRE 协作缩短发布时间。\n\n### 待改进\n- CI 不稳定导致约 18% 无效重跑。\n\n### 根因\n- 共享夹具隐含状态；任务争抢沙箱桶。\n\n### 决策\n- 隔离不稳定测试；仅稳定套件阻塞合并。\n\n### 行动项\n| 行动项 | 负责人 | 截止 | 指标 |\n|--------|--------|------|------|\n| 修复主要不稳定用例 | 测试负责人 | 4/21 | 不稳定率 <3% |\n| 文档化沙箱隔离 | SRE | 4/18 | 零任务冲突 |',
    systemExtraEn: '\n- Avoid blaming individuals; focus on systems and processes',
    systemExtraZh: '\n- 不对个人追责；聚焦系统与流程',
  }),
  build({
    category: 'management/engineering-manager',
    slug: 'technical_decision_record',
    mcp: 'em_technical_decision_record',
    name: 'Architecture Decision Record',
    nameZh: '技术决策记录（ADR）',
    tags: ['ADR', 'architecture', 'decision', 'engineering', 'documentation'],
    tagsZh: ['架构', '决策', '工程', '文档', '技术方案'],
    personaEn:
      'You are a principal engineer / engineering manager who writes crisp ADRs that capture context, options, and consequences.',
    personaZh: '你是首席工程师/工程经理，擅长撰写简洁 ADR，记录背景、方案与后果。',
    objectiveEn:
      'From problem statement, constraints, and options, produce an ADR with status, context, decision, consequences, and follow-ups.',
    objectiveZh: '基于问题、约束与备选方案，输出含状态、背景、决策、后果与跟进的 ADR。',
    audienceEn: 'Engineering teams and architects reviewing technical direction.',
    audienceZh: '工程团队与架构评审方。',
    outputFormatEn: 'Markdown ADR template: title, status, context, decision, consequences, alternatives considered, links.',
    outputFormatZh: 'Markdown ADR：标题、状态、背景、决策、后果、备选方案、链接。',
    vars: [
      {
        name: 'problem',
        descriptionEn: 'Problem or decision to capture',
        descriptionZh: '需要记录的问题或决策',
        exampleEn: 'Choose stream processing stack for fraud alerts',
        exampleZh: '为欺诈告警选择流处理技术栈',
        required: true,
      },
      {
        name: 'options',
        descriptionEn: 'Options considered with pros/cons',
        descriptionZh: '备选方案及利弊',
        exampleEn: 'Flink vs Kafka Streams vs managed service',
        exampleZh: 'Flink / Kafka Streams / 托管服务',
        required: true,
      },
      {
        name: 'constraints',
        descriptionEn: 'Constraints (latency, cost, team skills)',
        descriptionZh: '约束（延迟、成本、团队技能）',
        exampleEn: 'P99 <2s, $50k/year budget, small platform team',
        exampleZh: 'P99<2s，年预算 50k，小平台团队',
        required: false,
      },
    ],
    userEn: 'Problem:\n{{problem}}\n\nOptions:\n{{options}}\n\nConstraints:\n{{constraints}}\n\nWrite the ADR.',
    userZh: '问题：\n{{problem}}\n\n备选：\n{{options}}\n\n约束：\n{{constraints}}\n\n请撰写 ADR。',
    descEn: 'Produces a consistent ADR for technical decisions.',
    descZh: '为技术决策生成结构化 ADR。',
    outEn:
      '## ADR-014: Stream processing for fraud alerts\n\n**Status:** Accepted\n\n### Context\nWe need sub-2s enrichment for rule updates without taking down the hot path.\n\n### Decision\nAdopt Flink on managed Kubernetes with checkpointing to object storage; start with a single job template owned by Platform.\n\n### Consequences\n- Positive: mature ecosystem, backpressure controls, unified monitoring.\n- Negative: operational overhead until runbooks mature.\n\n### Alternatives considered\n- Kafka Streams: simpler ops but weaker complex-event support for our rules DSL.\n- Fully managed SaaS: fastest time-to-value but data residency risk.\n\n### Follow-ups\n- SLO dashboard by Apr 30; chaos test checkpoint restore monthly.',
    outZh:
      '## ADR-014：欺诈告警的流处理选型\n\n**状态：** 已接受\n\n### 背景\n需要在不停机的情况下实现规则更新亚秒级生效。\n\n### 决策\n在托管 Kubernetes 上采用 Flink，检查点写入对象存储；由平台团队维护单一作业模板。\n\n### 后果\n- 正面：生态成熟、背压可控、监控统一。\n- 负面：在运行手册完善前运维成本较高。\n\n### 备选方案\n- Kafka Streams：运维更简单但复杂规则表达能力不足。\n- 全托管 SaaS：上线最快但数据驻留风险。\n\n### 跟进\n- 4/30 前完成 SLO 面板；每月演练检查点恢复。',
  }),
  build({
    category: 'management/engineering-manager',
    slug: 'team_capacity_planning',
    mcp: 'em_team_capacity_planning',
    name: 'Team Capacity Planning',
    nameZh: '团队产能规划',
    tags: ['capacity', 'planning', 'engineering', 'roadmap', 'forecast'],
    tagsZh: ['产能', '规划', '工程', '路线图', '预测'],
    personaEn:
      'You are an engineering manager who balances roadmap ambition with sustainable throughput, vacations, and on-call load.',
    personaZh: '你是工程经理，能在路线图野心与可持续产能、假期与值班之间取得平衡。',
    objectiveEn:
      'From backlog themes, team roster, and time horizon, produce a capacity plan with expected throughput, risks, and staffing recommendations.',
    objectiveZh: '基于待办主题、团队编制与时间范围，输出产能计划：预期吞吐、风险与人员建议。',
    audienceEn: 'Engineering leadership and product partners.',
    audienceZh: '工程负责人与产品伙伴。',
    outputFormatEn:
      'Markdown: assumptions → capacity math → planned throughput → risks → asks (hiring, scope cuts, pairing).',
    outputFormatZh: 'Markdown：假设 → 产能计算 → 计划吞吐 → 风险 → 诉求（招聘、砍范围、结对）。',
    vars: [
      {
        name: 'horizon',
        descriptionEn: 'Planning horizon',
        descriptionZh: '规划周期',
        exampleEn: 'Next quarter (Q2 FY25)',
        exampleZh: '下季度（FY25 Q2）',
        required: true,
      },
      {
        name: 'team_roster',
        descriptionEn: 'Roles, FTE, vacations, on-call',
        descriptionZh: '角色、FTE、假期、值班',
        exampleEn: '6 engineers, 1 on-call rotation, 2 weeks holidays in May',
        exampleZh: '6 名工程师，1 套值班轮换，5 月两周假期',
        required: true,
      },
      {
        name: 'work_items',
        descriptionEn: 'Planned epics or commitments',
        descriptionZh: '计划史诗或承诺',
        exampleEn: 'Platform hardening, billing revamp, two customer commitments',
        exampleZh: '平台加固、计费改造、两个客户承诺',
        required: true,
      },
    ],
    userEn: 'Horizon:\n{{horizon}}\n\nTeam:\n{{team_roster}}\n\nWork:\n{{work_items}}\n\nDraft the capacity plan.',
    userZh: '周期：\n{{horizon}}\n\n团队：\n{{team_roster}}\n\n工作：\n{{work_items}}\n\n请输出产能规划。',
    descEn: 'Quarterly capacity view with explicit trade-offs.',
    descZh: '季度产能视图，明确取舍。',
    outEn:
      '## Q2 FY25 capacity plan (Platform team)\n\n### Assumptions\n- 6 FTE engineers, 0.2 FTE equivalent lost to on-call interrupts historically.\n- Target sustainable velocity: 30 story points per sprint (2 weeks).\n\n### Capacity math\n- 6 sprint cycles in Q2 → ~180 points if no slippage.\n- Reserve 15% for tech debt and incidents → ~150 points for product epics.\n\n### Planned throughput\n- Billing revamp: 70 points (two engineers).\n- Platform hardening: 50 points.\n- Customer commitments: 40 points (needs PM guardrails).\n\n### Risks\n- May holiday cluster reduces two sprints; billing has unknown integration spikes.\n\n### Asks\n- Approve a 0.5 contractor for 6 weeks OR descope customer B deliverable to Q3.',
    outZh:
      '## FY25 Q2 产能规划（平台团队）\n\n### 假设\n- 6 名工程师；历史值班打断约 0.2 FTE。\n- 可持续速度：每迭代 30 点（两周）。\n\n### 产能计算\n- Q2 共 6 个迭代 → 理论约 180 点。\n- 预留 15% 技术债与事故 → 产品史诗约 150 点。\n\n### 计划吞吐\n- 计费改造：70 点（两人）。\n- 平台加固：50 点。\n- 客户承诺：40 点（需产品边界）。\n\n### 风险\n- 五一假期集中，影响两个迭代；计费对接存在未知峰值。\n\n### 诉求\n- 批准 6 周 0.5 外包，或将客户 B 交付推迟到 Q3。',
  }),

  build({
    category: 'management/product-manager',
    slug: 'user_story_writing',
    mcp: 'pm_user_story_writing',
    name: 'User Story Writing',
    nameZh: '用户故事撰写',
    tags: ['user-story', 'requirements', 'agile', 'product', 'acceptance-criteria'],
    tagsZh: ['用户故事', '需求', '敏捷', '产品', '验收标准'],
    personaEn:
      'You are a senior product manager who writes testable user stories with clear acceptance criteria and edge cases.',
    personaZh: '你是资深产品经理，能写出可测试的用户故事、清晰验收标准与边界场景。',
    objectiveEn:
      'From persona, goal, and constraints, produce user stories with acceptance criteria suitable for Gherkin-style tests.',
    objectiveZh: '基于角色、目标与约束，输出含验收标准的用户故事，便于 Gherkin 化测试。',
    audienceEn: 'Engineering and QA partners.',
    audienceZh: '工程与测试伙伴。',
    outputFormatEn: 'Markdown: epic link → user stories → acceptance criteria → notes/risks.',
    outputFormatZh: 'Markdown：史诗链接 → 用户故事 → 验收标准 → 备注/风险。',
    vars: [
      {
        name: 'persona_goal',
        descriptionEn: 'User persona and job-to-be-done',
        descriptionZh: '用户画像与要完成的工作',
        exampleEn: 'Finance admin reconciling payouts weekly',
        exampleZh: '财务管理员每周对账打款',
        required: true,
      },
      {
        name: 'feature_idea',
        descriptionEn: 'Feature or change description',
        descriptionZh: '功能或变更描述',
        exampleEn: 'Bulk export of settlement lines with filters',
        exampleZh: '按筛选条件批量导出结算明细',
        required: true,
      },
      {
        name: 'constraints',
        descriptionEn: 'Non-goals, compliance, performance',
        descriptionZh: '非目标、合规、性能',
        exampleEn: 'Must respect RBAC; export <10k rows under 30s',
        exampleZh: '遵循 RBAC；1 万行内导出 <30 秒',
        required: false,
      },
    ],
    userEn: 'Persona & goal:\n{{persona_goal}}\n\nFeature:\n{{feature_idea}}\n\nConstraints:\n{{constraints}}\n\nWrite user stories.',
    userZh: '角色与目标：\n{{persona_goal}}\n\n功能：\n{{feature_idea}}\n\n约束：\n{{constraints}}\n\n请写用户故事。',
    descEn: 'Clear stories with acceptance criteria for delivery.',
    descZh: '带验收标准、便于交付的用户故事。',
    outEn:
      '## User stories: settlement export\n\n### Story 1\n**As a** finance admin **I want** to filter settlement lines by date range and status **so that** I can reconcile weekly payouts quickly.\n\n**Acceptance criteria**\n- Given I select a 7-day window, when I click Export CSV, then a file downloads with all matching rows and a stable column order.\n- Given I lack the FinanceExporter role, when I open the page, then export actions are disabled with an RBAC tooltip.\n- Given more than 10,000 rows match, when I export, then I see a warning and the job runs asynchronously with a download link.\n\n### Notes\n- Edge case: daylight-saving week boundaries must use org timezone.',
    outZh:
      '## 用户故事：结算导出\n\n### 故事 1\n**作为** 财务管理员 **我希望** 按日期区间与状态筛选结算明细 **以便** 快速完成周对账。\n\n**验收标准**\n- 当我选择 7 天窗口并点击导出 CSV，则下载文件包含匹配行且列顺序稳定。\n- 当我没有 FinanceExporter 角色，则导出按钮禁用并提示权限原因。\n- 当匹配行超过 1 万，则提示异步任务并返回下载链接。\n\n### 备注\n- 边界：夏令时周界需使用组织时区。',
  }),
  build({
    category: 'management/product-manager',
    slug: 'competitive_analysis',
    mcp: 'pm_competitive_analysis',
    name: 'Competitive Analysis',
    nameZh: '竞品分析',
    tags: ['competitive', 'market', 'strategy', 'product', 'positioning'],
    tagsZh: ['竞品', '市场', '战略', '产品', '定位'],
    personaEn:
      'You are a product manager who synthesizes competitive intel into decisions, not slide filler.',
    personaZh: '你是产品经理，能把竞品信息沉淀为决策而非堆砌幻灯片。',
    objectiveEn:
      'From competitors, features, and customer pains, produce a comparison matrix with implications and recommendations.',
    objectiveZh: '基于竞品、功能与客户痛点，输出对比矩阵、启示与建议。',
    audienceEn: 'Product and GTM leadership.',
    audienceZh: '产品与 GTM 管理层。',
    outputFormatEn: 'Markdown: summary → comparison table → differentiation → risks → recommended bets.',
    outputFormatZh: 'Markdown：摘要 → 对比表 → 差异化 → 风险 → 建议押注。',
    vars: [
      {
        name: 'market_context',
        descriptionEn: 'Market segment and ICP',
        descriptionZh: '细分市场与 ICP',
        exampleEn: 'Mid-market B2B payments in EU',
        exampleZh: '欧洲中型 B2B 支付',
        required: true,
      },
      {
        name: 'competitors',
        descriptionEn: 'Competitor list and notes',
        descriptionZh: '竞品列表与要点',
        exampleEn: 'CompA: strong UX; CompB: pricing; CompC: bank integrations',
        exampleZh: 'A：体验强；B：价格；C：银行对接',
        required: true,
      },
      {
        name: 'our_strengths',
        descriptionEn: 'Our differentiators today',
        descriptionZh: '我方现有优势',
        exampleEn: 'Workflow automation, SOC2, local support',
        exampleZh: '流程自动化、SOC2、本地支持',
        required: false,
      },
    ],
    userEn: 'Market:\n{{market_context}}\n\nCompetitors:\n{{competitors}}\n\nOur strengths:\n{{our_strengths}}\n\nProduce the analysis.',
    userZh: '市场：\n{{market_context}}\n\n竞品：\n{{competitors}}\n\n我方优势：\n{{our_strengths}}\n\n请输出分析。',
    descEn: 'Actionable competitive matrix with bets.',
    descZh: '可执行的竞品矩阵与押注建议。',
    outEn:
      '## Competitive snapshot — EU mid-market payouts\n\n### Summary\nBuyers optimize for time-to-first-transaction and bank coverage; UX parity is table stakes.\n\n### Comparison\n| Dimension | Us | CompA | CompB |\n|-----------|----|-------|-------|\n| Onboarding TTFV | 3 days | 2 days | 5 days |\n| Bank coverage (EU) | 180 | 210 | 95 |\n| Workflow automation | Strong | Medium | Weak |\n\n### Differentiation we can own\n- Deeper ERP reconciliation templates for finance teams.\n\n### Risks\n- CompA investing in local SDR coverage; pricing pressure from CompB.\n\n### Recommended bets\n- Ship 3 reconciliation templates in 60 days; publish benchmark study with 2 design partners.',
    outZh:
      '## 竞品快照 — 欧洲中型支付\n\n### 摘要\n买家关注首笔交易耗时与银行覆盖；体验差距需补齐。\n\n### 对比\n| 维度 | 我方 | A | B |\n|------|------|---|---|\n| 上线 TTFV | 3 天 | 2 天 | 5 天 |\n| 欧盟银行覆盖 | 180 | 210 | 95 |\n| 流程自动化 | 强 | 中 | 弱 |\n\n### 可强化的差异化\n- 面向财务团队的 ERP 对账模板深度。\n\n### 风险\n- A 加强本地销售；B 价格压力。\n\n### 建议押注\n- 60 天内交付 3 个对账模板；与 2 家设计伙伴发布对标研究。',
  }),
  build({
    category: 'management/product-manager',
    slug: 'release_notes_drafting',
    mcp: 'pm_release_notes_drafting',
    name: 'Release Notes Drafting',
    nameZh: '发布说明撰写',
    tags: ['release', 'changelog', 'product', 'communication', 'customers'],
    tagsZh: ['发布', '变更日志', '产品', '沟通', '客户'],
    personaEn:
      'You are a product manager who writes customer-truthful release notes with clear value and upgrade guidance.',
    personaZh: '你是产品经理，能写出对客户诚实、价值清晰、升级指引明确的发布说明。',
    objectiveEn:
      'From feature list, audience (internal vs external), and risk items, draft release notes with highlights, improvements, fixes, and known issues.',
    objectiveZh: '基于功能清单、受众（对内/对外）与风险项，撰写含亮点、改进、修复与已知问题的发布说明。',
    audienceEn: 'Customers, CS, and sales.',
    audienceZh: '客户、客服与销售。',
    outputFormatEn: 'Markdown release notes: title, overview, highlights, improvements, fixes, known issues, rollout.',
    outputFormatZh: 'Markdown：标题、概述、亮点、改进、修复、已知问题、发布策略。',
    vars: [
      {
        name: 'version',
        descriptionEn: 'Release version or date',
        descriptionZh: '版本或日期',
        exampleEn: 'v2.14.0 (Apr 8, 2026)',
        exampleZh: 'v2.14.0（2026-04-08）',
        required: true,
      },
      {
        name: 'changes',
        descriptionEn: 'Shipped changes with engineering labels',
        descriptionZh: '已交付变更（含工程标签）',
        exampleEn: 'PR-882 exporter filters; PR-901 RBAC fix; PR-905 perf',
        exampleZh: 'PR-882 导出筛选；PR-901 权限修复；PR-905 性能',
        required: true,
      },
      {
        name: 'audience',
        descriptionEn: 'External customers vs internal',
        descriptionZh: '对外客户或对内',
        exampleEn: 'External SaaS tenants',
        exampleZh: '对外 SaaS 租户',
        required: true,
      },
    ],
    userEn: 'Version:\n{{version}}\n\nChanges:\n{{changes}}\n\nAudience:\n{{audience}}\n\nDraft release notes.',
    userZh: '版本：\n{{version}}\n\n变更：\n{{changes}}\n\n受众：\n{{audience}}\n\n请撰写发布说明。',
    descEn: 'Customer-ready release notes from engineering change list.',
    descZh: '从工程变更清单生成面向客户的发布说明。',
    outEn:
      '## Release v2.14.0 — Apr 8, 2026\n\n### Overview\nThis release improves settlement exports and tightens RBAC around finance actions.\n\n### Highlights\n- **Filtered CSV exports** for finance admins with async jobs for large datasets.\n- **Clearer permission errors** when roles are missing.\n\n### Improvements\n- Export column order is now stable for downstream automation.\n\n### Fixes\n- Resolved intermittent timeout when filtering >5k rows.\n\n### Known issues\n- Async exports may take up to 10 minutes at peak; retry once before contacting support.\n\n### Rollout\n- Rolling deployment to all regions; no manual migration required.',
    outZh:
      '## 版本 v2.14.0 — 2026-04-08\n\n### 概述\n本版本改进结算导出，并强化财务相关 RBAC。\n\n### 亮点\n- **筛选 CSV 导出**，大数据集走异步任务。\n- **权限错误提示更清晰**。\n\n### 改进\n- 导出列顺序稳定，便于下游自动化。\n\n### 修复\n- 修复 >5000 行筛选偶发超时。\n\n### 已知问题\n- 高峰异步导出可能需 10 分钟；请先重试再联系支持。\n\n### 发布\n- 全区域滚动发布；无需手工迁移。',
  }),

  build({
    category: 'management/sales-manager',
    slug: 'territory_planning',
    mcp: 'sm_territory_planning',
    name: 'Territory Planning',
    nameZh: '区域与账户规划',
    tags: ['territory', 'sales', 'planning', 'accounts', 'coverage'],
    tagsZh: ['区域', '销售', '规划', '客户', '覆盖'],
    personaEn:
      'You are a sales manager who designs fair territories with clear coverage rules and pipeline targets.',
    personaZh: '你是销售经理，能设计公平区域、清晰覆盖规则与管道目标。',
    objectiveEn:
      'From ICP, rep roster, and account data, propose territory splits, coverage model, and quarterly targets.',
    objectiveZh: '基于 ICP、代表编制与账户数据，提出区域划分、覆盖模型与季度目标。',
    audienceEn: 'Sales leadership and RevOps.',
    audienceZh: '销售管理层与营收运营。',
    outputFormatEn: 'Markdown: principles → segments → territory map → quotas → risks.',
    outputFormatZh: 'Markdown：原则 → 细分 → 区域图 → 配额 → 风险。',
    vars: [
      {
        name: 'icp',
        descriptionEn: 'Ideal customer profile',
        descriptionZh: '理想客户画像',
        exampleEn: '500–5000 employees, multi-entity finance teams',
        exampleZh: '500–5000 人，多主体财务团队',
        required: true,
      },
      {
        name: 'reps',
        descriptionEn: 'Reps, regions, capacity',
        descriptionZh: '代表、区域、产能',
        exampleEn: '4 AEs in DACH + Nordics, 2 SDRs',
        exampleZh: 'DACH+北欧 4 名 AE，2 名 SDR',
        required: true,
      },
      {
        name: 'accounts',
        descriptionEn: 'Account tiers or counts',
        descriptionZh: '客户分层或数量',
        exampleEn: '120 Tier1, 400 Tier2, long tail in partner channel',
        exampleZh: '一级 120，二级 400，长尾走渠道',
        required: true,
      },
    ],
    userEn: 'ICP:\n{{icp}}\n\nReps:\n{{reps}}\n\nAccounts:\n{{accounts}}\n\nDraft territory plan.',
    userZh: 'ICP：\n{{icp}}\n\n团队：\n{{reps}}\n\n客户：\n{{accounts}}\n\n请输出区域规划。',
    descEn: 'Balanced territory design with explicit rules.',
    descZh: '平衡的区域设计，规则明确。',
    outEn:
      '## FY26 H1 territory plan — Northern Europe\n\n### Principles\n- Minimize account churn at rep transitions; Tier1 accounts single-threaded.\n- SDRs focus on Tier2 pipeline creation; AEs own close plans.\n\n### Segments\n- **Tier1:** >€250k ACV potential, named accounts.\n- **Tier2:** €50–250k potential, industry clusters.\n\n### Territory map\n- **AE-North:** SE, NO, FI named list (32 Tier1).\n- **AE-Central:** DE-North + DK (28 Tier1).\n- **AE-DACH-South:** AT + CH + DE-South (30 Tier1).\n\n### Targets (Q2)\n- Pipeline coverage 3.2x quota per AE; 18 qualified meetings/month per SDR pair.\n\n### Risks\n- Two AEs new to enterprise motion — add shadowing weeks and smaller patch swaps in May.',
    outZh:
      '## FY26 上半年区域规划 — 北欧\n\n### 原则\n- 换防时最小化客户动荡；一级客户单线负责。\n- SDR 主攻二级管道；AE 负责结案路径。\n\n### 细分\n- **一级：** 潜客 ACV >25 万欧元，点名客户。\n- **二级：** 5–25 万欧元潜力，行业簇。\n\n### 区域划分\n- **AE-北：** 瑞典/挪威/芬兰点名（32 个一级）。\n- **AE-中：** 德北+丹麦（28 个一级）。\n- **AE-DACH 南：** 奥瑞+德南（30 个一级）。\n\n### Q2 目标\n- 每 AE 管道覆盖 ≥3.2x 配额；每对 SDR 月 18 次有效会议。\n\n### 风险\n- 两名 AE 新上手企业销售 — 5 月安排跟访周并缩小片区交换范围。',
  }),
  build({
    category: 'management/sales-manager',
    slug: 'deal_review_coaching',
    mcp: 'sm_deal_review_coaching',
    name: 'Deal Review Coaching',
    nameZh: '大单复盘辅导',
    tags: ['deal-review', 'coaching', 'sales', 'pipeline', 'strategy'],
    tagsZh: ['大单复盘', '辅导', '销售', '管道', '策略'],
    personaEn:
      'You are a sales manager who runs rigorous deal reviews and coaches reps on strategy, risks, and next actions.',
    personaZh: '你是销售经理，能做大单复盘并辅导代表在策略、风险与下一步行动上对齐。',
    objectiveEn:
      'From deal snapshot, produce coaching notes: MEDDPICC gaps, risks, stakeholder plan, and a 7-day action plan.',
    objectiveZh: '基于商机快照，输出辅导：MEDDPICC 缺口、风险、干系人计划与 7 日行动。',
    audienceEn: 'AE and sales manager.',
    audienceZh: '销售代表与经理。',
    outputFormatEn: 'Markdown: deal summary → qualification → risks → coaching questions → 7-day plan.',
    outputFormatZh: 'Markdown：商机摘要 → 资质 → 风险 → 辅导提问 → 7 日计划。',
    vars: [
      {
        name: 'deal',
        descriptionEn: 'Deal details: stage, value, timeline',
        descriptionZh: '商机：阶段、金额、时间线',
        exampleEn: '€180k ACV, proposal stage, CFO engaged, close by May 30',
        exampleZh: '18 万 ACV，方案阶段，CFO 已介入，5/30 结案',
        required: true,
      },
      {
        name: 'rep_notes',
        descriptionEn: 'Rep notes and blockers',
        descriptionZh: '代表备注与阻碍',
        exampleEn: 'Champion strong; legal slow on DPA; competitor CompA pricing',
        exampleZh: '支持者强；法务 DPA 慢；竞品 A 价格压力',
        required: true,
      },
    ],
    userEn: 'Deal:\n{{deal}}\n\nRep notes:\n{{rep_notes}}\n\nRun deal review coaching.',
    userZh: '商机：\n{{deal}}\n\n代表备注：\n{{rep_notes}}\n\n请做大单复盘辅导。',
    descEn: 'Structured deal coaching with a short action plan.',
    descZh: '结构化大单辅导与短周期行动。',
    outEn:
      '## Deal review — Acme EU rollout\n\n### Snapshot\n€180k ACV, proposal stage, target close May 30; CFO engaged, procurement not yet involved.\n\n### Qualification (MEDDPICC)\n- **Metrics:** ROI case drafted but not validated with finance — gap.\n- **Economic buyer:** CFO met once; needs second meeting with numbers tied to payroll savings.\n- **Decision process:** Unclear legal timeline; DPA stuck 12 days.\n\n### Risks\n- CompA offering 15% discount; we lack a procurement sponsor.\n\n### Coaching questions for rep\n1. Who owns procurement and what is their evaluation checklist?\n2. What happens if May 30 slips — is there a compelling event?\n\n### 7-day plan\n- Mon: Schedule CFO working session with pre-read ROI worksheet.\n- Wed: Escalate DPA with mutual NDA path; propose redline turnaround SLA.\n- Fri: Add procurement contact and map approval chain.',
    outZh:
      '## 大单复盘 — Acme 欧洲上线\n\n### 快照\n18 万 ACV，方案阶段，目标 5/30 结案；CFO 已见面，采购未入场。\n\n### 资质（MEDDPICC）\n- **指标：** ROI 草稿未与财务共创 — 缺口。\n- **经济决策人：** CFO 需第二次会议，把数字与人力节省挂钩。\n- **决策流程：** 法务 DPA 卡 12 天，时间不明。\n\n### 风险\n- 竞品 A 降价 15%；我方缺少采购赞助人。\n\n### 辅导提问\n1. 采购负责人是谁，评估清单是什么？\n2. 若 5/30 延期，是否有强驱动事件？\n\n### 7 日计划\n- 周一：约 CFO 工作坊，提前发送 ROI 表。\n- 周三：推进 DPA，建议红线 SLA。\n- 周五：补齐采购联系人并绘制审批链。',
  }),
  build({
    category: 'management/sales-manager',
    slug: 'forecast_accuracy_review',
    mcp: 'sm_forecast_accuracy_review',
    name: 'Forecast Accuracy Review',
    nameZh: '预测准确性复盘',
    tags: ['forecast', 'pipeline', 'sales', 'accuracy', 'revops'],
    tagsZh: ['预测', '管道', '销售', '准确性', '营收运营'],
    personaEn:
      'You are a sales manager who diagnoses forecast misses with data, not opinions.',
    personaZh: '你是销售经理，能用数据诊断预测偏差而非凭感觉。',
    objectiveEn:
      'From forecast history and pipeline movements, summarize accuracy, root causes, and process fixes.',
    objectiveZh: '基于预测历史与管道变动，总结准确性、根因与流程修复。',
    audienceEn: 'Sales leadership and RevOps.',
    audienceZh: '销售管理层与营收运营。',
    outputFormatEn: 'Markdown: accuracy summary → variance drivers → hygiene issues → playbook updates.',
    outputFormatZh: 'Markdown：准确性摘要 → 偏差驱动 → 卫生问题 → 流程更新。',
    vars: [
      {
        name: 'period',
        descriptionEn: 'Review period',
        descriptionZh: '复盘周期',
        exampleEn: 'Q1 FY26',
        exampleZh: 'FY26 Q1',
        required: true,
      },
      {
        name: 'numbers',
        descriptionEn: 'Forecast vs actual, slippage, stage changes',
        descriptionZh: '预测与实际、滑点、阶段变化',
        exampleEn: 'Commit 4.2M vs 3.6M actual; 22% slipped from commit',
        exampleZh: '承诺 420 万 vs 实际 360 万；22% 从承诺滑落',
        required: true,
      },
    ],
    userEn: 'Period:\n{{period}}\n\nNumbers:\n{{numbers}}\n\nWrite forecast accuracy review.',
    userZh: '周期：\n{{period}}\n\n数据：\n{{numbers}}\n\n请写预测准确性复盘。',
    descEn: 'Forecast post-mortem with process improvements.',
    descZh: '预测复盘与流程改进。',
    outEn:
      '## Q1 FY26 forecast accuracy review\n\n### Summary\nCommit forecast missed by 14% overall; largest variance in enterprise deals >€100k.\n\n### Drivers\n- **Slippage:** 22% of commit deals slipped due to legal/procurement not mapped early.\n- **Sandbagging:** SMB segment beat by 9% — reps under-committed after Q4 burn.\n\n### Hygiene issues\n- 31% of late-stage deals lacked next-step dates; champion changes not logged.\n\n### Playbook updates\n- Require procurement contact before "Proposal" stage.\n- Weekly manager audit of next-step dates for >€50k deals.\n- RevOps dashboard: slippage reason codes mandatory on close-date moves.',
    outZh:
      '## FY26 Q1 预测准确性复盘\n\n### 摘要\n整体承诺预测偏差 -14%；>10 万欧元企业单偏差最大。\n\n### 驱动因素\n- **滑点：** 22% 承诺商机因法务/采购未提前映射而延期。\n- **保守：** SMB 超出 9% — Q4 透支后代表低估承诺。\n\n### 卫生问题\n- 31% 后期商机缺少下一步日期；支持者变更未记录。\n\n### 流程更新\n- 进入“方案”阶段前必须补齐采购联系人。\n- >5 万欧元商机每周由经理核对下一步日期。\n- RevOps 看板：改结案日期必须填写滑点原因码。',
  }),
  build({
    category: 'management/sales-manager',
    slug: 'sales_new_hire_ramp',
    mcp: 'sm_sales_new_hire_ramp',
    name: 'Sales New-Hire Ramp Plan',
    nameZh: '销售新人爬坡计划',
    tags: ['onboarding', 'sales', 'ramp', 'training', 'enablement'],
    tagsZh: ['入职', '销售', '爬坡', '培训', '赋能'],
    personaEn:
      'You are a sales manager who ramps new hires with clear milestones, shadowing, and measurable outputs.',
    personaZh: '你是销售经理，能用清晰里程碑、跟访与可衡量产出做好销售新人爬坡。',
    objectiveEn:
      'From role (AE/SDR), product complexity, and tools, produce a 30-60-90 ramp plan with activities and checkpoints.',
    objectiveZh: '基于角色（AE/SDR）、产品复杂度与工具，输出 30-60-90 爬坡计划、活动与检查点。',
    audienceEn: 'New hire and enablement partners.',
    audienceZh: '新人与赋能伙伴。',
    outputFormatEn: 'Markdown: goals → 30/60/90 plan → certifications → coaching cadence.',
    outputFormatZh: 'Markdown：目标 → 30/60/90 → 认证 → 辅导节奏。',
    vars: [
      {
        name: 'role',
        descriptionEn: 'Role and segment',
        descriptionZh: '角色与细分',
        exampleEn: 'Enterprise AE, DACH',
        exampleZh: '企业 AE，DACH',
        required: true,
      },
      {
        name: 'product_context',
        descriptionEn: 'Product motion and tools',
        descriptionZh: '产品模式与工具',
        exampleEn: 'PLG + sales assist; Salesforce + Outreach',
        exampleZh: 'PLG+销售辅助；Salesforce+Outreach',
        required: true,
      },
    ],
    userEn: 'Role:\n{{role}}\n\nProduct/tools:\n{{product_context}}\n\nDraft ramp plan.',
    userZh: '角色：\n{{role}}\n\n产品/工具：\n{{product_context}}\n\n请写爬坡计划。',
    descEn: 'Practical AE/SDR ramp with week-by-week focus.',
    descZh: '可执行的 AE/SDR 爬坡，按周聚焦。',
    outEn:
      '## 90-day ramp — Enterprise AE (DACH)\n\n### Goals\n- Day 30: product certified + 10 discovery calls completed.\n- Day 60: 3 qualified opportunities created; MEDDPICC coach checks.\n- Day 90: first small win or clear path to €200k+ opportunity.\n\n### 30-day plan\n- Weeks 1–2: shadow 6 customer calls; learn ICP and talk tracks.\n- Weeks 3–4: run discovery with manager coaching; build territory map with RevOps.\n\n### 60-day plan\n- Co-build 2 mutual success plans with champions; run pricing drills.\n\n### 90-day plan\n- Own a territory patch; present QBR-ready narrative for top 5 accounts.\n\n### Cadence\n- Biweekly 1:1 on pipeline hygiene; weekly deal review for active opps.',
    outZh:
      '## 90 天爬坡 — 企业 AE（DACH）\n\n### 目标\n- 30 天：产品认证 + 完成 10 次发现拜访。\n- 60 天：创建 3 个合格商机；完成 MEDDPICC 辅导。\n- 90 天：首单小胜或明确 >20 万欧元路径。\n\n### 30 天\n- 第 1–2 周：跟访 6 次客户会议；掌握 ICP 与话术。\n- 第 3–4 周：在经理辅导下做发现；与 RevOps 绘制区域地图。\n\n### 60 天\n- 与支持者共创 2 份成功计划；做定价演练。\n\n### 90 天\n- 独立负责片区；为前 5 大客户准备类 QBR 叙事。\n\n### 节奏\n- 双周 1:1 看管道卫生；每周复盘在跑商机。',
  }),

  build({
    category: 'management/hr-manager',
    slug: 'engagement_survey_analysis',
    mcp: 'hrm_engagement_survey_analysis',
    name: 'Engagement Survey Analysis',
    nameZh: '员工敬业度调研分析',
    tags: ['engagement', 'survey', 'HR', 'culture', 'action-plan'],
    tagsZh: ['敬业度', '调研', '人力', '文化', '行动计划'],
    personaEn:
      'You are an HR manager who translates survey results into prioritized, measurable people actions.',
    personaZh: '你是 HR 经理，能把调研结果转化为可优先排序、可衡量的人员行动。',
    objectiveEn:
      'From survey scores, themes, and demographics, produce insights, focus areas, and a 90-day action plan.',
    objectiveZh: '基于分数、主题与人口维度，输出洞察、重点领域与 90 天行动计划。',
    audienceEn: 'Leadership and people team.',
    audienceZh: '管理层与人力团队。',
    outputFormatEn: 'Markdown: headline insights → drivers → risks → actions (owner, metric, date).',
    outputFormatZh: 'Markdown：关键洞察 → 驱动因素 → 风险 → 行动（负责人、指标、日期）。',
    vars: [
      {
        name: 'survey_data',
        descriptionEn: 'Scores, benchmarks, key comments',
        descriptionZh: '分数、对标、关键评论',
        exampleEn: 'eNPS 12; lowest in Engineering; comments on unclear career paths',
        exampleZh: 'eNPS 12；工程最低；反馈职业发展路径不清',
        required: true,
      },
      {
        name: 'org_context',
        descriptionEn: 'Headcount, sites, recent changes',
        descriptionZh: '人数、地点、近期变化',
        exampleEn: '420 employees, 3 hubs, hiring freeze in Q1',
        exampleZh: '420 人，3 地办公室，Q1 招聘冻结',
        required: false,
      },
    ],
    userEn: 'Survey data:\n{{survey_data}}\n\nOrg context:\n{{org_context}}\n\nAnalyze and plan.',
    userZh: '调研数据：\n{{survey_data}}\n\n组织背景：\n{{org_context}}\n\n请分析与规划。',
    descEn: 'Survey synthesis with leadership-ready actions.',
    descZh: '调研综合，便于管理层落地。',
    outEn:
      '## Engagement pulse — Q1 FY26\n\n### Headline insights\n- eNPS 12 vs benchmark 25; largest drop in Engineering (-18 pts).\n- Top theme: unclear growth paths; second theme: meeting load.\n\n### Drivers\n- IC3–IC4 engineers report missing visibility into promo criteria.\n- Managers cite 25h/week in cross-team meetings.\n\n### Risks\n- Attrition risk in platform team if no career framework update by Q3.\n\n### 90-day actions\n| Action | Owner | Metric | Due |\n|--------|-------|--------|-----|\n| Publish IC3–IC5 expectations matrix | HRBP + Eng Dir | 90% managers trained | May 15 |\n| Pilot no-meeting Wednesday | COO office | Meeting hours -10% | Jun 1 |\n| Quarterly career conversations template | HR | 100% teams adopt | Apr 30 |',
    outZh:
      '## 敬业度快评 — FY26 Q1\n\n### 关键洞察\n- eNPS 12，低于对标 25；工程团队降幅最大（-18）。\n- 主题一：成长路径不清；主题二：会议负荷。\n\n### 驱动因素\n- IC3–IC4 工程师反馈晋升标准不透明。\n- 经理反馈每周跨团队会议约 25 小时。\n\n### 风险\n- 若 Q3 前不更新职业框架，平台团队流失风险上升。\n\n### 90 天行动\n| 行动 | 负责人 | 指标 | 截止 |\n|------|--------|------|------|\n| 发布 IC3–IC5 期望矩阵 | HRBP+工程总监 | 90% 经理完成培训 | 5/15 |\n| 试点周三无会日 | COO 办公室 | 会议时长 -10% | 6/1 |\n| 季度职业发展谈话模板 | HR | 100% 团队采用 | 4/30 |',
  }),
  build({
    category: 'management/hr-manager',
    slug: 'disciplinary_action_doc',
    mcp: 'hrm_disciplinary_action_doc',
    name: 'Disciplinary Action Documentation',
    nameZh: '纪律处分文档',
    tags: ['HR', 'disciplinary', 'compliance', 'documentation', 'workplace'],
    tagsZh: ['人力', '纪律', '合规', '文档', '职场'],
    personaEn:
      'You are an HR manager who documents performance or conduct issues with factual, neutral language and clear expectations.',
    personaZh: '你是 HR 经理，能用客观中立的表述记录绩效或行为问题，并明确期望。',
    objectiveEn:
      'From incident notes and policy context, draft a documentation memo with timeline, facts, policy references, and improvement plan.',
    objectiveZh: '基于事件纪要与制度背景，撰写纪要：时间线、事实、制度引用与改进计划。',
    audienceEn: 'Employee, manager, and HR file.',
    audienceZh: '员工、经理与人力档案。',
    outputFormatEn: 'Markdown memo: summary → facts → policy → expectations → signatures checklist.',
    outputFormatZh: 'Markdown 纪要：摘要 → 事实 → 制度 → 期望 → 签署清单。',
    vars: [
      {
        name: 'facts',
        descriptionEn: 'Chronological facts (no opinions)',
        descriptionZh: '按时间事实（不含主观评价）',
        exampleEn: 'Missed 3 deadlines in Feb; client escalation on Mar 4',
        exampleZh: '2 月三次逾期；3/4 客户升级',
        required: true,
      },
      {
        name: 'policy',
        descriptionEn: 'Relevant policy names or excerpts',
        descriptionZh: '相关制度名称或摘录',
        exampleEn: 'Code of Conduct §4.2; PIP policy v3',
        exampleZh: '行为准则 §4.2；PIP 制度 v3',
        required: true,
      },
      {
        name: 'improvement_plan',
        descriptionEn: 'Agreed actions and metrics',
        descriptionZh: '已达成共识的行动与指标',
        exampleEn: 'Weekly check-ins; deliver milestone doc by Apr 20',
        exampleZh: '每周对齐；4/20 前交付里程碑文档',
        required: false,
      },
    ],
    userEn: 'Facts:\n{{facts}}\n\nPolicy:\n{{policy}}\n\nImprovement plan:\n{{improvement_plan}}\n\nDraft documentation.',
    userZh: '事实：\n{{facts}}\n\n制度：\n{{policy}}\n\n改进计划：\n{{improvement_plan}}\n\n请起草纪要。',
    descEn: 'Neutral HR documentation with clear next steps.',
    descZh: '中立的人力纪要与清晰下一步。',
    outEn:
      '## Documentation of discussion — performance expectations\n\n**Date:** Apr 7, 2026\n**Participants:** Employee, Manager, HRBP\n\n### Summary\nWe reviewed repeated missed deliverables in February and a client escalation on March 4. The purpose is to align on expectations and support improvement.\n\n### Facts (chronological)\n- Feb 3, 10, 17: three committed dates missed without 48-hour advance notice.\n- Mar 4: customer success filed escalation ticket #4412 regarding delayed integration guide.\n\n### Policy references\n- Code of Conduct §4.2 on professional reliability.\n- Performance Improvement Policy v3 outlines documentation steps.\n\n### Expectations\n- Provide weekly written status each Friday.\n- Deliver integration guide v1 by Apr 20; escalate blockers within 24 hours.\n\n### Signatures\n- Employee acknowledgment: __  Manager: __  HRBP: __',
    outZh:
      '## 谈话纪要 — 绩效期望\n\n**日期：** 2026-04-07\n**参与：** 员工、经理、HRBP\n\n### 摘要\n回顾 2 月多次交付逾期及 3/4 客户升级。目的是对齐期望并支持改进。\n\n### 事实（时间顺序）\n- 2/3、2/10、2/17：三次承诺日期未交付且未提前 48 小时说明。\n- 3/4：客户成功提交升级工单 #4412（集成指南延迟）。\n\n### 制度引用\n- 行为准则 §4.2（职业可靠性）。\n- 绩效改进制度 v3（文档化步骤）。\n\n### 期望\n- 每周五提交书面进展。\n- 4/20 前交付集成指南 v1；阻碍需在 24 小时内上报。\n\n### 签署\n- 员工确认：__  经理：__  HRBP：__',
    systemExtraEn: '\n- Do not provide legal advice; recommend counsel when unsure',
    systemExtraZh: '\n- 不提供法律意见；不确定时建议咨询法务',
  }),
  build({
    category: 'management/hr-manager',
    slug: 'onboarding_plan',
    mcp: 'hrm_onboarding_plan',
    name: 'New-Hire Onboarding Plan',
    nameZh: '新员工入职计划',
    tags: ['onboarding', 'HR', 'new-hire', 'checklist', '30-60-90'],
    tagsZh: ['入职', '人力', '新人', '清单', '30-60-90'],
    personaEn:
      'You are an HR manager who designs onboarding that accelerates time-to-productivity and belonging.',
    personaZh: '你是 HR 经理，能设计加速产出与归属感的入职计划。',
    objectiveEn:
      'From role, team, and systems, produce a week-1 and 30-day onboarding plan with owners and resources.',
    objectiveZh: '基于角色、团队与系统，输出首周与 30 天入职计划，含负责人与资料。',
    audienceEn: 'Manager, buddy, and new hire.',
    audienceZh: '经理、伙伴与新人。',
    outputFormatEn: 'Markdown: pre-day-1 → week 1 → day 30 checklist → feedback touchpoints.',
    outputFormatZh: 'Markdown：到岗前 → 第 1 周 → 第 30 天清单 → 反馈触点。',
    vars: [
      {
        name: 'role',
        descriptionEn: 'Role and location',
        descriptionZh: '角色与地点',
        exampleEn: 'Senior backend engineer, remote EU',
        exampleZh: '资深后端工程师，远程欧洲',
        required: true,
      },
      {
        name: 'systems',
        descriptionEn: 'Tools and access needs',
        descriptionZh: '工具与权限',
        exampleEn: 'GitHub, AWS, Jira, Slack, Okta',
        exampleZh: 'GitHub、AWS、Jira、Slack、Okta',
        required: true,
      },
    ],
    userEn: 'Role:\n{{role}}\n\nSystems:\n{{systems}}\n\nCreate onboarding plan.',
    userZh: '角色：\n{{role}}\n\n系统：\n{{systems}}\n\n请制定入职计划。',
    descEn: 'Structured onboarding with clear owners.',
    descZh: '结构化入职，负责人清晰。',
    outEn:
      '## Onboarding plan — Senior backend engineer (remote EU)\n\n### Before day 1\n- IT ships laptop; manager sends team intro + reading list.\n- HR confirms payroll, handbook acknowledgment, and benefits enrollment.\n\n### Week 1\n- Day 1: buddy intro, account provisioning, security training.\n- Day 2–3: architecture walkthrough; shadow on-call handoff (read-only).\n- Day 4–5: pick a starter ticket; submit first PR with reviewer pairing.\n\n### Day 30\n- Complete AWS least-privilege access review with security champion.\n- Present "how our billing pipeline works" mini-session to team.\n- Manager 1:1 on expectations and growth themes.\n\n### Feedback\n- Day 14 pulse survey; day 30 onboarding retro with HRBP.',
    outZh:
      '## 入职计划 — 资深后端（远程欧洲）\n\n### 到岗前\n- IT 寄送电脑；经理发送团队介绍与阅读清单。\n- HR 确认薪酬、手册签署与福利入项。\n\n### 第 1 周\n- 第 1 天：伙伴对接、开通账号、安全培训。\n- 第 2–3 天：架构走读；跟访值班交接（只读）。\n- 第 4–5 天：认领 starter 工单；在评审结对下提交首个 PR。\n\n### 第 30 天\n- 与安全伙伴完成 AWS 最小权限复核。\n- 向团队分享“计费流水线如何工作”小课堂。\n- 经理 1:1 对齐期望与成长主题。\n\n### 反馈\n- 第 14 天轻量问卷；第 30 天与 HRBP 做入职复盘。',
  }),
];
