'use strict';

/** operations-manager, finance-manager, marketing-manager (15 skills) */
module.exports = (build) => [
  build({
    category: 'management/operations-manager',
    slug: 'capacity_planning',
    mcp: 'om_capacity_planning',
    name: 'Operations Capacity Planning',
    nameZh: '运营产能规划',
    tags: ['capacity', 'operations', 'planning', 'SLA', 'throughput'],
    tagsZh: ['产能', '运营', '规划', 'SLA', '吞吐'],
    personaEn:
      'You are an operations manager who aligns demand, staffing, and SLAs with realistic buffers.',
    personaZh: '你是运营经理，能在需求、编制与 SLA 之间做出现实缓冲。',
    objectiveEn:
      'From demand forecast, staffing, and SLA targets, produce a capacity plan with utilization targets and risk mitigations.',
    objectiveZh: '基于需求预测、编制与 SLA 目标，输出产能计划：利用率目标与风险缓解。',
    audienceEn: 'Ops leadership and finance partners.',
    audienceZh: '运营与财务伙伴。',
    outputFormatEn: 'Markdown: assumptions → demand → supply → gap analysis → mitigations.',
    outputFormatZh: 'Markdown：假设 → 需求 → 供给 → 缺口 → 缓解措施。',
    vars: [
      {
        name: 'demand',
        descriptionEn: 'Volumes, seasonality, SLAs',
        descriptionZh: '业务量、季节性、SLA',
        exampleEn: '12k tickets/month peak; 4h P95 response',
        exampleZh: '峰值月 1.2 万工单；P95 4 小时响应',
        required: true,
      },
      {
        name: 'supply',
        descriptionEn: 'Headcount, shifts, productivity',
        descriptionZh: '人力、班次、效率',
        exampleEn: '18 agents, 85% occupancy target, 12 min handle time',
        exampleZh: '18 名坐席，目标占用率 85%，处理时长 12 分钟',
        required: true,
      },
    ],
    userEn: 'Demand:\n{{demand}}\n\nSupply:\n{{supply}}\n\nDraft capacity plan.',
    userZh: '需求：\n{{demand}}\n\n供给：\n{{supply}}\n\n请写产能规划。',
    descEn: 'Ops capacity view with explicit SLA trade-offs.',
    descZh: '运营产能视图，明确 SLA 取舍。',
    outEn:
      '## Capacity plan — Customer support (Q2)\n\n### Assumptions\n- Peak month +18% vs baseline; SLA: P95 first response 4h.\n\n### Demand\n- ~12k tickets/month peak; 22% require engineering escalations.\n\n### Supply\n- 18 agents, 40h/week, 85% occupancy, AHT 12 minutes → ~9.5k resolved tickets/month at peak efficiency.\n\n### Gap\n- ~2.5k ticket gap unless deflection improves or hours expand.\n\n### Mitigations\n- Launch macro library for top 10 intents (target -12% volume).\n- Add 2 contractors for 8 weeks through peak.\n- Shift 5% of L2 work to async knowledge base updates.',
    outZh:
      '## 产能规划 — 客服（Q2）\n\n### 假设\n- 峰值月较基线 +18%；SLA：P95 首响 4 小时。\n\n### 需求\n- 峰值月约 1.2 万工单；22% 需工程升级。\n\n### 供给\n- 18 名坐席，每周 40 小时，占用率 85%，AHT 12 分钟 → 峰值效率下约 9500 单/月。\n\n### 缺口\n- 约 2500 单缺口，除非自助解决提升或延长工时。\n\n### 缓解\n- 上线前十意图宏模板（目标 -12% 量）。\n- 峰值 8 周增加 2 名外包。\n- 将 5% L2 工作转为异步知识库更新。',
  }),
  build({
    category: 'management/operations-manager',
    slug: 'sla_review_report',
    mcp: 'om_sla_review_report',
    name: 'SLA Review Report',
    nameZh: 'SLA 复盘报告',
    tags: ['SLA', 'operations', 'metrics', 'review', 'incidents'],
    tagsZh: ['SLA', '运营', '指标', '复盘', '事故'],
    personaEn:
      'You are an operations manager who reviews SLA performance with trends, incidents, and corrective actions.',
    personaZh: '你是运营经理，能复盘 SLA 表现：趋势、事故与纠正措施。',
    objectiveEn:
      'From SLA metrics and incident log, produce an executive SLA review with breaches, root causes, and fixes.',
    objectiveZh: '基于 SLA 指标与事故日志，输出管理层 SLA 复盘：违约、根因与修复。',
    audienceEn: 'COO and service owners.',
    audienceZh: 'COO 与服务负责人。',
    outputFormatEn: 'Markdown: executive summary → metrics table → breaches → actions.',
    outputFormatZh: 'Markdown：执行摘要 → 指标表 → 违约 → 行动。',
    vars: [
      {
        name: 'metrics',
        descriptionEn: 'SLA targets vs actuals',
        descriptionZh: 'SLA 目标与实际',
        exampleEn: 'P95 response 3.8h vs 4h target; uptime 99.92%',
        exampleZh: 'P95 响应 3.8h vs 目标 4h；可用性 99.92%',
        required: true,
      },
      {
        name: 'incidents',
        descriptionEn: 'Major incidents affecting SLA',
        descriptionZh: '影响 SLA 的重大事件',
        exampleEn: 'Mar 12 vendor DNS outage 47m customer impact',
        exampleZh: '3/12 供应商 DNS 故障，客户影响 47 分钟',
        required: false,
      },
    ],
    userEn: 'Metrics:\n{{metrics}}\n\nIncidents:\n{{incidents}}\n\nWrite SLA review.',
    userZh: '指标：\n{{metrics}}\n\n事件：\n{{incidents}}\n\n请写 SLA 复盘。',
    descEn: 'SLA performance narrative with corrective actions.',
    descZh: 'SLA 表现叙事与纠正行动。',
    outEn:
      '## SLA review — March 2026\n\n### Executive summary\nWe met customer-facing response SLAs overall, but two vendor incidents created short breaches in EU-West.\n\n### Metrics\n| SLA | Target | Actual | Status |\n|-----|--------|--------|--------|\n| P95 first response | 4.0h | 3.8h | Met |\n| Uptime | 99.9% | 99.92% | Met |\n\n### Breaches\n- Mar 12: DNS provider outage caused 47m impact; breach on premium tier response SLA.\n\n### Actions\n- Add secondary DNS with automated failover test monthly.\n- Publish customer comms template for vendor-wide incidents.',
    outZh:
      '## SLA 复盘 — 2026 年 3 月\n\n### 执行摘要\n整体达成面向客户的响应 SLA，但两次供应商事件导致西欧短暂违约。\n\n### 指标\n| SLA | 目标 | 实际 | 状态 |\n|-----|------|------|------|\n| P95 首响 | 4.0h | 3.8h | 达成 |\n| 可用性 | 99.9% | 99.92% | 达成 |\n\n### 违约\n- 3/12：DNS 供应商故障，影响 47 分钟；高级版响应 SLA 违约。\n\n### 行动\n- 增加备用 DNS，每月自动化故障切换演练。\n- 发布供应商级事件的客户沟通模板。',
  }),
  build({
    category: 'management/operations-manager',
    slug: 'vendor_performance_review',
    mcp: 'om_vendor_performance_review',
    name: 'Vendor Performance Review',
    nameZh: '供应商绩效评估',
    tags: ['vendor', 'operations', 'procurement', 'performance', 'review'],
    tagsZh: ['供应商', '运营', '采购', '绩效', '评估'],
    personaEn:
      'You are an operations manager who evaluates vendors on delivery, quality, risk, and cost.',
    personaZh: '你是运营经理，能从交付、质量、风险与成本评估供应商。',
    objectiveEn:
      'From KPIs, issues, and contract terms, draft a vendor scorecard with recommendations (renew, renegotiate, replace).',
    objectiveZh: '基于 KPI、问题与合同条款，输出供应商评分卡与建议（续约、重谈、替换）。',
    audienceEn: 'Procurement and executive sponsors.',
    audienceZh: '采购与高管赞助人。',
    outputFormatEn: 'Markdown: summary → scorecard → issues → recommendations → negotiation levers.',
    outputFormatZh: 'Markdown：摘要 → 评分卡 → 问题 → 建议 → 谈判抓手。',
    vars: [
      {
        name: 'vendor',
        descriptionEn: 'Vendor name and scope',
        descriptionZh: '供应商名称与范围',
        exampleEn: 'LogiFreight — EU inbound logistics',
        exampleZh: 'LogiFreight — 欧洲入向物流',
        required: true,
      },
      {
        name: 'kpis',
        descriptionEn: 'KPI results and trends',
        descriptionZh: 'KPI 结果与趋势',
        exampleEn: 'OTIF 94% vs 96% target; 3 invoice disputes',
        exampleZh: 'OTIF 94% vs 目标 96%；3 次发票争议',
        required: true,
      },
    ],
    userEn: 'Vendor:\n{{vendor}}\n\nKPIs:\n{{kpis}}\n\nWrite performance review.',
    userZh: '供应商：\n{{vendor}}\n\nKPI：\n{{kpis}}\n\n请写绩效评估。',
    descEn: 'Vendor scorecard with renewal guidance.',
    descZh: '供应商评分卡与续约建议。',
    outEn:
      '## Vendor performance — LogiFreight (Q1)\n\n### Summary\nDelivery reliability slipped slightly; finance hygiene issues increased admin load.\n\n### Scorecard\n| Area | Score (1-5) | Notes |\n|------|-------------|-------|\n| Delivery | 3 | OTIF 94% vs 96% |\n| Quality | 4 | Damage rate stable |\n| Responsiveness | 4 | Incidents acknowledged <30m |\n| Cost | 3 | 2 unexpected accessorial charges |\n\n### Recommendations\n- **Renegotiate** SLA credits for Q2 if OTIF <95% persists.\n- Require weekly invoice reconciliation office hours.\n\n### Replace? Not yet — alternate vendor quotes as backup for EU peak season.',
    outZh:
      '## 供应商绩效 — LogiFreight（Q1）\n\n### 摘要\n交付可靠性略降；财务对账问题增加管理成本。\n\n### 评分卡\n| 维度 | 分（1-5） | 说明 |\n|------|-----------|------|\n| 交付 | 3 | OTIF 94% vs 96% |\n| 质量 | 4 | 货损率稳定 |\n| 响应 | 4 | 事故 <30 分钟确认 |\n| 成本 | 3 | 2 次意外附加费 |\n\n### 建议\n- **重谈** 若 Q2 OTIF <95% 持续，争取 SLA 抵扣。\n- 要求每周固定对账窗口。\n\n### 是否替换：暂否 — 旺季前准备备选报价。',
  }),
  build({
    category: 'management/operations-manager',
    slug: 'process_improvement_proposal',
    mcp: 'om_process_improvement_proposal',
    name: 'Process Improvement Proposal',
    nameZh: '流程改进提案（精益）',
    tags: ['lean', 'process', 'operations', 'improvement', 'efficiency'],
    tagsZh: ['精益', '流程', '运营', '改进', '效率'],
    personaEn:
      'You are an operations manager who uses lean framing (waste, flow, standard work) to improve processes.',
    personaZh: '你是运营经理，能用精益视角（浪费、流动、标准作业）改进流程。',
    objectiveEn:
      'From current process pain, metrics, and constraints, propose improvements with pilot plan and measures.',
    objectiveZh: '基于现状痛点、指标与约束，提出改进方案、试点与衡量方式。',
    audienceEn: 'Process owners and leadership.',
    audienceZh: '流程负责人与管理层。',
    outputFormatEn: 'Markdown: problem → current state → future state → pilot → metrics.',
    outputFormatZh: 'Markdown：问题 → 现状 → 未来态 → 试点 → 指标。',
    vars: [
      {
        name: 'process',
        descriptionEn: 'Process name and scope',
        descriptionZh: '流程名称与范围',
        exampleEn: 'Customer refund approvals',
        exampleZh: '客户退款审批',
        required: true,
      },
      {
        name: 'pain',
        descriptionEn: 'Pain points and data',
        descriptionZh: '痛点与数据',
        exampleEn: 'Avg 6.2 days; 14 handoffs; 9% rework',
        exampleZh: '平均 6.2 天；14 次转手；9% 返工',
        required: true,
      },
    ],
    userEn: 'Process:\n{{process}}\n\nPain/data:\n{{pain}}\n\nDraft improvement proposal.',
    userZh: '流程：\n{{process}}\n\n痛点/数据：\n{{pain}}\n\n请写改进提案。',
    descEn: 'Lean-style process improvement with a pilot.',
    descZh: '精益式流程改进含试点。',
    outEn:
      '## Process improvement — Refund approvals\n\n### Problem\nCustomers wait 6.2 days on average due to sequential approvals and unclear criteria.\n\n### Current state\n- 14 handoffs across CS → Finance → Risk for >$500 refunds.\n- 9% rework from missing invoice metadata.\n\n### Future state\n- Tiered policy: auto-approve <$200 with fraud checks; single approver <$1k.\n- Standard work checklist embedded in ticket template.\n\n### Pilot (30 days)\n- Run new policy for EU SMB segment; daily defect review.\n\n### Metrics\n- Cycle time P95 <48h; rework <3%; CSAT +5 pts.',
    outZh:
      '## 流程改进 — 退款审批\n\n### 问题\n客户平均等待 6.2 天，因串行审批与标准不清。\n\n### 现状\n- >500 美元退款在客服→财务→风控间 14 次转手。\n- 9% 返工因发票元数据缺失。\n\n### 未来态\n- 分层策略：<200 美元自动（含风控）；<1000 美元单人审批。\n- 工单模板嵌入标准作业清单。\n\n### 试点（30 天）\n- 在欧洲 SMB 试运行；每日缺陷复盘。\n\n### 指标\n- 周期 P95 <48 小时；返工 <3%；CSAT +5。',
  }),
  build({
    category: 'management/operations-manager',
    slug: 'ops_escalation_playbook',
    mcp: 'om_ops_escalation_playbook',
    name: 'Operational Escalation Playbook',
    nameZh: '运营升级手册',
    tags: ['escalation', 'operations', 'incident', 'playbook', 'communication'],
    tagsZh: ['升级', '运营', '事件', '手册', '沟通'],
    personaEn:
      'You are an operations manager who defines clear escalation paths, owners, and customer comms.',
    personaZh: '你是运营经理，能定义清晰的升级路径、负责人与客户沟通。',
    objectiveEn:
      'From service tiers and org chart, produce an escalation playbook with triggers, SLAs, and templates.',
    objectiveZh: '基于服务分层与组织架构，输出升级手册：触发条件、SLA 与模板。',
    audienceEn: 'On-call teams and CS leadership.',
    audienceZh: '值班团队与客服管理层。',
    outputFormatEn: 'Markdown: tiers → triggers → RACI → comms templates → post-incident review.',
    outputFormatZh: 'Markdown：分层 → 触发 → RACI → 沟通模板 → 事后复盘。',
    vars: [
      {
        name: 'services',
        descriptionEn: 'Critical services and customers',
        descriptionZh: '关键服务与客户',
        exampleEn: 'Payments API, data pipeline; enterprise tier customers',
        exampleZh: '支付 API、数据管道；企业级客户',
        required: true,
      },
      {
        name: 'stakeholders',
        descriptionEn: 'Teams and executives',
        descriptionZh: '团队与高管',
        exampleEn: 'SRE, CS, Legal, CFO for financial incidents',
        exampleZh: 'SRE、客服、法务、财务（资金类事件）',
        required: true,
      },
    ],
    userEn: 'Services:\n{{services}}\n\nStakeholders:\n{{stakeholders}}\n\nWrite playbook.',
    userZh: '服务：\n{{services}}\n\n干系人：\n{{stakeholders}}\n\n请写手册。',
    descEn: 'Operational escalation paths with comms templates.',
    descZh: '运营升级路径与沟通模板。',
    outEn:
      '## Ops escalation playbook — Payments\n\n### Severity tiers\n- **SEV1:** customer money movement impaired → page on-call + exec within 15m.\n- **SEV2:** degraded latency impacting >10% traffic → manager bridge within 30m.\n\n### Triggers\n- Error budget burn >50% in 24h; PSP partner status page red; fraud spike >3σ.\n\n### RACI\n- **Incident commander:** SRE lead (A), CS comms (C), Legal review for regulatory touch (C).\n\n### Comms templates\n- **Customer update (30m):** scope, impact, next update time.\n- **Internal exec (60m):** customer count, financial exposure estimate, mitigation.\n\n### Post-incident\n- Blameless retro within 5 business days; action owners named.',
    outZh:
      '## 运营升级手册 — 支付\n\n### 严重级别\n- **SEV1：** 影响客户资金流转 → 15 分钟内拉值班与高管。\n- **SEV2：** >10% 流量体验降级 → 30 分钟内经理桥接。\n\n### 触发条件\n- 24 小时错误预算消耗 >50%；PSP 伙伴状态页红色；欺诈峰值 >3σ。\n\n### RACI\n- **事件指挥官：** SRE 负责人（A）；客服沟通（C）；涉监管触达需法务（C）。\n\n### 沟通模板\n- **客户更新（30 分钟）：** 范围、影响、下次更新时间。\n- **内部高管（60 分钟）：** 客户数、财务敞口估计、缓解措施。\n\n### 事后\n- 5 个工作日内无责复盘；行动项明确负责人。',
  }),

  build({
    category: 'management/finance-manager',
    slug: 'annual_budget_planning',
    mcp: 'fm_annual_budget_planning',
    name: 'Annual Budget Planning',
    nameZh: '年度预算编制',
    tags: ['budget', 'finance', 'planning', 'forecast', 'FP-A'],
    tagsZh: ['预算', '财务', '规划', '预测', 'FP&A'],
    personaEn:
      'You are a finance manager who builds driver-based budgets with clear assumptions and guardrails.',
    personaZh: '你是财务经理，能构建基于驱动因素的预算，假设与边界清晰。',
    objectiveEn:
      'From revenue plan, headcount, and cost drivers, draft an annual budget narrative with scenarios.',
    objectiveZh: '基于收入计划、人力与成本驱动，撰写年度预算叙事与情景。',
    audienceEn: 'CFO and department heads.',
    audienceZh: 'CFO 与部门负责人。',
    outputFormatEn: 'Markdown: assumptions → P&L walk → headcount → risks → scenarios.',
    outputFormatZh: 'Markdown：假设 → 损益推演 → 人力 → 风险 → 情景。',
    vars: [
      {
        name: 'drivers',
        descriptionEn: 'Revenue and cost drivers',
        descriptionZh: '收入与成本驱动',
        exampleEn: 'ARR +22%; infra +COGS tied to usage; hiring 40 net new',
        exampleZh: 'ARR +22%；基础设施+用量 COGS；净增 40 人',
        required: true,
      },
      {
        name: 'constraints',
        descriptionEn: 'Board or cash constraints',
        descriptionZh: '董事会或现金约束',
        exampleEn: 'Rule of 40 focus; cap opex growth at 18%',
        exampleZh: '关注 Rule of 40；运营费用增速上限 18%',
        required: false,
      },
    ],
    userEn: 'Drivers:\n{{drivers}}\n\nConstraints:\n{{constraints}}\n\nDraft budget plan.',
    userZh: '驱动：\n{{drivers}}\n\n约束：\n{{constraints}}\n\n请写预算方案。',
    descEn: 'Annual budget storyline with scenarios.',
    descZh: '年度预算叙事与情景。',
    outEn:
      '## FY27 budget narrative (draft)\n\n### Assumptions\n- ARR grows 22% with NRR 118%; gross margin improves 1.2 pts via infra optimization.\n- Net hiring +40; sales capacity model ties to pipeline coverage 3.0x.\n\n### P&L walk\n- Revenue: +22%\n- COGS: +18% (usage-linked)\n- OpEx: +16% (below 18% guardrail)\n\n### Risks\n- Enterprise sales cycle elongation; FX headwind ~1.5% on EU revenue.\n\n### Scenarios\n- **Upside:** NRR 122% → +$6M ARR, allows incremental R&D hire.\n- **Downside:** NRR 112% → freeze hiring H2, cut discretionary marketing 10%.',
    outZh:
      '## FY27 预算叙事（草案）\n\n### 假设\n- ARR +22%，NRR 118%；毛利率因基础设施优化 +1.2 点。\n- 净增 40 人；销售产能与 3.0x 管道覆盖挂钩。\n\n### 损益推演\n- 收入：+22%\n- COGS：+18%（与用量相关）\n- OpEx：+16%（低于 18% 边界）\n\n### 风险\n- 企业销售周期拉长；欧元收入汇率逆风约 1.5%。\n\n### 情景\n- **上行：** NRR 122% → ARR +600 万，可增编研发。\n- **下行：** NRR 112% → 下半年冻结招聘，裁减可自由支配营销 10%。',
  }),
  build({
    category: 'management/finance-manager',
    slug: 'month_end_close_checklist',
    mcp: 'fm_month_end_close_checklist',
    name: 'Month-End Close Checklist',
    nameZh: '月末结账清单',
    tags: ['close', 'finance', 'accounting', 'checklist', 'controls'],
    tagsZh: ['结账', '财务', '会计', '清单', '内控'],
    personaEn:
      'You are a finance manager who ensures timely, controlled month-end close with clear owners.',
    personaZh: '你是财务经理，能确保月末结账及时、可控且负责人明确。',
    objectiveEn:
      'From entity list and systems, produce a close checklist with deadlines, dependencies, and controls.',
    objectiveZh: '基于主体与系统，输出结账清单：截止日、依赖与控制点。',
    audienceEn: 'Accounting team and auditors.',
    audienceZh: '会计团队与审计。',
    outputFormatEn: 'Markdown: calendar → tasks by day → dependencies → control evidence.',
    outputFormatZh: 'Markdown：日历 → 按日任务 → 依赖 → 控制证据。',
    vars: [
      {
        name: 'entities',
        descriptionEn: 'Legal entities and currencies',
        descriptionZh: '法人主体与币种',
        exampleEn: 'US parent + UK + DE subsidiaries',
        exampleZh: '美国母公司 + 英国 + 德国子公司',
        required: true,
      },
      {
        name: 'systems',
        descriptionEn: 'ERP, billing, payroll systems',
        descriptionZh: 'ERP、计费、薪酬系统',
        exampleEn: 'NetSuite, Stripe, Workday',
        exampleZh: 'NetSuite、Stripe、Workday',
        required: true,
      },
    ],
    userEn: 'Entities:\n{{entities}}\n\nSystems:\n{{systems}}\n\nBuild close checklist.',
    userZh: '主体：\n{{entities}}\n\n系统：\n{{systems}}\n\n请生成结账清单。',
    descEn: 'Month-end close runbook with controls.',
    descZh: '月末结账手册含控制点。',
    outEn:
      '## Month-end close — Day-by-day checklist\n\n### Day T-3\n- **AR:** reconcile Stripe settlements to bank; attach gateway reports (Owner: AR lead).\n- **Deferrals:** confirm unearned revenue schedule updated for annual contracts.\n\n### Day T-2\n- **Payroll:** post accruals for March bonus run; validate headcount file vs Workday.\n- **FX:** run month-end rates; document ECB source.\n\n### Day T-1\n- **Inventory:** confirm COGS cut-off for EU 3PL snapshot.\n- **Intercompany:** match IC balances; resolve mismatches >$5k same day.\n\n### Day T (close)\n- **Trial balance review:** variance thresholds >2% MoM require controller sign-off.\n- **Controls:** SOX evidence uploaded for revenue, payroll, and cash.',
    outZh:
      '## 月末结账 — 按日清单\n\n### T-3\n- **应收：** 对账 Stripe 结算与银行；附网关报表（负责人：应收负责人）。\n- **递延：** 更新年约未实现收入表。\n\n### T-2\n- **薪酬：** 计提 3 月奖金；核对 Workday 人数文件。\n- **汇率：** 运行月末汇率；记录 ECB 来源。\n\n### T-1\n- **存货：** 确认欧洲三方仓截止快照。\n- **往来：** 对平集团往来；>5000 美元差异当日解决。\n\n### T（结账日）\n- **试算复核：** 环比波动 >2% 需控制人签字。\n- **内控：** 收入、薪酬、现金的 SOX 证据归档。',
  }),
  build({
    category: 'management/finance-manager',
    slug: 'cost_reduction_proposal',
    mcp: 'fm_cost_reduction_proposal',
    name: 'Cost Reduction Proposal',
    nameZh: '降本提案',
    tags: ['cost', 'finance', 'efficiency', 'savings', 'proposal'],
    tagsZh: ['成本', '财务', '效率', '节约', '提案'],
    personaEn:
      'You are a finance manager who identifies savings with implementation plans and guardrails for service quality.',
    personaZh: '你是财务经理，能提出可落地的节约方案并守住服务质量边界。',
    objectiveEn:
      'From spend categories and usage data, propose cost reductions with savings, risks, and timelines.',
    objectiveZh: '基于支出科目与用量数据，提出降本方案：节约额、风险与时间线。',
    audienceEn: 'CFO and budget owners.',
    audienceZh: 'CFO 与预算负责人。',
    outputFormatEn: 'Markdown: baseline → initiatives → savings table → risks → governance.',
    outputFormatZh: 'Markdown：基线 → 举措 → 节约表 → 风险 → 治理。',
    vars: [
      {
        name: 'spend',
        descriptionEn: 'Spend categories and amounts',
        descriptionZh: '支出科目与金额',
        exampleEn: 'Cloud $1.2M, SaaS $420k, travel $180k',
        exampleZh: '云 120 万，SaaS 42 万，差旅 18 万',
        required: true,
      },
      {
        name: 'goals',
        descriptionEn: 'Savings target or constraints',
        descriptionZh: '节约目标或约束',
        exampleEn: 'Target 8% opex reduction without layoffs',
        exampleZh: '在不裁员前提下降运营费用 8%',
        required: true,
      },
    ],
    userEn: 'Spend:\n{{spend}}\n\nGoals:\n{{goals}}\n\nDraft proposal.',
    userZh: '支出：\n{{spend}}\n\n目标：\n{{goals}}\n\n请写提案。',
    descEn: 'Structured cost takeout plan with owners.',
    descZh: '结构化降本计划，负责人明确。',
    outEn:
      '## Cost reduction proposal — FY26 H2\n\n### Baseline opex (annualized)\n- Cloud $1.2M, SaaS $420k, travel $180k\n\n### Initiatives\n| Initiative | Savings | Owner | Timeline |\n|------------|---------|-------|----------|\n| Rightsize K8s clusters + commit discounts | $180k/yr | Platform | 60 days |\n| SaaS license rationalization (duplicate tools) | $90k/yr | IT | 45 days |\n| Travel policy tiering + virtual QBR default | $40k/yr | Ops | Immediate |\n\n### Risks\n- Aggressive cloud cuts could impact peak readiness — add error budget guardrail.\n\n### Governance\n- Weekly savings tracking in FP&A dashboard; freeze new SaaS under $500/mo without approval.',
    outZh:
      '## 降本提案 — FY26 下半年\n\n### 基线运营费用（年化）\n- 云 120 万，SaaS 42 万，差旅 18 万\n\n### 举措\n| 举措 | 节约 | 负责人 | 时间 |\n|------|------|--------|------|\n| K8s 规格优化+承诺折扣 | 18 万/年 | 平台 | 60 天 |\n| SaaS 许可证合并（重复工具） | 9 万/年 | IT | 45 天 |\n| 差旅分层+默认线上 QBR | 4 万/年 | 运营 | 立即 |\n\n### 风险\n- 云资源过猛可能影响峰值 — 加错误预算保护。\n\n### 治理\n- FP&A 看板周跟踪；<$500/月 新 SaaS 需审批。',
  }),
  build({
    category: 'management/finance-manager',
    slug: 'revenue_recognition_memo',
    mcp: 'fm_revenue_recognition_memo',
    name: 'Revenue Recognition Memo',
    nameZh: '收入确认备忘录',
    tags: ['revenue', 'finance', 'ASC-606', 'accounting', 'memo'],
    tagsZh: ['收入', '财务', '准则', '会计', '备忘录'],
    personaEn:
      'You are a finance manager who documents revenue recognition judgments with policy citations and risks.',
    personaZh: '你是财务经理，能记录收入确认判断，引用政策并提示风险。',
    objectiveEn:
      'From contract facts, deliverables, and payment terms, draft a revenue recognition memo outline.',
    objectiveZh: '基于合同事实、交付物与付款条款，起草收入确认备忘录提纲。',
    audienceEn: 'Controller and external auditors.',
    audienceZh: '财务总监与外部审计。',
    outputFormatEn: 'Markdown: facts → performance obligations → timing → estimates → disclosures.',
    outputFormatZh: 'Markdown：事实 → 履约义务 → 时点/时段 → 估计 → 披露。',
    vars: [
      {
        name: 'contract',
        descriptionEn: 'Contract summary',
        descriptionZh: '合同摘要',
        exampleEn: '3-year SaaS + onboarding services + usage overages',
        exampleZh: '三年 SaaS + 上线服务 + 用量超额',
        required: true,
      },
      {
        name: 'facts',
        descriptionEn: 'Key facts (milestones, acceptance, variable consideration)',
        descriptionZh: '关键事实（里程碑、验收、可变对价）',
        exampleEn: 'Onboarding acceptance at 30 days; overages billed monthly',
        exampleZh: '上线 30 天验收；超额按月计费',
        required: true,
      },
    ],
    userEn: 'Contract:\n{{contract}}\n\nFacts:\n{{facts}}\n\nDraft memo outline.',
    userZh: '合同：\n{{contract}}\n\n事实：\n{{facts}}\n\n请写备忘录提纲。',
    descEn: '606-style revenue memo skeleton (informational).',
    descZh: '收入确认备忘录骨架（信息性，非法律意见）。',
    outEn:
      '## Revenue recognition memo — ACME-2026-014 (outline)\n\n### Facts\n- 36-month SaaS subscription with tiered seats.\n- Separate SOW for onboarding services (30-day acceptance).\n- Usage-based API overages billed monthly in arrears.\n\n### Performance obligations\n- **Software subscription:** distinct series of distinct daily services → recognize ratably.\n- **Onboarding:** distinct service → recognize upon acceptance or as services render if milestones met.\n- **Overages:** variable consideration → constrain to expected value with monthly true-up.\n\n### Judgments & estimates\n- Standalone selling price allocation using adjusted market approach.\n\n### Risks / disclosures\n- Disaggregate revenue in footnotes if material; document SSP support.',
    systemExtraEn: '\n- This is not legal or audit advice; involve technical accounting experts',
    systemExtraZh: '\n- 非法律或审计意见；需技术会计专家复核',
    outZh:
      '## 收入确认备忘录 — ACME-2026-014（提纲）\n\n### 事实\n- 36 个月 SaaS 订阅，阶梯席位。\n- 上线服务单独 SOW（30 天验收）。\n- API 超额按月后付。\n\n### 履约义务\n- **订阅：** 按日 distinct → 直线法。\n- **上线：** 单独服务 → 验收或按里程碑进度。\n- **超额：** 可变对价 → 期望值法并月度回冲。\n\n### 判断与估计\n- 用调整后市场法分摊 SSP。\n\n### 风险/披露\n- 重大时脚注拆分收入；保留 SSP 支撑材料。',
  }),
  build({
    category: 'management/finance-manager',
    slug: 'variance_analysis_report',
    mcp: 'fm_variance_analysis_report',
    name: 'Variance Analysis Report',
    nameZh: '差异分析报告',
    tags: ['variance', 'finance', 'forecast', 'analysis', 'reporting'],
    tagsZh: ['差异', '财务', '预测', '分析', '报告'],
    personaEn:
      'You are a finance manager who explains budget vs actual variances with drivers and actions.',
    personaZh: '你是财务经理，能用驱动因素解释预算与实际的差异并提出行动。',
    objectiveEn:
      'From budget and actuals by department, produce a variance report with commentary and follow-ups.',
    objectiveZh: '基于部门预算与实际，输出差异报告：说明与跟进。',
    audienceEn: 'Department heads and CFO.',
    audienceZh: '部门负责人与 CFO。',
    outputFormatEn: 'Markdown: summary table → key variances → root causes → actions.',
    outputFormatZh: 'Markdown：汇总表 → 关键差异 → 根因 → 行动。',
    vars: [
      {
        name: 'period',
        descriptionEn: 'Reporting period',
        descriptionZh: '报告期',
        exampleEn: 'March FY26',
        exampleZh: 'FY26 年 3 月',
        required: true,
      },
      {
        name: 'numbers',
        descriptionEn: 'Budget vs actual by line',
        descriptionZh: '分科目预算 vs 实际',
        exampleEn: 'Marketing +12% over; R&D -4% under; G&A flat',
        exampleZh: '市场 +12% 超支；研发 -4% 节余；管理费用持平',
        required: true,
      },
    ],
    userEn: 'Period:\n{{period}}\n\nNumbers:\n{{numbers}}\n\nWrite variance report.',
    userZh: '期间：\n{{period}}\n\n数据：\n{{numbers}}\n\n请写差异分析。',
    descEn: 'Management variance narrative with actions.',
    descZh: '管理层差异叙事与行动。',
    outEn:
      '## Variance analysis — March FY26\n\n### Summary\n- **Marketing +12% vs budget** driven by two unplanned events and higher paid search CPC.\n- **R&D -4%** due to delayed hiring start dates (3 offers shifted to April).\n\n### Marketing deep dive\n- Event sponsorships: +$85k (two industry shows moved into March).\n- Paid search: +$42k CPC inflation on core keywords.\n\n### Actions\n- Reallocate $60k from Q2 content syndication to cover March events.\n- SEM team runs negative keyword audit weekly through April.\n\n### R&D note\n- Maintain hiring plan; expect April spend to normalize as starts land.',
    outZh:
      '## 差异分析 — FY26 年 3 月\n\n### 摘要\n- **市场 +12%**：两场临时活动 + 搜索 CPC 上升。\n- **研发 -4%：** 3 个入职推迟到 4 月。\n\n### 市场拆解\n- 活动赞助：+8.5 万（两场展会提前到 3 月）。\n- 搜索投放：+4.2 万（核心词 CPC 上涨）。\n\n### 行动\n- 从 Q2 内容分发调剂 6 万覆盖 3 月活动。\n- SEM 团队在 4 月前每周做否定词审计。\n\n### 研发说明\n- 维持招聘计划；预计 4 月费用随入职回归正常。',
  }),

  build({
    category: 'management/marketing-manager',
    slug: 'content_calendar_planning',
    mcp: 'mm_content_calendar_planning',
    name: 'Content Calendar Planning',
    nameZh: '内容日历规划',
    tags: ['content', 'calendar', 'marketing', 'campaign', 'planning'],
    tagsZh: ['内容', '日历', '营销', '战役', '规划'],
    personaEn:
      'You are a marketing manager who builds channel-aware content calendars tied to pipeline goals.',
    personaZh: '你是市场经理，能搭建结合渠道与管道目标的内容日历。',
    objectiveEn:
      'From ICP, offers, and channels, produce a 90-day content calendar with themes, formats, and owners.',
    objectiveZh: '基于 ICP、卖点与渠道，输出 90 天内容日历：主题、形式与负责人。',
    audienceEn: 'Demand gen and product marketing.',
    audienceZh: '获客与产品市场。',
    outputFormatEn: 'Markdown: goals → themes → weekly calendar table → KPIs.',
    outputFormatZh: 'Markdown：目标 → 主题 → 周历表 → KPI。',
    vars: [
      {
        name: 'goals',
        descriptionEn: 'Pipeline or awareness goals',
        descriptionZh: '管道或认知目标',
        exampleEn: '500 MQLs/quarter; launch new analytics module',
        exampleZh: '本季 500 个 MQL；发布新分析模块',
        required: true,
      },
      {
        name: 'channels',
        descriptionEn: 'Channels and capacity',
        descriptionZh: '渠道与产能',
        exampleEn: 'Blog 2/wk, LinkedIn 4/wk, webinar monthly',
        exampleZh: '博客每周 2 篇，领英每周 4 条，网络研讨会每月',
        required: true,
      },
    ],
    userEn: 'Goals:\n{{goals}}\n\nChannels:\n{{channels}}\n\nBuild calendar.',
    userZh: '目标：\n{{goals}}\n\n渠道：\n{{channels}}\n\n请生成日历。',
    descEn: 'Quarterly content calendar aligned to launches.',
    descZh: '与发布节奏对齐的季度内容日历。',
    outEn:
      '## 90-day content calendar — Analytics module launch\n\n### Goals\n- Support launch of **Analytics+** module; generate 500 MQLs in Q2.\n\n### Themes\n- Weeks 1–3: pain of spreadsheet reporting\n- Weeks 4–6: customer proof and ROI math\n- Weeks 7–10: deep dives + competitive contrast\n\n### April snapshot\n| Week | Mon | Wed | Fri |\n|------|-----|-----|-----|\n| W1 | Blog: reporting tax | LinkedIn tip | Customer quote |\n| W2 | Webinar promo | Case study clip | Blog: data quality |\n\n### KPIs\n- MQL conversion by content cohort; webinar registration target 900.',
    outZh:
      '## 90 天内容日历 — Analytics+ 模块发布\n\n### 目标\n- 支撑 **Analytics+** 上线；Q2 获取 500 个 MQL。\n\n### 主题\n- 第 1–3 周：表格报表痛点\n- 第 4–6 周：客户证明与 ROI\n- 第 7–10 周：深度内容 + 竞品对比\n\n### 四月示例\n| 周 | 周一 | 周三 | 周五 |\n|----|------|------|------|\n| W1 | 博客：报表税 | 领英技巧 | 客户金句 |\n| W2 | 研讨会预热 | 案例短视频 | 博客：数据质量 |\n\n### KPI\n- 按内容队列看 MQL 转化；研讨会报名目标 900。',
  }),
  build({
    category: 'management/marketing-manager',
    slug: 'campaign_performance_review',
    mcp: 'mm_campaign_performance_review',
    name: 'Campaign Performance Review',
    nameZh: '营销活动复盘',
    tags: ['campaign', 'performance', 'marketing', 'ROI', 'analytics'],
    tagsZh: ['活动', '绩效', '营销', 'ROI', '分析'],
    personaEn:
      'You are a marketing manager who reviews campaigns with honest attribution limits and next tests.',
    personaZh: '你是市场经理，能在承认归因局限的前提下复盘活动并设计下一轮实验。',
    objectiveEn:
      'From channel metrics and spend, produce a performance review with insights and optimization plan.',
    objectiveZh: '基于渠道指标与花费，输出复盘：洞察与优化计划。',
    audienceEn: 'CMO and demand gen team.',
    audienceZh: 'CMO 与获客团队。',
    outputFormatEn: 'Markdown: summary → funnel metrics → creative/learnings → next tests.',
    outputFormatZh: 'Markdown：摘要 → 漏斗指标 → 素材/经验 → 下一轮测试。',
    vars: [
      {
        name: 'campaign',
        descriptionEn: 'Campaign name and dates',
        descriptionZh: '活动名称与日期',
        exampleEn: 'Analytics+ launch — Mar 1–Apr 15',
        exampleZh: 'Analytics+ 上线 — 3/1–4/15',
        required: true,
      },
      {
        name: 'metrics',
        descriptionEn: 'Spend, impressions, CTR, CPL, pipeline',
        descriptionZh: '花费、曝光、CTR、CPL、管道',
        exampleEn: '$180k spend; CPL $86; 2.1k MQL; $4.2M pipeline influenced',
        exampleZh: '花费 18 万；CPL 86；MQL 2100；影响管道 420 万',
        required: true,
      },
    ],
    userEn: 'Campaign:\n{{campaign}}\n\nMetrics:\n{{metrics}}\n\nWrite review.',
    userZh: '活动：\n{{campaign}}\n\n指标：\n{{metrics}}\n\n请写复盘。',
    descEn: 'Campaign retrospective with next experiments.',
    descZh: '活动复盘与下一轮实验。',
    outEn:
      '## Campaign performance — Analytics+ launch\n\n### Summary\nStrong engagement on technical content; CPL improved after week 3 creative refresh.\n\n### Funnel\n- Spend: $180k\n- MQL: 2,100 (CPL $86 vs $95 benchmark)\n- SQL: 420 (conv 20%)\n- Influenced pipeline: $4.2M (multi-touch attribution)\n\n### Learnings\n- Webinar + technical teardown outperformed generic demos (+32% registration).\n- EU segment under-indexed — localization gap on paid social.\n\n### Next tests\n- Run localized LinkedIn creatives in DE/FR.\n- A/B landing page headline emphasizing compliance use cases.',
    outZh:
      '## 活动复盘 — Analytics+ 上线\n\n### 摘要\n技术向内容互动强；第三周素材更新后 CPL 改善。\n\n### 漏斗\n- 花费：18 万\n- MQL：2100（CPL 86 vs 基准 95）\n- SQL：420（转化率 20%）\n- 影响管道：420 万（多触点归因）\n\n### 经验\n- 网络研讨会 + 技术拆解优于泛化演示（报名 +32%）。\n- 欧洲细分偏低 — 付费社交本地化不足。\n\n### 下一轮测试\n- 德/法本地化领英素材。\n- A/B 落地页标题强调合规场景。',
  }),
  build({
    category: 'management/marketing-manager',
    slug: 'influencer_partnership_brief',
    mcp: 'mm_influencer_partnership_brief',
    name: 'Influencer Partnership Brief',
    nameZh: '达人/合作简报',
    tags: ['influencer', 'partnership', 'marketing', 'brief', 'brand'],
    tagsZh: ['达人', '合作', '营销', '简报', '品牌'],
    personaEn:
      'You are a marketing manager who scopes influencer partnerships with compliance and measurement.',
    personaZh: '你是市场经理，能界定达人合作范围、合规与衡量方式。',
    objectiveEn:
      'From campaign goals and brand guidelines, draft a partnership brief with deliverables, dos/don\'ts, and KPIs.',
    objectiveZh: '基于活动目标与品牌规范，撰写合作简报：交付物、禁忌与 KPI。',
    audienceEn: 'Creators and legal review.',
    audienceZh: '创作者与法务复核。',
    outputFormatEn: 'Markdown: overview → messaging → deliverables → legal → KPIs.',
    outputFormatZh: 'Markdown：概述 → 信息屋 → 交付 → 法务 → KPI。',
    vars: [
      {
        name: 'goals',
        descriptionEn: 'Campaign goals and audience',
        descriptionZh: '活动目标与受众',
        exampleEn: 'Reach finance admins in EU; promote trust + security story',
        exampleZh: '触达欧洲财务管理员；传递信任与安全故事',
        required: true,
      },
      {
        name: 'creator',
        descriptionEn: 'Creator profile and channel',
        descriptionZh: '达人画像与渠道',
        exampleEn: 'YouTube 120k subs, B2B SaaS reviews',
        exampleZh: 'YouTube 12 万订阅，B2B SaaS 测评',
        required: true,
      },
    ],
    userEn: 'Goals:\n{{goals}}\n\nCreator:\n{{creator}}\n\nDraft brief.',
    userZh: '目标：\n{{goals}}\n\n达人：\n{{creator}}\n\n请写简报。',
    descEn: 'Influencer brief with brand guardrails.',
    descZh: '含品牌边界的达人简报。',
    outEn:
      '## Partnership brief — Creator: FinOpsReview (YouTube)\n\n### Overview\nPromote our SOC2 and EU data residency story to finance operations leaders.\n\n### Messaging must-haves\n- **Claims:** only use approved stats from the fact sheet (v3).\n- **Disclosure:** #ad in first 2 lines + verbal disclosure in first 30s.\n\n### Deliverables\n- 1 integrated 8–10 min video + 2 short clips for LinkedIn reuse.\n- Publish window: Apr 20–May 5.\n\n### Don\'ts\n- No competitor disparagement; no guarantees about pricing or discounts.\n\n### KPIs\n- 150k qualified views, 1.5% CTR to landing page, 300 webinar signups attributed.',
    outZh:
      '## 合作简报 — 达人：FinOpsReview（YouTube）\n\n### 概述\n向财务运营负责人传递 SOC2 与欧盟数据驻留故事。\n\n### 必达信息\n- **数据：** 仅使用事实清单 v3 的批准口径。\n- **披露：** 正文前两句含 #ad，前 30 秒口头披露。\n\n### 交付\n- 1 条 8–10 分钟植入视频 + 2 条短视频供领英复用。\n- 发布窗口：4/20–5/5。\n\n### 禁止\n- 不贬低竞品；不承诺价格或折扣。\n\n### KPI\n- 15 万有效观看；落地页 CTR 1.5%；归因研讨会报名 300。',
  }),
  build({
    category: 'management/marketing-manager',
    slug: 'brand_guideline_update',
    mcp: 'mm_brand_guideline_update',
    name: 'Brand Guideline Update Memo',
    nameZh: '品牌规范更新备忘录',
    tags: ['brand', 'guidelines', 'marketing', 'design', 'messaging'],
    tagsZh: ['品牌', '规范', '营销', '设计', '信息'],
    personaEn:
      'You are a marketing manager who updates brand guidelines with rationale, examples, and rollout steps.',
    personaZh: '你是市场经理，能更新品牌规范：理由、示例与推广步骤。',
    objectiveEn:
      'From brand shifts (visual/voice), produce a guideline update memo for internal teams and agencies.',
    objectiveZh: '基于视觉/语气变化，撰写对内及对代理商的规范更新备忘录。',
    audienceEn: 'Design, PMM, and agency partners.',
    audienceZh: '设计、产品市场与代理商。',
    outputFormatEn: 'Markdown: what changed → why → examples → rollout → training.',
    outputFormatZh: 'Markdown：变更 → 原因 → 示例 → 推广 → 培训。',
    vars: [
      {
        name: 'changes',
        descriptionEn: 'What is changing',
        descriptionZh: '变更内容',
        exampleEn: 'New secondary palette; tighter product naming rules',
        exampleZh: '新增辅色；产品命名规则更严',
        required: true,
      },
      {
        name: 'rationale',
        descriptionEn: 'Customer research or strategy reason',
        descriptionZh: '客户研究或战略原因',
        exampleEn: 'Accessibility audit + enterprise trust research',
        exampleZh: '无障碍审计 + 企业信任研究',
        required: true,
      },
    ],
    userEn: 'Changes:\n{{changes}}\n\nRationale:\n{{rationale}}\n\nWrite memo.',
    userZh: '变更：\n{{changes}}\n\n原因：\n{{rationale}}\n\n请写备忘录。',
    descEn: 'Brand guideline change memo with rollout.',
    descZh: '品牌规范变更备忘录含推广。',
    outEn:
      '## Brand guideline update — April 2026\n\n### What changed\n- **Color:** introduce **Slate 700** as secondary text on light backgrounds (replaces Gray 600).\n- **Naming:** product names must include module suffix (+Pay, +Analytics) in first mention.\n\n### Why\n- Accessibility audit flagged contrast failures on marketing pages.\n- Enterprise buyers confused module boundaries in RFP responses.\n\n### Examples\n- ✅ "Acme Analytics+ helps finance teams..."\n- ❌ "Acme analytics helps..."\n\n### Rollout\n- Apr 10: update Figma libraries + web design tokens.\n- Apr 17: agency office hour + asset pack v14.\n\n### Training\n- 15-min Loom for sales + CS; quiz in LMS optional.',
    outZh:
      '## 品牌规范更新 — 2026 年 4 月\n\n### 变更\n- **色彩：** 浅色背景二级文字改用 **Slate 700**（替代 Gray 600）。\n- **命名：** 首次提及需含模块后缀（+Pay、+Analytics）。\n\n### 原因\n- 无障碍审计发现营销页对比度问题。\n- 企业买家在 RFP 中对模块边界困惑。\n\n### 示例\n- ✅ "Acme Analytics+ 帮助财务团队…"\n- ❌ "Acme analytics 帮助…"\n\n### 推广\n- 4/10：更新 Figma 库与 Web design tokens。\n- 4/17：代理商答疑 + 资产包 v14。\n\n### 培训\n- 销售与客服 15 分钟 Loom；LMS 测验可选。',
  }),
  build({
    category: 'management/marketing-manager',
    slug: 'event_marketing_plan',
    mcp: 'mm_event_marketing_plan',
    name: 'Event Marketing Plan',
    nameZh: '活动营销计划',
    tags: ['event', 'marketing', 'field', 'demand-gen', 'logistics'],
    tagsZh: ['活动', '营销', '线下', '获客', '后勤'],
    personaEn:
      'You are a marketing manager who plans field events with pre/during/post motions and clear ROI targets.',
    personaZh: '你是市场经理，能规划线下活动的前中后动作与清晰 ROI 目标。',
    objectiveEn:
      'From event goals, audience, and budget, produce an event marketing plan with timeline and metrics.',
    objectiveZh: '基于目标、受众与预算，输出活动营销计划：时间线与指标。',
    audienceEn: 'Sales and events team.',
    audienceZh: '销售与活动团队。',
    outputFormatEn: 'Markdown: goals → audience → pre/during/post → budget → KPIs.',
    outputFormatZh: 'Markdown：目标 → 受众 → 前中后 → 预算 → KPI。',
    vars: [
      {
        name: 'event',
        descriptionEn: 'Event type, city, date',
        descriptionZh: '活动类型、城市、日期',
        exampleEn: 'Executive dinner, London, May 22',
        exampleZh: '高管晚宴，伦敦，5/22',
        required: true,
      },
      {
        name: 'budget',
        descriptionEn: 'Budget and constraints',
        descriptionZh: '预算与约束',
        exampleEn: '$45k all-in; 40 guests max',
        exampleZh: '总计 4.5 万；最多 40 人',
        required: true,
      },
    ],
    userEn: 'Event:\n{{event}}\n\nBudget:\n{{budget}}\n\nDraft plan.',
    userZh: '活动：\n{{event}}\n\n预算：\n{{budget}}\n\n请写计划。',
    descEn: 'Field event plan with pipeline targets.',
    descZh: '含管道目标的线下活动计划。',
    outEn:
      '## Event marketing plan — London executive dinner (May 22)\n\n### Goals\n- Accelerate 6 enterprise opportunities in UKI; generate 25 qualified conversations.\n\n### Audience\n- CIO/CFO personas from target account list (Tier1 only).\n\n### Pre-event (T-21 to T-1)\n- SDR/BDR personalized invites with customer speaker hook.\n- Exec sponsor 1:1 outreach for top 12 accounts.\n\n### During\n- 20-min customer story + 10-min product vision + structured table topics.\n- Capture next-step cards; scan badges.\n\n### Post (T+3)\n- Thank-you + recap deck; schedule follow-ups within 48h.\n\n### Budget ($45k)\n- Venue/catering $28k; travel $8k; creative/gifts $6k; buffer $3k.\n\n### KPIs\n- 40 attendees; 18 SQLs; $2.5M influenced pipeline within 45 days.',
    outZh:
      '## 活动营销计划 — 伦敦高管晚宴（5/22）\n\n### 目标\n- 推动英国爱尔兰 6 个企业商机；产生 25 次有效对话。\n\n### 受众\n- 目标清单一级账户的 CIO/CFO。\n\n### 会前（T-21 至 T-1）\n- SDR/BDR 个性化邀请，突出客户演讲亮点。\n- 高管赞助人对前 12 账户 1:1 触达。\n\n### 会中\n- 20 分钟客户故事 + 10 分钟产品愿景 + 桌长话题。\n- 收集下一步卡片；扫描胸牌。\n\n### 会后（T+3）\n- 感谢信 + 纪要 deck；48 小时内安排跟进。\n\n### 预算（4.5 万）\n- 场地餐饮 2.8 万；差旅 0.8 万；物料礼品 0.6 万；缓冲 0.3 万。\n\n### KPI\n- 出席 40；SQL 18；45 天内影响管道 250 万。',
  }),
];
