'use strict';

/** C-Suite +10 and cross-functional +3 */
module.exports = (build) => [
  build({
    category: 'c-suite/cto',
    slug: 'tech_debt_prioritization',
    mcp: 'cto_tech_debt_prioritization',
    name: 'Tech Debt Prioritization',
    nameZh: '技术债优先级评估',
    tags: ['tech-debt', 'engineering', 'prioritization', 'risk', 'CTO'],
    tagsZh: ['技术债', '工程', '优先级', '风险', 'CTO'],
    personaEn: 'You are a CTO who prioritizes tech debt using risk, customer impact, and delivery drag.',
    personaZh: '你是 CTO，能按风险、客户影响与交付阻力为技术债排序。',
    objectiveEn: 'From inventory notes, produce a prioritized tech debt backlog with rationale and quarterly cuts.',
    objectiveZh: '基于清单记录，输出含理由与季度削减目标的排序技术债 backlog。',
    audienceEn: 'Engineering leadership and CFO.',
    audienceZh: '工程负责人与 CFO。',
    outputFormatEn: 'Markdown: principles → ranked themes → estimates → trade-offs → quarterly plan.',
    outputFormatZh: 'Markdown：原则 → 排序主题 → 估算 → 取舍 → 季度计划。',
    vars: [
      { name: 'inventory', descriptionEn: 'Debt items and symptoms', descriptionZh: '技术债项与症状', exampleEn: 'Flaky CI; monolith deploys; outdated auth lib', exampleZh: 'CI 不稳定；单体发布；认证库过期', required: true },
      { name: 'constraints', descriptionEn: 'Capacity constraints', descriptionZh: '产能约束', exampleEn: '20% eng capacity for debt per quarter', exampleZh: '每季度 20% 工程产能用于还债', required: false },
    ],
    userEn: 'Inventory:\n{{inventory}}\n\nConstraints:\n{{constraints}}\n\nPrioritize tech debt.',
    userZh: '清单：\n{{inventory}}\n\n约束：\n{{constraints}}\n\n请排序技术债。',
    descEn: 'Executive-ready tech debt prioritization.',
    descZh: '面向管理层的技债排序。',
    outEn: '## Tech debt prioritization — Q2 plan\n\n### Principles\n1. Customer-visible reliability first\n2. Reduce cycle time second\n3. Pay down compliance/security debt in parallel\n\n### Ranked themes\n| Theme | Why now | Est. eng-weeks |\n|-------|---------|----------------|\n| CI flakiness | Blocks merges; erodes quality culture | 4 |\n| Auth library EOL | Known CVE patch gap | 3 |\n| Deploy monolith coupling | Increases incident blast radius | 8 |\n\n### Trade-offs\n- Defer "nice refactor" of reporting module until NRR dashboard ships\n\n### Quarterly cut\nAllocate **20%** capacity: finish CI + auth in Q2; start deploy decoupling spike in Q3.',
    outZh: '## 技术债排序 — Q2 计划\n\n### 原则\n1. 客户可见可靠性优先\n2. 其次缩短交付周期\n3. 并行偿还合规/安全债\n\n### 排序主题\n| 主题 | 为何现在 | 估算人周 |\n|------|----------|----------|\n| CI 不稳定 | 阻塞合并；侵蚀质量文化 | 4 |\n| 认证库 EOL | 已知 CVE 补丁缺口 | 3 |\n| 单体发布耦合 | 扩大事故影响面 | 8 |\n\n### 取舍\n- 「报表模块美化重构」延到 NRR 看板发布之后\n\n### 季度削减\n拨 **20%** 产能：Q2 完成 CI+认证；Q3 启动发布解耦尖刺。',
  }),
  build({
    category: 'c-suite/cto',
    slug: 'build_vs_buy_analysis',
    mcp: 'cto_build_vs_buy_analysis',
    name: 'Build vs Buy Analysis',
    nameZh: '自研与采购分析',
    tags: ['build-vs-buy', 'vendor', 'architecture', 'CTO', 'strategy'],
    tagsZh: ['自研采购', '供应商', '架构', 'CTO', '战略'],
    personaEn: 'You are a CTO who compares build vs buy with TCO, time-to-value, and strategic control.',
    personaZh: '你是 CTO，能从 TCO、价值时间与战略控制力比较自研与采购。',
    objectiveEn: 'From capability need and vendor options, produce a build vs buy memo with recommendation.',
    objectiveZh: '基于能力需求与供应商选项，输出含建议的自研/采购备忘录。',
    audienceEn: 'CEO and finance.',
    audienceZh: 'CEO 与财务。',
    outputFormatEn: 'Markdown: requirement → options → TCO → risks → decision → next steps.',
    outputFormatZh: 'Markdown：需求 → 选项 → TCO → 风险 → 决策 → 下一步。',
    vars: [
      { name: 'need', descriptionEn: 'Capability needed', descriptionZh: '所需能力', exampleEn: 'Real-time anomaly detection on payments graph', exampleZh: '支付图上的实时异常检测', required: true },
      { name: 'vendors', descriptionEn: 'Vendor options', descriptionZh: '供应商选项', exampleEn: 'VendorA SaaS; VendorB managed service', exampleZh: 'A 家 SaaS；B 家托管', required: true },
    ],
    userEn: 'Need:\n{{need}}\n\nVendors:\n{{vendors}}\n\nAnalyze build vs buy.',
    userZh: '需求：\n{{need}}\n\n供应商：\n{{vendors}}\n\n请分析自研/采购。',
    descEn: 'Build vs buy decision memo.',
    descZh: '自研与采购决策备忘录。',
    outEn: '## Build vs buy — real-time fraud graph analytics\n\n### Requirement\nDetect anomalous payment subgraph patterns within 2s for rule enrichment.\n\n### Options\n1. **Buy:** VendorA SaaS graph scoring\n2. **Buy:** VendorB managed Flink + templates\n3. **Build:** Internal Flink + custom rules DSL\n\n### TCO (3-year, rough)\n- VendorA: lowest upfront, highest per-transaction fees at scale\n- VendorB: mid upfront, predictable monthly\n- Build: highest upfront, best unit economics at >X txn/day\n\n### Risks\n- Build: hiring + on-call burden\n- Buy: data residency + model transparency\n\n### Recommendation\n**VendorB managed** for 12 months to learn patterns, with contract clause allowing portable export; reassess build at month 9.\n\n### Next steps\nSecurity review + procurement RFP by May 1.',
    outZh: '## 自研/采购 — 实时欺诈图分析\n\n### 需求\n2 秒内检测支付子图异常模式以丰富规则。\n\n### 选项\n1. **采购：** A 家 SaaS 图评分\n2. **采购：** B 家托管 Flink + 模板\n3. **自研：** 内部 Flink + 自定义规则 DSL\n\n### TCO（3 年粗算）\n- A：前期最低，规模化后按笔费用最高\n- B：前期中等，月度可预测\n- 自研：前期最高，>X 笔/日单位经济最优\n\n### 风险\n- 自研：招聘+值班负担\n- 采购：数据驻留+模型可解释性\n\n### 建议\n先 **B 托管 12 个月**学习模式，合同含可迁移导出条款；第 9 个月复盘是否自研。\n\n### 下一步\n5/1 前完成安全评审与采购 RFP。',
  }),

  build({
    category: 'c-suite/cfo',
    slug: 'cash_flow_forecast_narrative',
    mcp: 'cfo_cash_flow_forecast_narrative',
    name: 'Cash Flow Forecast Narrative',
    nameZh: '现金流预测说明',
    tags: ['cash-flow', 'CFO', 'forecast', 'liquidity', 'finance'],
    tagsZh: ['现金流', 'CFO', '预测', '流动性', '财务'],
    personaEn: 'You are a CFO who explains cash movements with bridge logic and sensitivity cases.',
    personaZh: '你是 CFO，能用桥接逻辑与敏感性情景解释现金变动。',
    objectiveEn: 'From cash line items, produce a board-ready cash forecast narrative.',
    objectiveZh: '基于现金科目，输出面向董事会的现金流预测叙事。',
    audienceEn: 'Board and investors.',
    audienceZh: '董事会与投资人。',
    outputFormatEn: 'Markdown: bridge → drivers → sensitivities → covenant headroom.',
    outputFormatZh: 'Markdown：桥接 → 驱动 → 敏感性 → 契约余量。',
    vars: [
      { name: 'items', descriptionEn: 'Cash in/out items', descriptionZh: '现金流入流出项', exampleEn: 'ARR collections, payroll, cloud, tax, debt service', exampleZh: 'ARR 回款、薪酬、云、税、偿债', required: true },
      { name: 'horizon', descriptionEn: 'Forecast horizon', descriptionZh: '预测区间', exampleEn: 'Next 6 months', exampleZh: '未来 6 个月', required: true },
    ],
    userEn: 'Items:\n{{items}}\n\nHorizon:\n{{horizon}}\n\nWrite narrative.',
    userZh: '科目：\n{{items}}\n\n区间：\n{{horizon}}\n\n请写说明。',
    descEn: 'Cash forecast storyline for governance.',
    descZh: '面向治理的现金流叙事。',
    outEn: '## Cash flow forecast narrative — next 6 months\n\n### Bridge (high level)\nStarting cash **$42M** → projected **$36–$40M** range driven by timing of enterprise collections and annual bonus payouts.\n\n### Drivers\n- **Inflows:** stronger collections in April–May from enterprise renewals\n- **Outflows:** June bonus accrual payment + semi-annual cloud commit invoice\n\n### Sensitivities\n- **-10% collections slip** in May reduces ending cash by ~$2.2M\n- **FX (EUR/USD)** ±3% moves impact ~$0.6M on EU subsidiary balances\n\n### Covenant headroom\nNet leverage covenant remains comfortable under base and downside cases; monitor weekly if collections slip >5 days DSO.',
    outZh: '## 现金流预测说明 — 未来 6 个月\n\n### 桥接（摘要）\n期初现金 **4200 万** → 预计期末 **3600–4000 万**，受企业回款时点与年终奖支付影响。\n\n### 驱动\n- **流入：** 4–5 月企业续约回款较强\n- **流出：** 6 月奖金发放 + 半年云承诺账单\n\n### 敏感性\n- **5 月回款延迟 10%** 约减少期末现金 220 万\n- **欧元/美元 ±3%** 影响欧洲子公司余额约 60 万\n\n### 契约余量\n净杠杆契约在基准与下行情景均充裕；若 DSO 延迟 >5 天则改周监控。',
  }),
  build({
    category: 'c-suite/cfo',
    slug: 'fundraising_prep_memo',
    mcp: 'cfo_fundraising_prep_memo',
    name: 'Fundraising Preparation Memo',
    nameZh: '融资准备备忘录',
    tags: ['fundraising', 'CFO', 'investor', 'memo', 'strategy'],
    tagsZh: ['融资', 'CFO', '投资人', '备忘录', '战略'],
    personaEn: 'You are a CFO who prepares fundraising materials framing traction, efficiency, and capital plan.',
    personaZh: '你是 CFO，能准备融资材料：增长、效率与资金计划。',
    objectiveEn: 'From metrics and use of proceeds, draft an internal fundraising prep memo outline.',
    objectiveZh: '基于指标与资金用途，起草内部融资准备备忘录提纲。',
    audienceEn: 'CEO and board.',
    audienceZh: 'CEO 与董事会。',
    outputFormatEn: 'Markdown: story → metrics → milestones → use of proceeds → diligence pack list.',
    outputFormatZh: 'Markdown：故事 → 指标 → 里程碑 → 资金用途 → 尽调清单。',
    vars: [
      { name: 'metrics', descriptionEn: 'Key metrics', descriptionZh: '关键指标', exampleEn: 'ARR $32M; NRR 121%; burn multiple 1.3', exampleZh: 'ARR 3200 万；NRR 121%；burn multiple 1.3', required: true },
      { name: 'raise', descriptionEn: 'Target raise and timing', descriptionZh: '目标融资与时间', exampleEn: '$40M Series C in Q3', exampleZh: 'C 轮 4000 万，Q3', required: true },
    ],
    userEn: 'Metrics:\n{{metrics}}\n\nRaise:\n{{raise}}\n\nWrite prep memo outline.',
    userZh: '指标：\n{{metrics}}\n\n融资：\n{{raise}}\n\n请写准备备忘录提纲。',
    descEn: 'Internal fundraising prep outline.',
    descZh: '内部融资准备提纲。',
    outEn: '## Fundraising prep memo — Series C (outline)\n\n### Story\nWe are the default payout operations layer for mid-market finance teams in EU + UK, expanding to US with the same wedge.\n\n### Metrics snapshot\n- ARR $32M, growth 78% YoY, NRR 121%\n- Burn multiple 1.3; runway 28 months pre-raise\n\n### Milestones to prove (pre-close)\n- Launch US GA entity + 3 lighthouse logos\n- Ship Analytics+ module to 30% of base\n\n### Use of proceeds\n- 45% GTM US expansion\n- 35% R&D (reliability + compliance)\n- 20% balance sheet flexibility\n\n### Diligence pack checklist\n- Data room: financials, cap table, contracts, security docs\n- Customer reference list (8) + churn postmortems',
    outZh: '## 融资准备备忘录 — C 轮（提纲）\n\n### 故事\n我们是欧洲+英国中型财务团队的默认打款运营层，并以同一楔子扩张美国。\n\n### 指标快照\n- ARR 3200 万，同比 +78%，NRR 121%\n- Burn multiple 1.3；融资前跑道 28 个月\n\n### 交割前需证明的里程碑\n- 美国主体上线 + 3 个灯塔客户\n- Analytics+ 覆盖 30% 基盘\n\n### 资金用途\n- 45% 美国 GTM\n- 35% 研发（可靠性+合规）\n- 20% 资产负债表弹性\n\n### 尽调包清单\n- 数据室：财报、股本表、合同、安全材料\n- 客户引荐 8 + 流失复盘',
  }),

  build({
    category: 'c-suite/coo',
    slug: 'process_optimization_proposal',
    mcp: 'coo_process_optimization_proposal',
    name: 'Process Optimization Proposal (Executive)',
    nameZh: '流程优化提案（高管视角）',
    tags: ['process', 'COO', 'operations', 'efficiency', 'executive'],
    tagsZh: ['流程', 'COO', '运营', '效率', '高管'],
    personaEn: 'You are a COO who sponsors cross-functional process optimization with measurable KPIs.',
    personaZh: '你是 COO，能推动跨职能流程优化并绑定可衡量 KPI。',
    objectiveEn: 'From operational pain, produce an executive process optimization proposal with KPIs and owners.',
    objectiveZh: '基于运营痛点，输出高管流程优化提案：KPI 与负责人。',
    audienceEn: 'Executive team.',
    audienceZh: '高管团队。',
    outputFormatEn: 'Markdown: problem → target state → KPIs → program plan → investment.',
    outputFormatZh: 'Markdown：问题 → 目标态 → KPI → 项目计划 → 投入。',
    vars: [
      { name: 'pain', descriptionEn: 'Operational pain', descriptionZh: '运营痛点', exampleEn: 'Quote-to-cash cycle 38 days; handoffs between Sales-CS-Finance', exampleZh: '报价到回款 38 天；销售-CS-财务转手多', required: true },
    ],
    userEn: 'Pain:\n{{pain}}\n\nWrite executive proposal.',
    userZh: '痛点：\n{{pain}}\n\n请写高管提案。',
    descEn: 'COO-level process optimization proposal.',
    descZh: 'COO 视角流程优化提案。',
    outEn: '## Process optimization proposal — Quote-to-cash\n\n### Problem\nCycle time **38 days** (p75) due to sequential handoffs and unclear ownership between Sales, CS, and Finance.\n\n### Target state\n- Single **deal desk** workflow template in CRM\n- Automated billing triggers once delivery milestones verified\n\n### KPIs\n- p75 cycle **< 24 days** by Q4\n- Rework tickets **-30%**\n\n### Program plan (90 days)\n- Week 1–3: map current state + pain dollars\n- Week 4–8: pilot on mid-market segment\n- Week 9–12: scale + training\n\n### Investment\n- 0.5 FTE program manager + light tooling ($120k one-time)',
    outZh: '## 流程优化提案 — 报价到回款\n\n### 问题\n周期 **38 天（p75）**，因销售-CS-财务串行转手与责任不清。\n\n### 目标态\n- CRM 统一 **deal desk** 工作流模板\n- 交付里程碑确认后自动触发计费\n\n### KPI\n- Q4 前 p75 **<24 天**\n- 返工工单 **-30%**\n\n### 项目（90 天）\n- 第 1–3 周：现状图 + 损失估算\n- 第 4–8 周：中型市场试点\n- 第 9–12 周：推广 + 培训\n\n### 投入\n- 0.5 FTE 项目经理 + 轻量工具（一次性 12 万）',
  }),
  build({
    category: 'c-suite/coo',
    slug: 'cross_department_escalation',
    mcp: 'coo_cross_department_escalation',
    name: 'Cross-Department Escalation Playbook',
    nameZh: '跨部门升级手册',
    tags: ['escalation', 'COO', 'operations', 'alignment', 'executive'],
    tagsZh: ['升级', 'COO', '运营', '协同', '高管'],
    personaEn: 'You are a COO who defines cross-functional escalation paths to unblock revenue and delivery.',
    personaZh: '你是 COO，能定义跨职能升级路径以打通收入与交付。',
    objectiveEn: 'From recurring conflict themes, produce a cross-department escalation playbook.',
    objectiveZh: '基于跨部门反复出现的冲突主题，输出包含触发条件、升级路径与复盘节奏的跨部门升级手册。',
    audienceEn: 'VPs and department heads.',
    audienceZh: 'VP 与部门负责人。',
    outputFormatEn: 'Markdown: triggers → forums → SLAs → documentation → review cadence.',
    outputFormatZh: 'Markdown：触发 → 机制 → SLA → 文档 → 复盘节奏。',
    vars: [
      { name: 'themes', descriptionEn: 'Conflict themes', descriptionZh: '冲突主题', exampleEn: 'Pricing exceptions; SLA disputes; roadmap priority fights', exampleZh: '定价例外；SLA 争议；路线图优先级争执', required: true },
    ],
    userEn: 'Themes:\n{{themes}}\n\nWrite playbook.',
    userZh: '主题：\n{{themes}}\n\n请写手册。',
    descEn: 'Cross-dept escalation for exec alignment.',
    descZh: '跨部门升级以对齐高管。',
    outEn: '## Cross-department escalation playbook\n\n### Triggers\n- Revenue-impacting customer issue >48h unresolved\n- Repeated SLA misses between CS and Product\n- Pricing exceptions >15% discount without VP alignment\n\n### Forums\n- **Tier 1:** functional VPs sync (weekly)\n- **Tier 2:** COO bridge within 24h of trigger\n- **Tier 3:** CEO decision if cash/legal exposure > threshold\n\n### SLAs\n- Written decision + owners within **48h** of Tier 2 bridge\n\n### Documentation\n- Single-page decision log stored in Notion `exec-decisions`\n\n### Review cadence\n- Monthly retro: top 5 escalations + systemic fixes',
    outZh: '## 跨部门升级手册\n\n### 触发\n- >48 小时未解决且影响收入的客户问题\n- CS 与产品间重复 SLA 未达成\n- >15% 折扣定价例外未获 VP 对齐\n\n### 机制\n- **一级：** 职能 VP 周会\n- **二级：** 触发 24 小时内 COO 桥接\n- **三级：** 现金/法律敞口超阈值由 CEO 决策\n\n### SLA\n- **二级桥接后 48 小时**内书面决策+负责人\n\n### 文档\n- 单页决策记录存 Notion `exec-decisions`\n\n### 复盘\n- 月度：前 5 大升级 + 系统性修复',
  }),

  build({
    category: 'c-suite/cmo',
    slug: 'marketing_budget_allocation',
    mcp: 'cmo_marketing_budget_allocation',
    name: 'Marketing Budget Allocation Memo',
    nameZh: '营销预算分配备忘录',
    tags: ['budget', 'CMO', 'marketing', 'allocation', 'strategy'],
    tagsZh: ['预算', 'CMO', '营销', '分配', '战略'],
    personaEn: 'You are a CMO who allocates budget across funnel stages with experiments and guardrails.',
    personaZh: '你是 CMO，能在漏斗各阶段分配预算并保留实验与护栏。',
    objectiveEn: 'From goals and historical performance, draft a marketing budget allocation memo.',
    objectiveZh: '基于目标与历史表现，撰写营销预算分配备忘录。',
    audienceEn: 'CEO and finance.',
    audienceZh: 'CEO 与财务。',
    outputFormatEn: 'Markdown: goals → allocation table → experiments → efficiency metrics → risks.',
    outputFormatZh: 'Markdown：目标 → 分配表 → 实验 → 效率指标 → 风险。',
    vars: [
      { name: 'goals', descriptionEn: 'Pipeline or revenue goals', descriptionZh: '管道或收入目标', exampleEn: '$18M new ARR influenced marketing', exampleZh: '营销影响新增 ARR 1800 万', required: true },
      { name: 'budget', descriptionEn: 'Total budget', descriptionZh: '总预算', exampleEn: '$9.2M annual', exampleZh: '年度 920 万', required: true },
    ],
    userEn: 'Goals:\n{{goals}}\n\nBudget:\n{{budget}}\n\nWrite memo.',
    userZh: '目标：\n{{goals}}\n\n预算：\n{{budget}}\n\n请写备忘录。',
    descEn: 'Marketing budget allocation narrative.',
    descZh: '营销预算分配叙事。',
    outEn: '## Marketing budget allocation — FY26\n\n### Goals\nSupport **$18M** new ARR influenced by marketing with improved CAC payback.\n\n### Allocation\n| Category | % | Notes |\n|----------|---|-------|\n| Demand gen (paid + events) | 45% | EU expansion priority |\n| Product marketing & content | 20% | Launch Analytics+ |\n| Brand & PR | 15% | Trust + compliance narrative |\n| Ops & tools | 12% | Attribution + enrichment |\n| Experiments reserve | 8% | Controlled tests only |\n\n### Efficiency metrics\n- CAC payback **< 18 months** in SMB; **< 12** in MM where possible\n\n### Risks\n- Paid CPC inflation; mitigate with owned audience growth\n\n### Experiments reserve rules\n- Max 2 concurrent; kill criteria defined pre-launch',
    outZh: '## 营销预算分配 — FY26\n\n### 目标\n支撑营销影响的 **1800 万** 新增 ARR，并改善 CAC 回收期。\n\n### 分配\n| 科目 | 占比 | 说明 |\n|------|------|------|\n| 获客（付费+活动） | 45% | 欧洲扩张优先 |\n| 产品市场与内容 | 20% | Analytics+ 发布 |\n| 品牌与公关 | 15% | 信任与合规叙事 |\n| 运营与工具 | 12% | 归因与丰富化 |\n| 实验储备 | 8% | 仅控制实验 |\n\n### 效率指标\n- SMB CAC 回收 **<18 月**；MM 力争 **<12 月**\n\n### 风险\n- 付费 CPC 上涨；以自有受众增长对冲\n\n### 实验储备规则\n- 最多并行 2 个；预设止损标准',
  }),
  build({
    category: 'c-suite/cmo',
    slug: 'competitive_landscape_brief',
    mcp: 'cmo_competitive_landscape_brief',
    name: 'Competitive Landscape Brief',
    nameZh: '竞争格局简报',
    tags: ['competitive', 'CMO', 'positioning', 'market', 'strategy'],
    tagsZh: ['竞争', 'CMO', '定位', '市场', '战略'],
    personaEn: 'You are a CMO who frames competitive moves for executive decisions on messaging and spend.',
    personaZh: '你是 CMO，能把竞品动向框定为高管在信息与投放上的决策依据。',
    objectiveEn: 'From competitor signals, produce a competitive landscape brief with implications.',
    objectiveZh: '基于竞品信号与市场动态，输出面向高管的竞争格局简报、客户认知风险与应对策略建议。',
    audienceEn: 'Executive team and board.',
    audienceZh: '高管与董事会。',
    outputFormatEn: 'Markdown: market map → competitor moves → customer perception risks → plays.',
    outputFormatZh: 'Markdown：市场图 → 竞品动作 → 客户认知风险 → 对策。',
    vars: [
      { name: 'signals', descriptionEn: 'Competitor signals', descriptionZh: '竞品信号', exampleEn: 'CompX raised $200M; CompY launched free tier', exampleZh: 'X 融资 2 亿；Y 推出免费层', required: true },
    ],
    userEn: 'Signals:\n{{signals}}\n\nWrite brief.',
    userZh: '信号：\n{{signals}}\n\n请写简报。',
    descEn: 'Executive competitive landscape note.',
    descZh: '高管竞争格局备忘。',
    outEn: '## Competitive landscape brief — April 2026\n\n### Market map\n- **Incumbents:** broad suites with weaker workflow depth\n- **Point solutions:** fast UX, narrower integrations\n\n### Recent moves\n- **CompX:** $200M round → likely aggressive US enterprise marketing\n- **CompY:** free tier → may compress SMB pricing perceptions\n\n### Perception risks\n- Buyers may equate "free" with "good enough" for smaller teams\n\n### Plays\n- Double down on **compliance + auditability** proof in enterprise campaigns\n- Publish TCO study emphasizing hidden ops costs of free tiers\n- Accelerate customer evidence in UKI where CompX is weaker',
    outZh: '## 竞争格局简报 — 2026 年 4 月\n\n### 市场图\n- **套件巨头：** 广但工作流深度弱\n- **单点方案：** 体验快但集成窄\n\n### 近期动作\n- **X：** 融资 2 亿 → 可能加码美国企业营销\n- **Y：** 免费层 → 可能压低 SMB 价格认知\n\n### 认知风险\n- 买家或认为「免费」对小团队「够用」\n\n### 对策\n- 企业战役强化 **合规与可审计** 证据\n- 发布 TCO 研究揭示免费层隐性运营成本\n- 加强 UKI 客户证据（X 较弱）',
  }),

  build({
    category: 'c-suite/chro',
    slug: 'dei_program_review',
    mcp: 'chro_dei_program_review',
    name: 'DEI Program Review Brief',
    nameZh: '多元包容项目复盘简报',
    tags: ['DEI', 'CHRO', 'culture', 'HR', 'program'],
    tagsZh: ['多元包容', 'CHRO', '文化', '人力', '项目'],
    personaEn: 'You are a CHRO who reviews DEI programs with outcomes, gaps, and governance.',
    personaZh: '你是 CHRO，能复盘 DEI 项目：成果、差距与治理。',
    objectiveEn: 'From program data and goals, produce a DEI program review for leadership.',
    objectiveZh: '基于项目数据与目标，输出供领导层审阅的 DEI 复盘。',
    audienceEn: 'CEO and board committee.',
    audienceZh: 'CEO 与董事会委员会。',
    outputFormatEn: 'Markdown: objectives → metrics → highlights → gaps → actions → legal caution.',
    outputFormatZh: 'Markdown：目标 → 指标 → 亮点 → 差距 → 行动 → 法律提示。',
    vars: [
      { name: 'data', descriptionEn: 'Program data', descriptionZh: '项目数据', exampleEn: 'Hiring funnel diversity; promotion rates; survey themes', exampleZh: '招聘漏斗多样性；晋升率；调研主题', required: true },
    ],
    userEn: 'Data:\n{{data}}\n\nWrite DEI review.',
    userZh: '数据：\n{{data}}\n\n请写 DEI 复盘。',
    descEn: 'DEI program review for executives.',
    descZh: '面向高管的 DEI 项目复盘。',
    systemExtraEn: '\n- Keep compliant with local employment laws; avoid discriminatory quotas',
    systemExtraZh: '\n- 遵守各地雇佣法律；避免歧视性配额表述',
    outEn: '## DEI program review — FY25–FY26 YTD\n\n### Objectives\nImprove representation in engineering leadership pipelines and inclusive team norms.\n\n### Metrics\n- **Hiring:** URG representation in eng interviews +6 pts YoY\n- **Promotions:** IC→mgr promotion parity index improved 0.08\n- **Culture:** inclusion score +4 pts in annual survey\n\n### Highlights\n- Sponsorship program paired 42 high-potential ICs with directors\n\n### Gaps\n- Attrition slightly elevated for mid-level URG engineers in two hubs\n- Manager training completion at 78% (target 90%)\n\n### Actions\n- Hub-specific listening sessions + retention playbooks\n- Mandate manager training completion by Q3 with exec nudges\n\n### Legal caution\nPrograms must comply with jurisdiction-specific rules; legal review for any targets language.',
    outZh: '## DEI 项目复盘 — FY25 至 FY26 年初\n\n### 目标\n提升工程领导梯队代表性并强化包容团队规范。\n\n### 指标\n- **招聘：** 工程面试中 URG 代表性同比 +6 点\n- **晋升：** IC→经理公平指数 +0.08\n- **文化：** 年度调研包容分 +4\n\n### 亮点\n- 赞助计划为 42 名高潜 IC 配对总监导师\n\n### 差距\n- 两地枢纽中级 URG 工程师流失略高\n- 经理培训完成率 78%（目标 90%）\n\n### 行动\n- 分枢纽倾听会 + 留存手册\n- Q3 前强制完成经理培训（高管督促）\n\n### 法律提示\n项目需符合各地法规；涉及目标表述需法务复核',
  }),
  build({
    category: 'c-suite/chro',
    slug: 'succession_planning_memo',
    mcp: 'chro_succession_planning_memo',
    name: 'Succession Planning Memo',
    nameZh: '继任计划备忘录',
    tags: ['succession', 'CHRO', 'talent', 'leadership', 'risk'],
    tagsZh: ['继任', 'CHRO', '人才', '领导', '风险'],
    personaEn: 'You are a CHRO who documents succession depth for critical roles with timelines and development plans.',
    personaZh: '你是 CHRO，能记录关键岗位的继任深度、时间线与培养计划。',
    objectiveEn: 'From critical roles list, produce a succession planning memo outline.',
    objectiveZh: '基于关键岗位清单，输出继任计划备忘录提纲。',
    audienceEn: 'CEO and board.',
    audienceZh: 'CEO 与董事会。',
    outputFormatEn: 'Markdown: critical roles → readiness → risks → development actions → confidentiality.',
    outputFormatZh: 'Markdown：关键岗位 → 准备度 → 风险 → 培养行动 → 保密。',
    vars: [
      { name: 'roles', descriptionEn: 'Critical roles', descriptionZh: '关键岗位', exampleEn: 'CFO, VP Sales, VP Eng', exampleZh: 'CFO、销售 VP、工程 VP', required: true },
    ],
    userEn: 'Roles:\n{{roles}}\n\nWrite succession memo outline.',
    userZh: '岗位：\n{{roles}}\n\n请写继任备忘录提纲。',
    descEn: 'Succession planning outline for governance.',
    descZh: '面向治理的继任计划提纲。',
    outEn: '## Succession planning memo (outline)\n\n### Critical roles\n- CFO, VP Sales, VP Engineering\n\n### Readiness matrix\n| Role | Incumbent risk | Ready-now | Ready-12m | External needed? |\n|------|----------------|-----------|-----------|------------------|\n| CFO | Low | n/a | FP&A Director | backup search |\n| VP Sales | Med (travel health) | RSD EMEA | RSD NA | yes |\n| VP Eng | Low | Eng Dir Platform | Eng Dir Product | no |\n\n### Risks\n- VP Sales has single-threaded relationships in top 10 accounts\n\n### Development actions\n- Stretch assignment: NA RSD leads global forecasting pilot\n- Executive coaching for director bench\n\n### Confidentiality\nDistribution limited to CEO + board comp committee; avoid employee identifiers in shared decks.',
    outZh: '## 继任计划备忘录（提纲）\n\n### 关键岗位\n- CFO、销售 VP、工程 VP\n\n### 准备度矩阵\n| 岗位 | 在位者风险 | 立即可替 | 12 月可替 | 需外部？ |\n|------|------------|----------|-----------|----------|\n| CFO | 低 | 无 | FP&A 总监 | 备选寻访 |\n| 销售 VP | 中（健康） | 欧非 RSD | 北美 RSD | 是 |\n| 工程 VP | 低 | 平台工程总监 | 产品工程总监 | 否 |\n\n### 风险\n- 销售 VP 与前十大客户关系单线\n\n### 培养\n- 北美 RSD 牵头全球预测试点（拉伸任务）\n- 总监梯队高管教练\n\n### 保密\n仅限 CEO + 薪酬委员会；共享材料避免可识别员工信息',
  }),

  build({
    category: 'cross-functional',
    slug: 'stakeholder_update',
    mcp: 'xf_stakeholder_update',
    name: 'Stakeholder Communication Plan',
    nameZh: '干系人沟通计划',
    tags: ['stakeholders', 'communication', 'project', 'alignment', 'status'],
    tagsZh: ['干系人', '沟通', '项目', '对齐', '状态'],
    personaEn: 'You are a program lead who plans stakeholder updates with cadence, channel, and message by audience.',
    personaZh: '你是项目负责人，能按受众制定节奏、渠道与信息的沟通计划。',
    objectiveEn: 'From project context, produce a stakeholder communication plan.',
    objectiveZh: '基于项目背景与关键里程碑，输出分受众、分渠道、分节奏的干系人沟通计划与升级机制。',
    audienceEn: 'Project team and sponsors.',
    audienceZh: '项目组与赞助人。',
    outputFormatEn: 'Markdown: audiences → cadence → channels → message pillars → escalation.',
    outputFormatZh: 'Markdown：受众 → 节奏 → 渠道 → 信息支柱 → 升级。',
    vars: [
      { name: 'project', descriptionEn: 'Project name and phase', descriptionZh: '项目名与阶段', exampleEn: 'Global payroll rollout — build phase', exampleZh: '全球薪酬上线 — 建设阶段', required: true },
      { name: 'stakeholders', descriptionEn: 'Stakeholder groups', descriptionZh: '干系人群体', exampleEn: 'Exec sponsors, HRBPs, IT, finance controllers', exampleZh: '高管赞助人、HRBP、IT、财务控制员', required: true },
    ],
    userEn: 'Project:\n{{project}}\n\nStakeholders:\n{{stakeholders}}\n\nWrite communication plan.',
    userZh: '项目：\n{{project}}\n\n干系人：\n{{stakeholders}}\n\n请写沟通计划。',
    descEn: 'Stakeholder comms cadence for programs.',
    descZh: '项目的干系人沟通节奏。',
    outEn: '## Stakeholder communication plan — Global payroll rollout\n\n### Audiences\n- **Exec sponsors:** risk, timeline, budget variance\n- **HRBPs:** local impacts, training, FAQs\n- **IT:** integrations, cutover windows, rollback\n- **Finance:** reconciliation, reporting cutover\n\n### Cadence\n- Exec: biweekly 15-min written update + monthly live review\n- HRBPs: weekly office hours during UAT\n- IT: daily standup during cutover week\n\n### Channels\n- Email summary + Slack #payroll-rollout + wiki hub\n\n### Message pillars\n- "No surprises" on dates; single source of truth links\n\n### Escalation\n- Issues >$250k impact or >1 week slip go to program steering within 24h',
    outZh: '## 干系人沟通计划 — 全球薪酬上线\n\n### 受众\n- **高管赞助人：** 风险、时间线、预算偏差\n- **HRBP：** 本地影响、培训、FAQ\n- **IT：** 集成、切换窗口、回滚\n- **财务：** 对账、报表切换\n\n### 节奏\n- 高管：双周 15 分钟书面 + 月度现场复盘\n- HRBP：UAT 期间每周答疑\n- IT：切换周每日站会\n\n### 渠道\n- 邮件摘要 + Slack #payroll-rollout + wiki 枢纽\n\n### 信息支柱\n- 日期「零意外」；单一事实来源链接\n\n### 升级\n- 影响 >25 万或滑点 >1 周的问题 24 小时内上报指导委员会',
  }),
  build({
    category: 'cross-functional',
    slug: 'project_kickoff',
    mcp: 'xf_project_kickoff',
    name: 'Project Kickoff Document',
    nameZh: '项目启动文档',
    tags: ['kickoff', 'project', 'charter', 'scope', 'cross-functional'],
    tagsZh: ['启动', '项目', '章程', '范围', '跨职能'],
    personaEn: 'You are a PM who kickoffs projects with charter, scope, RACI, and success metrics.',
    personaZh: '你是项目经理，能用章程、范围、RACI 与成功指标做项目启动。',
    objectiveEn: 'From initiative description, produce a kickoff document for cross-functional teams.',
    objectiveZh: '基于倡议描述，输出跨职能团队用的启动文档。',
    audienceEn: 'Core team and sponsors.',
    audienceZh: '核心团队与赞助人。',
    outputFormatEn: 'Markdown: charter → scope in/out → milestones → RACI → risks → comms.',
    outputFormatZh: 'Markdown：章程 → 范围内外 → 里程碑 → RACI → 风险 → 沟通。',
    vars: [
      { name: 'initiative', descriptionEn: 'Initiative summary', descriptionZh: '倡议摘要', exampleEn: 'Consolidate three CRM instances into one', exampleZh: '将三个 CRM 实例合并为一个', required: true },
      { name: 'timeline', descriptionEn: 'Target timeline', descriptionZh: '目标时间线', exampleEn: '9 months', exampleZh: '9 个月', required: true },
    ],
    userEn: 'Initiative:\n{{initiative}}\n\nTimeline:\n{{timeline}}\n\nWrite kickoff doc.',
    userZh: '倡议：\n{{initiative}}\n\n时间线：\n{{timeline}}\n\n请写启动文档。',
    descEn: 'Cross-functional project kickoff charter.',
    descZh: '跨职能项目启动章程。',
    outEn: '## Project kickoff — CRM consolidation\n\n### Charter\nReduce operational drag and reporting inconsistency by consolidating three regional CRM instances into a single global instance with standardized pipelines.\n\n### Scope\n**In:** data migration, integration rewiring, training, cutover\n**Out:** CPQ redesign (separate initiative)\n\n### Milestones\n- M1: inventory + dedupe rules (Week 6)\n- M2: UAT with 5 pilot regions (Week 20)\n- M3: global cutover (Week 34)\n\n### RACI (snippet)\n- **Migration lead:** R for data mapping; IT infra: C; Sales ops: A for pipeline definitions\n\n### Risks\n- Data quality surprises; mitigate with early profiling jobs\n\n### Success metrics\n- Single source reporting for pipeline by Q4; support tickets -25% post-cutover\n\n### Comms\nWeekly status note to sponsors; wiki as hub',
    outZh: '## 项目启动 — CRM 合并\n\n### 章程\n将三个区域 CRM 合并为单一全球实例并标准化管道，降低运营摩擦与报表不一致。\n\n### 范围\n**包含：** 数据迁移、集成改造、培训、切换\n**不包含：** CPQ 重设计（独立项目）\n\n### 里程碑\n- M1：盘点+去重规则（第 6 周）\n- M2：5 个试点区域 UAT（第 20 周）\n- M3：全球切换（第 34 周）\n\n### RACI（摘录）\n- **迁移负责人：** 数据映射 R；IT 基建 C；销售运营对管道定义 A\n\n### 风险\n- 数据质量意外；早期剖析任务缓解\n\n### 成功指标\n- Q4 前管道单一事实来源；切换后支持工单 -25%\n\n### 沟通\n赞助人周度纪要；wiki 为枢纽',
  }),
  build({
    category: 'cross-functional',
    slug: 'knowledge_transfer',
    mcp: 'xf_knowledge_transfer',
    name: 'Knowledge Transfer Document',
    nameZh: '知识转移文档',
    tags: ['knowledge-transfer', 'documentation', 'handover', 'continuity', 'team'],
    tagsZh: ['知识转移', '文档', '交接', '连续性', '团队'],
    personaEn: 'You are a team lead who documents knowledge transfer for role transitions with systems, rituals, and contacts.',
    personaZh: '你是团队负责人，能记录岗位交接所需的系统、例行与联系人。',
    objectiveEn: 'From departing context, produce a knowledge transfer outline covering systems, processes, and risks.',
    objectiveZh: '基于离任/交接背景，输出覆盖系统、流程与风险的知识转移提纲。',
    audienceEn: 'Incoming owner and manager.',
    audienceZh: '接手人与经理。',
    outputFormatEn: 'Markdown: overview → systems → recurring processes → stakeholders → risks → 30-day plan.',
    outputFormatZh: 'Markdown：概述 → 系统 → 例行流程 → 干系人 → 风险 → 30 天计划。',
    vars: [
      { name: 'role', descriptionEn: 'Role and responsibilities', descriptionZh: '角色与职责', exampleEn: 'Primary on-call for billing platform', exampleZh: '计费平台主值班', required: true },
      { name: 'systems', descriptionEn: 'Systems owned', descriptionZh: '负责系统', exampleEn: 'Stripe webhooks service, ledger exporter, Grafana dashboards', exampleZh: 'Stripe webhook、账本导出、Grafana 面板', required: true },
    ],
    userEn: 'Role:\n{{role}}\n\nSystems:\n{{systems}}\n\nWrite KT outline.',
    userZh: '角色：\n{{role}}\n\n系统：\n{{systems}}\n\n请写知识转移提纲。',
    descEn: 'Knowledge transfer checklist for continuity.',
    descZh: '保障连续性的知识转移清单。',
    outEn: '## Knowledge transfer — Billing platform primary (outline)\n\n### Overview\nOwns reliability of webhook ingestion, nightly ledger exports, and billing incident response.\n\n### Systems\n- `webhooks-svc` (k8s), Postgres `billing` schema, S3 export buckets, Grafana dash `BILLING-SLO`\n\n### Recurring processes\n- Weekly dependency updates (Tues)\n- Monthly key rotation rehearsal with security\n- Quarterly disaster recovery test for exports\n\n### Key stakeholders\n- Finance controller (Ana), PSP partner manager (Li), Security (SOC)\n\n### Risks / gotchas\n- Daylight saving impacts batch windows; DST runbook RB-BILL-03\n\n### 30-day plan\n- Week 1: shadow incidents + read runbooks\n- Week 2: lead minor deploy with buddy\n- Week 3: own weekly update email to finance\n- Week 4: solo on-call with escalation safety net',
    outZh: '## 知识转移 — 计费平台主值班（提纲）\n\n### 概述\n负责 webhook 摄入可靠性、夜间账本导出与计费事故响应。\n\n### 系统\n- `webhooks-svc`（k8s）、Postgres `billing`、S3 导出桶、Grafana `BILLING-SLO`\n\n### 例行\n- 每周二依赖更新\n- 每月与安全演练密钥轮换\n- 每季度导出灾备演练\n\n### 关键干系人\n- 财务控制员 Ana、PSP 伙伴经理 Li、安全 SOC\n\n### 风险/坑\n- 夏令时影响批处理窗口；见 RB-BILL-03\n\n### 30 天计划\n- 第 1 周：跟事故 + 读手册\n- 第 2 周：在伙伴陪同下主导小发布\n- 第 3 周：独立发财务周更邮件\n- 第 4 周：单独值班 + 升级安全网',
  }),
];
