'use strict';

/** marketing, sales-rep, customer-success, legal — 16 skills */
module.exports = (build) => [
  build({
    category: 'individual-contributor/marketing',
    slug: 'social_media_post_series',
    mcp: 'mkt_social_media_post_series',
    name: 'Social Media Post Series',
    nameZh: '社交媒体系列帖',
    tags: ['social-media', 'marketing', 'content', 'campaign', 'B2B'],
    tagsZh: ['社交媒体', '营销', '内容', '战役', 'B2B'],
    personaEn: 'You are a B2B marketer who writes crisp social posts with hooks, proof, and compliant claims.',
    personaZh: '你是 B2B 营销，能写有钩子、证据且合规的社交帖。',
    objectiveEn: 'From campaign angle and proof points, draft a 5-post LinkedIn series with CTAs.',
    objectiveZh: '基于战役角度与证据点，撰写 5 条领英系列帖含 CTA。',
    audienceEn: 'Demand gen and brand.',
    audienceZh: '获客与品牌。',
    outputFormatEn: 'Markdown: series outline → posts → hashtags → compliance notes.',
    outputFormatZh: 'Markdown：系列提纲 → 帖子 → 话题 → 合规备注。',
    vars: [
      { name: 'angle', descriptionEn: 'Campaign angle', descriptionZh: '战役角度', exampleEn: 'Why finance teams ditch spreadsheets for payouts', exampleZh: '财务团队为何用平台替代表格做打款', required: true },
      { name: 'proof', descriptionEn: 'Stats or customer quotes', descriptionZh: '数据或客户金句', exampleEn: 'SOC2; 40% faster close; "cut manual work 12h/wk"', exampleZh: 'SOC2；关账快 40%；「每周少 12 小时手工」', required: true },
    ],
    userEn: 'Angle:\n{{angle}}\n\nProof:\n{{proof}}\n\nWrite 5 posts.',
    userZh: '角度：\n{{angle}}\n\n证据：\n{{proof}}\n\n请写 5 条帖子。',
    descEn: 'LinkedIn-ready post series.',
    descZh: '可直接发布的领英系列。',
    outEn: '## 5-post LinkedIn series — Payout automation\n\n### Post 1 (hook)\nSpreadsheet payouts don\'t fail loudly—they fail slowly. Here\'s what we see in mid-market finance teams 👇\n\n### Post 2 (pain)\n3 silent risks: broken audit trails, FX rounding drift, and "who approved this?" moments during month-end.\n\n### Post 3 (proof)\nTeams on modern payout ops report fewer escalations and faster closes—one customer cut manual work ~12h/week (internal survey, n=42).\n\n### Post 4 (how we help)\nAutomated approvals + immutable logs + role-based exports—without ripping out your bank relationships.\n\n### Post 5 (CTA)\nIf you\'re reviewing payout ops this quarter, comment "checklist" and I\'ll send a 1-page readiness list. #fintech #financeops',
    outZh: '## 5 条领英系列 — 打款自动化\n\n### 帖 1（钩子）\n表格打款不会"巨响式"失败——而是慢慢失稳。看看中型财务团队常见情况 👇\n\n### 帖 2（痛点）\n三个静默风险：审计链断裂、汇兑舍入漂移、关账时"谁批的？"。\n\n### 帖 3（证据）\n现代化打款运营团队升级更少、关账更快——某调研 n=42，客户每周少约 12 小时手工（内部问卷）。\n\n### 帖 4（价值）\n自动审批 + 不可篡改日志 + 基于角色的导出——无需换掉银行关系。\n\n### 帖 5（CTA）\n若本季度要评估打款运营，评论「清单」领取 1 页准备清单。#fintech #financeops',
  }),
  build({
    category: 'individual-contributor/marketing',
    slug: 'email_nurture_sequence',
    mcp: 'mkt_email_nurture_sequence',
    name: 'Email Nurture Sequence',
    nameZh: '邮件培育序列',
    tags: ['email', 'nurture', 'marketing', 'demand-gen', 'copy'],
    tagsZh: ['邮件', '培育', '营销', '获客', '文案'],
    personaEn: 'You are a lifecycle marketer who writes nurture emails with one CTA per email and strong subject lines.',
    personaZh: '你是生命周期营销，能写一封一个 CTA、主题行清晰的培育邮件。',
    objectiveEn: 'From ICP and offer, draft a 4-email nurture sequence with subjects and body copy.',
    objectiveZh: '基于 ICP 与卖点，撰写 4 封培育邮件含主题与正文。',
    audienceEn: 'Marketing ops.',
    audienceZh: '营销运营。',
    outputFormatEn: 'Markdown: goals → emails (subject, preview, body) → metrics.',
    outputFormatZh: 'Markdown：目标 → 邮件（主题、预览、正文）→ 指标。',
    vars: [
      { name: 'icp', descriptionEn: 'ICP', descriptionZh: '理想客户', exampleEn: 'Finance ops leaders at 200–2000 employees', exampleZh: '200–2000 人公司的财务运营负责人', required: true },
      { name: 'offer', descriptionEn: 'Offer / CTA', descriptionZh: '卖点/CTA', exampleEn: 'Webinar + ROI worksheet', exampleZh: '网络研讨会 + ROI 表', required: true },
    ],
    userEn: 'ICP:\n{{icp}}\n\nOffer:\n{{offer}}\n\nWrite sequence.',
    userZh: 'ICP：\n{{icp}}\n\n卖点：\n{{offer}}\n\n请写序列。',
    descEn: 'Short nurture sequence for MQL progression.',
    descZh: '推动 MQL 的短培育序列。',
    outEn: '## 4-email nurture — ROI webinar\n\n### Email 1\n- **Subject:** Your month-end close has a hidden tax (time)\n- **Preview:** 3 questions finance teams ask before switching payout tools\n- **Body:** Short story + link to webinar\n\n### Email 2\n- **Subject:** The spreadsheet → platform checklist\n- **Body:** Bulleted checklist + CTA worksheet download\n\n### Email 3\n- **Subject:** What changes in week 1 (implementation)\n- **Body:** Timeline graphic + FAQ\n\n### Email 4\n- **Subject:** Last seats — webinar tomorrow\n- **Body:** Urgency + social proof snippet\n\n### Metrics\nTarget 35% open, 6% CTR, 12% webinar reg from clickers',
    outZh: '## 4 封培育 — ROI 研讨会\n\n### 邮件 1\n- **主题：** 关账的隐性成本是时间\n- **预览：** 换打款工具前财务常问的 3 个问题\n- **正文：** 小故事 + 研讨会链接\n\n### 邮件 2\n- **主题：** 从表格到平台的检查清单\n- **正文：** 要点清单 + 下载 ROI 表 CTA\n\n### 邮件 3\n- **主题：** 上线第 1 周会发生什么\n- **正文：** 时间线 + FAQ\n\n### 邮件 4\n- **主题：** 最后名额 — 明天开会\n- **正文：** 紧迫 + 社会证明片段\n\n### 指标\n目标打开 35%、CTR 6%、点击者中 12% 报名研讨会',
  }),
  build({
    category: 'individual-contributor/marketing',
    slug: 'seo_content_brief',
    mcp: 'mkt_seo_content_brief',
    name: 'SEO Content Brief',
    nameZh: 'SEO 内容简报',
    tags: ['SEO', 'content', 'marketing', 'keywords', 'brief'],
    tagsZh: ['SEO', '内容', '营销', '关键词', '简报'],
    personaEn: 'You are an SEO-focused marketer who writes briefs with intent, outlines, and internal link plans.',
    personaZh: '你是 SEO 向营销，能写含意图、提纲与内链计划的简报。',
    objectiveEn: 'From target keyword and audience, produce an SEO brief with H1/H2 outline and SERP notes.',
    objectiveZh: '基于目标词与受众，输出含 H1/H2 提纲与 SERP 备注的 SEO 简报。',
    audienceEn: 'Writers and editors.',
    audienceZh: '作者与编辑。',
    outputFormatEn: 'Markdown: intent → outline → FAQs → links → on-page checklist.',
    outputFormatZh: 'Markdown：意图 → 提纲 → FAQ → 链接 → 页面清单。',
    vars: [
      { name: 'keyword', descriptionEn: 'Primary keyword', descriptionZh: '主关键词', exampleEn: 'payout automation software', exampleZh: '打款自动化软件', required: true },
      { name: 'audience', descriptionEn: 'Reader persona', descriptionZh: '读者画像', exampleEn: 'CFO staff evaluating vendors', exampleZh: '评估供应商的 CFO 团队', required: true },
    ],
    userEn: 'Keyword:\n{{keyword}}\n\nAudience:\n{{audience}}\n\nWrite SEO brief.',
    userZh: '关键词：\n{{keyword}}\n\n受众：\n{{audience}}\n\n请写 SEO 简报。',
    descEn: 'Writer-ready SEO brief.',
    descZh: '可直接写作的 SEO 简报。',
    outEn: '## SEO brief — "payout automation software"\n\n### Intent\nCommercial investigation: compare solutions, understand features, de-risk procurement.\n\n### Outline\n- H1: Best payout automation software for finance teams (2026 guide)\n- H2: What payout automation actually automates\n- H2: Key features checklist (approvals, audit logs, bank coverage)\n- H2: Implementation timeline (30/60/90)\n- H2: Pricing models you\'ll see\n- H2: FAQs\n\n### FAQs\n- How is this different from AP automation?\n- What integrations matter for NetSuite?\n\n### Internal links\n- Link to /security/soc2 and /product/payouts\n\n### On-page checklist\n- Meta title <60 chars; schema FAQ; 2 original diagrams',
    outZh: '## SEO 简报 — 「打款自动化软件」\n\n### 意图\n商业调研：比较方案、理解功能、降低采购风险。\n\n### 提纲\n- H1：财务团队的打款自动化软件指南（2026）\n- H2：打款自动化到底自动化了什么\n- H2：功能清单（审批、审计日志、银行覆盖）\n- H2：实施时间线（30/60/90）\n- H2：常见定价模式\n- H2：FAQ\n\n### FAQ\n- 与应付自动化有何不同？\n- NetSuite 对接哪些集成最关键？\n\n### 内链\n- 链到 /security/soc2 与 /product/payouts\n\n### 页面清单\n- Title <60 字；FAQ 结构化数据；2 张原创图',
  }),
  build({
    category: 'individual-contributor/marketing',
    slug: 'case_study_writing',
    mcp: 'mkt_case_study_writing',
    name: 'Case Study Writing',
    nameZh: '客户案例撰写',
    tags: ['case-study', 'marketing', 'storytelling', 'B2B', 'proof'],
    tagsZh: ['案例', '营销', '叙事', 'B2B', '证据'],
    personaEn: 'You are a B2B marketer who writes case studies with quantified outcomes and ethical attribution.',
    personaZh: '你是 B2B 营销，能写量化成果且归属合规的客户案例。',
    objectiveEn: 'From customer situation, solution, and metrics, draft a 800–1200 word case study structure.',
    objectiveZh: '基于客户情境、方案与指标，起草 800–1200 词案例结构。',
    audienceEn: 'Sales and website.',
    audienceZh: '销售与官网。',
    outputFormatEn: 'Markdown: headline → summary → challenge → solution → results → quotes → CTA.',
    outputFormatZh: 'Markdown：标题 → 摘要 → 挑战 → 方案 → 结果 → 引语 → CTA。',
    vars: [
      { name: 'customer', descriptionEn: 'Customer profile (anonymized ok)', descriptionZh: '客户画像（可匿名）', exampleEn: 'EU fintech, 600 employees', exampleZh: '欧洲金融科技，600 人', required: true },
      { name: 'metrics', descriptionEn: 'Quantified results', descriptionZh: '量化结果', exampleEn: 'Close time -18%; manual hours -12h/wk', exampleZh: '关账时间 -18%；每周手工 -12 小时', required: true },
    ],
    userEn: 'Customer:\n{{customer}}\n\nMetrics:\n{{metrics}}\n\nWrite case study.',
    userZh: '客户：\n{{customer}}\n\n指标：\n{{metrics}}\n\n请写案例。',
    descEn: 'Case study narrative with proof.',
    descZh: '含证据的案例叙事。',
    outEn: '## Case study: How FinEuro cut month-end close time by 18%\n\n### At a glance\nEU fintech, 600 employees; replaced spreadsheet payout ops with automated approvals and audit-ready exports.\n\n### Challenge\n- Fragmented bank files and manual reconciliations stretched close to 9 days.\n- Audit prep required hunting through email approvals.\n\n### Solution\n- Centralized payout workflows with RBAC and immutable logs.\n- ERP-mapped exports reduced rework for finance controllers.\n\n### Results (6 months)\n- Close calendar time: **-18%**\n- Manual weekly hours: **-12h** (self-reported survey, n=9)\n- Audit findings related to payout approvals: **0**\n\n### Quote\n"We finally have one place to answer who approved what—and when." — Controller\n\n### CTA\nSee the payout automation checklist for finance teams.',
    outZh: '## 案例：FinEuro 如何将关账周期缩短 18%\n\n### 一览\n欧洲金融科技 600 人；用自动审批与可审计导出替代表格打款运营。\n\n### 挑战\n- 银行文件分散、手工对账拉长关账至 9 天。\n- 审计准备需在邮件里找审批痕迹。\n\n### 方案\n- 集中打款工作流 + RBAC + 不可篡改日志。\n- 映射 ERP 的导出减少控制员返工。\n\n### 结果（6 个月）\n- 关账日历时间：**-18%**\n- 每周手工时长：**-12 小时**（自报问卷 n=9）\n- 与打款审批相关的审计发现：**0**\n\n### 引语\n「我们终于能回答谁、在何时、批了什么。」—— 财务控制员\n\n### CTA\n获取财务团队的打款自动化清单。',
  }),

  build({
    category: 'individual-contributor/sales-rep',
    slug: 'discovery_call_prep',
    mcp: 'sr_discovery_call_prep',
    name: 'Discovery Call Preparation',
    nameZh: '需求发现拜访准备',
    tags: ['discovery', 'sales', 'preparation', 'questions', 'B2B'],
    tagsZh: ['发现', '销售', '准备', '提问', 'B2B'],
    personaEn: 'You are an enterprise AE who prepares discovery with hypotheses, questions, and exit criteria.',
    personaZh: '你是企业 AE，能用假设、问题与退出标准做发现拜访准备。',
    objectiveEn: 'From account context, produce a discovery plan: goals, questions, and success signals.',
    objectiveZh: '基于客户背景，输出发现计划：目标、问题与成功信号。',
    audienceEn: 'AE and manager.',
    audienceZh: '销售与经理。',
    outputFormatEn: 'Markdown: hypothesis → agenda → questions → landmines → next step.',
    outputFormatZh: 'Markdown：假设 → 议程 → 问题 → 雷区 → 下一步。',
    vars: [
      { name: 'account', descriptionEn: 'Account notes', descriptionZh: '客户备注', exampleEn: 'Series C, 800 employees, multi-entity finance', exampleZh: 'C 轮，800 人，多主体财务', required: true },
      { name: 'persona', descriptionEn: 'Persona meeting', descriptionZh: '会面角色', exampleEn: 'VP Finance', exampleZh: '财务 VP', required: true },
    ],
    userEn: 'Account:\n{{account}}\n\nPersona:\n{{persona}}\n\nPrep discovery.',
    userZh: '客户：\n{{account}}\n\n角色：\n{{persona}}\n\n请做准备。',
    descEn: 'Discovery prep for first/second meeting.',
    descZh: '首访/二访的发现准备。',
    outEn: '## Discovery prep — FinScale (VP Finance)\n\n### Hypothesis\nThey outgrew spreadsheet payout controls; procurement wants SOC2 evidence and faster month-end.\n\n### Goals (30 min)\n- Confirm pain, quantify impact, map decision process\n\n### Agenda\n1. Context (5)\n2. Current workflow deep dive (12)\n3. Success criteria + timeline (8)\n4. Next steps (5)\n\n### Questions\n- Walk me through last month-end—where do delays happen?\n- What would "good" look like in 90 days?\n- Who else cares besides finance? (IT/security/procurement)\n\n### Landmines\nDon\'t pitch features early; avoid trashing their current bank.\n\n### Success signals\nThey share metrics (hours, error rates) and introduce procurement.\n\n### Next step\nMutual action: ROI worksheet + security packet; schedule technical deep dive.',
    outZh: '## 发现准备 — FinScale（财务 VP）\n\n### 假设\n表格打款控制已不够；采购要 SOC2 证据与更快关账。\n\n### 目标（30 分钟）\n- 确认痛点、量化影响、绘制决策流程\n\n### 议程\n1. 背景（5）\n2. 现状深挖（12）\n3. 成功标准+时间线（8）\n4. 下一步（5）\n\n### 问题\n- 走一遍上次关账——延迟卡在哪？\n- 90 天内「好」是什么样？\n- 除了财务还有谁在意？（IT/安全/采购）\n\n### 雷区\n别早推销功能；别贬低现有银行。\n\n### 成功信号\n愿意分享指标（工时、错误率）并引荐采购。\n\n### 下一步\n共创：ROI 表 + 安全材料；约技术深聊。',
  }),
  build({
    category: 'individual-contributor/sales-rep',
    slug: 'proposal_writing',
    mcp: 'sr_proposal_writing',
    name: 'Sales Proposal Writing',
    nameZh: '销售方案撰写',
    tags: ['proposal', 'sales', 'pricing', 'value', 'B2B'],
    tagsZh: ['方案', '销售', '定价', '价值', 'B2B'],
    personaEn: 'You are an AE who writes proposals that map product capabilities to customer outcomes.',
    personaZh: '你是 AE，能把产品能力映射到客户结果的方案写手。',
    objectiveEn: 'From discovery notes and SKU list, draft a proposal outline with scope, timeline, and commercial terms placeholders.',
    objectiveZh: '基于发现纪要与 SKU 清单，起草含范围、时间线与商务占位条款的方案提纲。',
    audienceEn: 'Buyer committee.',
    audienceZh: '采购决策链。',
    outputFormatEn: 'Markdown: exec summary → solution map → plan → commercials → assumptions.',
    outputFormatZh: 'Markdown：执行摘要 → 方案映射 → 计划 → 商务 → 假设。',
    vars: [
      { name: 'needs', descriptionEn: 'Customer needs', descriptionZh: '客户需求', exampleEn: 'Multi-entity payouts, SSO, audit logs, NetSuite export', exampleZh: '多主体打款、SSO、审计日志、NetSuite 导出', required: true },
      { name: 'products', descriptionEn: 'Products/modules', descriptionZh: '产品/模块', exampleEn: 'Core platform + Analytics+ + premium support', exampleZh: '核心平台 + Analytics+ + 高级支持', required: true },
    ],
    userEn: 'Needs:\n{{needs}}\n\nProducts:\n{{products}}\n\nDraft proposal.',
    userZh: '需求：\n{{needs}}\n\n产品：\n{{products}}\n\n请写方案。',
    descEn: 'Proposal skeleton after discovery.',
    descZh: '发现后的方案骨架。',
    outEn: '## Proposal — FinScale (draft)\n\n### Executive summary\nFinScale will reduce payout operational load and strengthen audit readiness by centralizing approvals, exports, and access controls—aligned to your Q3 procurement timeline.\n\n### Solution map\n| Need | Capability |\n|------|------------|\n| Multi-entity | Tenant hierarchy + scoped roles |\n| SSO | SAML/OIDC with JIT provisioning |\n| Audit logs | Immutable event stream + 13-month retention |\n| ERP | NetSuite mapped exports (daily)\n\n### Delivery plan\n- Week 1–2: discovery + security review\n- Week 3–6: integration + UAT\n- Week 7: go-live + hypercare\n\n### Commercials (placeholders)\n- Subscription: [SKU table]\n- Implementation: [SOW reference]\n\n### Assumptions\n- IT provides sandbox credentials by May 1; finance owner available 4h/week.',
    outZh: '## 方案 — FinScale（草案）\n\n### 执行摘要\n通过集中审批、导出与访问控制，降低打款运营负担并提升审计准备度，契合贵方 Q3 采购节奏。\n\n### 方案映射\n| 需求 | 能力 |\n|------|------|\n| 多主体 | 租户层级 + 范围角色 |\n| SSO | SAML/OIDC + JIT |\n| 审计日志 | 不可篡改事件流 + 13 月留存 |\n| ERP | NetSuite 映射导出（每日）\n\n### 交付计划\n- 第 1–2 周：发现 + 安全评审\n- 第 3–6 周：集成 + UAT\n- 第 7 周：上线 + 护航\n\n### 商务（占位）\n- 订阅：[SKU 表]\n- 实施：[SOW 引用]\n\n### 假设\n- IT 5/1 前提供沙箱凭证；财务负责人每周可投入 4 小时',
  }),
  build({
    category: 'individual-contributor/sales-rep',
    slug: 'objection_handling',
    mcp: 'sr_objection_handling',
    name: 'Objection Handling Playbook',
    nameZh: '异议处理话术手册',
    tags: ['objections', 'sales', 'playbook', 'negotiation', 'B2B'],
    tagsZh: ['异议', '销售', '手册', '谈判', 'B2B'],
    personaEn: 'You are an AE who handles objections with empathy, proof, and a clear next step.',
    personaZh: '你是 AE，能用共情、证据与明确下一步处理异议。',
    objectiveEn: 'From objection list, produce talk tracks with reframes and proof points.',
    objectiveZh: '基于异议清单，输出含重构与证据点的话术。',
    audienceEn: 'Sales team enablement.',
    audienceZh: '销售赋能。',
    outputFormatEn: 'Markdown: objection → intent → response → proof → question.',
    outputFormatZh: 'Markdown：异议 → 意图 → 回应 → 证据 → 提问。',
    vars: [
      { name: 'objections', descriptionEn: 'Objections heard', descriptionZh: '听到的异议', exampleEn: 'Too expensive; we can build internally; security concerns', exampleZh: '太贵；能自研；安全顾虑', required: true },
    ],
    userEn: 'Objections:\n{{objections}}\n\nWrite playbook.',
    userZh: '异议：\n{{objections}}\n\n请写手册。',
    descEn: 'Objection talk tracks for enterprise deals.',
    descZh: '企业单的异议话术。',
    outEn: '## Objection playbook (enterprise)\n\n### "Too expensive"\n- **Intent:** needs ROI + budget alignment\n- **Response:** Anchor value to hours saved + audit risk reduction, not feature count.\n- **Proof:** ROI worksheet + similar segment case study metrics\n- **Question:** What budget cycle do we need to align to—and what metric owns this decision?\n\n### "We can build internally"\n- **Intent:** control + engineering capacity\n- **Response:** Validate build scope (integrations, compliance, on-call).\n- **Proof:** Implementation timeline comparison; total cost of ownership outline\n- **Question:** What\'s the opportunity cost for your platform team this quarter?\n\n### "Security concerns"\n- **Intent:** trust + procurement checklist\n- **Response:** Offer SOC2 report, data flow diagram, and subprocessors list.\n- **Proof:** Security pack + reference calls with InfoSec peers\n- **Question:** Which controls are must-haves vs nice-to-haves in your vendor review?',
    outZh: '## 异议手册（企业）\n\n### 「太贵」\n- **意图：** 要 ROI 与预算对齐\n- **回应：** 用节省工时与审计风险定价，而非功能数量。\n- **证据：** ROI 表 + 同类客户案例指标\n- **提问：** 需对齐哪个预算周期？谁拥有这个指标决策？\n\n### 「我们可以自研」\n- **意图：** 控制 + 工程产能\n- **回应：** 对齐自研范围（集成、合规、值班）。\n- **证据：** 实施周期对比；TCO 提纲\n- **提问：** 本季度平台团队的机会成本是什么？\n\n### 「安全顾虑」\n- **意图：** 信任 + 采购清单\n- **回应：** 提供 SOC2、数据流图、子处理方清单。\n- **证据：** 安全包 + 信息安全同行引荐\n- **提问：** 哪些控制是必需 vs 加分项？',
  }),
  build({
    category: 'individual-contributor/sales-rep',
    slug: 'follow_up_email',
    mcp: 'sr_follow_up_email',
    name: 'Follow-Up Email After Meeting',
    nameZh: '会后跟进邮件',
    tags: ['email', 'sales', 'follow-up', 'communication', 'next-steps'],
    tagsZh: ['邮件', '销售', '跟进', '沟通', '下一步'],
    personaEn: 'You are an AE who sends concise follow-ups that recap decisions, owners, and dates.',
    personaZh: '你是 AE，能发简洁跟进：复盘决策、负责人与日期。',
    objectiveEn: 'From meeting notes, draft a follow-up email with summary, action table, and attachments list.',
    objectiveZh: '基于会议纪要，撰写含摘要、行动表与附件清单的跟进邮件。',
    audienceEn: 'Buying committee.',
    audienceZh: '采购决策链。',
    outputFormatEn: 'Plain email: greeting → recap → actions → attachments → CTA.',
    outputFormatZh: '邮件体：问候 → 纪要 → 行动 → 附件 → CTA。',
    vars: [
      { name: 'notes', descriptionEn: 'Meeting notes', descriptionZh: '会议记录', exampleEn: 'Agreed on security review; need NetSuite mapping sample', exampleZh: '同意安全评审；需要 NetSuite 映射样例', required: true },
      { name: 'next_meeting', descriptionEn: 'Next meeting time if known', descriptionZh: '下次会议时间', exampleEn: 'Apr 16, 10:00 CET', exampleZh: '4/16 10:00 CET', required: false },
    ],
    userEn: 'Notes:\n{{notes}}\n\nNext meeting:\n{{next_meeting}}\n\nWrite email.',
    userZh: '纪要：\n{{notes}}\n\n下次会议：\n{{next_meeting}}\n\n请写邮件。',
    descEn: 'Professional follow-up email.',
    descZh: '专业的会后跟进邮件。',
    outEn: 'Subject: FinScale — recap + next steps from today\'s working session\n\nHi Anna and team,\n\nThanks for the time today. Quick recap:\n- We aligned on the security review path (SOC2 + data flow) and procurement timeline targeting a June decision.\n- You\'ll share a sample NetSuite export so we can validate field mapping assumptions.\n\nActions\n| Action | Owner | Due |\n|--------|-------|-----|\n| Send NetSuite sample export | Anna | Apr 10 |\n| Return redlined security questionnaire | Me | Apr 12 |\n| Schedule technical deep dive | Mutual | Apr 16 10:00 CET |\n\nAttachments: meeting deck v3 + security FAQ one-pager.\n\nBest,\n[Name]',
    outZh: '主题：FinScale — 今日工作坊纪要与下一步\n\nAnna 各位好，\n\n感谢今天的时间。简要纪要：\n- 已对齐安全评审路径（SOC2 + 数据流）与 6 月决策目标。\n- 你将提供 NetSuite 导出样例以验证字段映射假设。\n\n行动项\n| 行动 | 负责人 | 截止 |\n|------|--------|------|\n| 发送 NetSuite 样例导出 | Anna | 4/10 |\n| 返回标注版安全问卷 | 我 | 4/12 |\n| 约技术深聊 | 双方 | 4/16 10:00 CET |\n\n附件：会议 deck v3 + 安全 FAQ 一页纸。\n\n祝好，\n[姓名]',
  }),

  build({
    category: 'individual-contributor/customer-success',
    slug: 'onboarding_kickoff',
    mcp: 'cs_onboarding_kickoff',
    name: 'Customer Onboarding Kickoff Plan',
    nameZh: '客户上线启动计划',
    tags: ['onboarding', 'customer-success', 'kickoff', 'implementation', 'B2B'],
    tagsZh: ['上线', '客户成功', '启动', '实施', 'B2B'],
    personaEn: 'You are a CSM who runs kickoffs that set scope, owners, and success metrics for onboarding.',
    personaZh: '你是 CSM，能用启动会明确范围、负责人与上线成功指标。',
    objectiveEn: 'From customer goals and stack, produce a kickoff agenda and 30-day onboarding plan.',
    objectiveZh: '基于客户目标与技术栈，输出启动会议程与 30 天上线计划。',
    audienceEn: 'Customer team and internal pods.',
    audienceZh: '客户团队与内部小组。',
    outputFormatEn: 'Markdown: agenda → RACI → milestones → risks → success metrics.',
    outputFormatZh: 'Markdown：议程 → RACI → 里程碑 → 风险 → 成功指标。',
    vars: [
      { name: 'goals', descriptionEn: 'Customer goals', descriptionZh: '客户目标', exampleEn: 'Go live in 45 days; migrate 3 entities; enable SSO', exampleZh: '45 天上线；迁移 3 主体；启用 SSO', required: true },
      { name: 'stack', descriptionEn: 'Systems and integrations', descriptionZh: '系统与集成', exampleEn: 'NetSuite, Okta, SFTP bank files', exampleZh: 'NetSuite、Okta、SFTP 银行文件', required: true },
    ],
    userEn: 'Goals:\n{{goals}}\n\nStack:\n{{stack}}\n\nWrite kickoff plan.',
    userZh: '目标：\n{{goals}}\n\n技术栈：\n{{stack}}\n\n请写启动计划。',
    descEn: 'Kickoff plan for complex onboarding.',
    descZh: '复杂上线的启动计划。',
    outEn: '## Onboarding kickoff — FinScale\n\n### Kickoff agenda (60 min)\n1. Goals + definition of "go-live" (10)\n2. Technical prerequisites (Okta, NetSuite creds) (15)\n3. Milestones + owners (20)\n4. Risks + communication norms (10)\n5. Next meeting + actions (5)\n\n### RACI (high level)\n- Integration: Customer IT (A), CS (C), PS (R)\n- UAT sign-off: Customer finance owner (A)\n\n### 30-day milestones\n- Week 1: sandbox connectivity + data mapping\n- Week 2: SSO + role model\n- Week 3: pilot payouts (read-only)\n- Week 4: UAT + go-live checklist\n\n### Risks\n- Bank file format variance; mitigated by early sample testing\n\n### Success metrics\n- Go-live by day 45; <1% payout errors first 2 weeks; CSAT ≥8/10 post-kickoff survey',
    outZh: '## 上线启动 — FinScale\n\n### 启动会议程（60 分钟）\n1. 目标与「上线」定义（10）\n2. 技术前置（Okta、NetSuite 凭证）（15）\n3. 里程碑与负责人（20）\n4. 风险与沟通规范（10）\n5. 下次会议与行动（5）\n\n### RACI（摘要）\n- 集成：客户 IT（A），CS（C），PS（R）\n- UAT 签字：客户财务负责人（A）\n\n### 30 天里程碑\n- 第 1 周：沙箱连通 + 数据映射\n- 第 2 周：SSO + 角色模型\n- 第 3 周：试点打款（只读）\n- 第 4 周：UAT + 上线清单\n\n### 风险\n- 银行文件格式差异；通过早期样例测试缓解\n\n### 成功指标\n- 45 天内上线；前两周打款错误率 <1%；启动后 CSAT ≥8/10',
  }),
  build({
    category: 'individual-contributor/customer-success',
    slug: 'churn_risk_assessment',
    mcp: 'cs_churn_risk_assessment',
    name: 'Churn Risk Assessment',
    nameZh: '流失风险评估',
    tags: ['churn', 'customer-success', 'risk', 'retention', 'expansion'],
    tagsZh: ['流失', '客户成功', '风险', '留存', '扩展'],
    personaEn: 'You are a CSM who assesses churn risk with evidence, stakeholder health, and save plans.',
    personaZh: '你是 CSM，能基于证据、干系人健康度与挽救计划评估流失风险。',
    objectiveEn: 'From usage, tickets, and stakeholder notes, produce a churn risk memo with severity and actions.',
    objectiveZh: '基于用量、工单与干系人记录，输出含严重度与行动的流失风险备忘录。',
    audienceEn: 'CS leadership and sales.',
    audienceZh: '客户成功与销售。',
    outputFormatEn: 'Markdown: signals → impact → plan → owners → escalation triggers.',
    outputFormatZh: 'Markdown：信号 → 影响 → 计划 → 负责人 → 升级触发。',
    vars: [
      { name: 'signals', descriptionEn: 'Risk signals', descriptionZh: '风险信号', exampleEn: 'Usage -35% MoM; exec sponsor left; 3 sev2 incidents', exampleZh: '用量环比 -35%；高管赞助人离职；3 次 sev2', required: true },
      { name: 'arr', descriptionEn: 'ARR or contract value', descriptionZh: 'ARR 或合同额', exampleEn: '$420k ARR', exampleZh: '42 万美元 ARR', required: false },
    ],
    userEn: 'Signals:\n{{signals}}\n\nARR:\n{{arr}}\n\nAssess churn risk.',
    userZh: '信号：\n{{signals}}\n\nARR：\n{{arr}}\n\n请评估流失风险。',
    descEn: 'Churn risk memo for internal alignment.',
    descZh: '内部对齐用的流失风险备忘录。',
    outEn: '## Churn risk assessment — Account ORG-882\n\n### Signals (last 45 days)\n- Active users down **35% MoM** after finance reorg\n- Executive sponsor departed; no replacement named\n- 3 Sev2 incidents related to export timeouts\n\n### Impact\n- **ARR at risk:** $420k (renewal in 96 days)\n\n### Assessment\n**High risk** — usage + sponsor gap + service friction compound.\n\n### Save plan (14 days)\n1. Executive business review with interim CFO (Owner: CSM)\n2. Engineering hotfix for export async + comms (Owner: Support lead)\n3. Success plan with weekly checkpoints (Owner: CSM)\n\n### Escalation\nIf no named sponsor within 10 days OR usage continues to drop >10% WoW, escalate to VP CS + AE manager.',
    outZh: '## 流失风险评估 — 账户 ORG-882\n\n### 信号（近 45 天）\n- 财务重组后活跃用户 **环比 -35%**\n- 高管赞助人离职；未指定接替\n- 3 次与导出超时相关的 Sev2\n\n### 影响\n- **风险 ARR：** 42 万（96 天内续约）\n\n### 判断\n**高风险** — 用量 + 赞助人空档 + 服务摩擦叠加。\n\n### 挽救（14 天）\n1. 与代理 CFO 开高管业务回顾（负责人：CSM）\n2. 工程修复异步导出 + 客户沟通（负责人：支持负责人）\n3. 成功计划 + 周对齐（负责人：CSM）\n\n### 升级\n若 10 天内无赞助人 OR 用量周环比再降 >10%，升级至 VP CS + AE 经理。',
  }),
  build({
    category: 'individual-contributor/customer-success',
    slug: 'upsell_opportunity_brief',
    mcp: 'cs_upsell_opportunity_brief',
    name: 'Upsell Opportunity Brief',
    nameZh: '扩展销售机会简报',
    tags: ['upsell', 'expansion', 'customer-success', 'revenue', 'B2B'],
    tagsZh: ['扩展', '增购', '客户成功', '收入', 'B2B'],
    personaEn: 'You are a CSM who identifies expansion opportunities tied to measurable customer outcomes.',
    personaZh: '你是 CSM，能把扩展机会与客户可量化结果绑定。',
    objectiveEn: 'From usage patterns and roadmap fit, draft an upsell brief for sales/AE handoff.',
    objectiveZh: '基于使用模式与路线图契合度，撰写供销售/AE 交接的扩展简报。',
    audienceEn: 'Account executive.',
    audienceZh: '客户经理。',
    outputFormatEn: 'Markdown: context → trigger → recommended SKU → talk track → risks.',
    outputFormatZh: 'Markdown：背景 → 触发 → 建议 SKU → 话术 → 风险。',
    vars: [
      { name: 'usage', descriptionEn: 'Usage insights', descriptionZh: '用量洞察', exampleEn: 'Analytics+ trial enabled; 120 weekly active users in dashboards', exampleZh: '试用 Analytics+；仪表盘周活 120', required: true },
      { name: 'pain', descriptionEn: 'Customer pain', descriptionZh: '客户痛点', exampleEn: 'CFO wants board-ready variance narratives', exampleZh: 'CFO 要董事会级差异叙事', required: true },
    ],
    userEn: 'Usage:\n{{usage}}\n\nPain:\n{{pain}}\n\nWrite upsell brief.',
    userZh: '用量：\n{{usage}}\n\n痛点：\n{{pain}}\n\n请写扩展简报。',
    descEn: 'Expansion brief for AE collaboration.',
    descZh: '与 AE 协作的扩展简报。',
    outEn: '## Upsell brief — ORG-441 (handoff to AE)\n\n### Context\nCustomer completed onboarding ahead of schedule; finance team adopted exports quickly.\n\n### Trigger\n- **Analytics+** trial shows 120 WAU on dashboards; 6 saved views owned by FP&A.\n- CFO asked for "board-ready variance narratives" in last QBR.\n\n### Recommended motion\n- Propose **Analytics+** annual add-on + 2 workshops for FP&A storytelling.\n\n### Talk track\nAnchor on reducing board prep time and standardizing variance explanations—not "more charts."\n\n### Risks\n- Procurement may bundle into renewal; start early with ROI worksheet.\n\n### Next step\nAE to schedule exec alignment call with CFO within 14 days; CSM to provide usage screenshots + adoption notes.',
    outZh: '## 扩展简报 — ORG-441（交接 AE）\n\n### 背景\n客户提前完成上线；财务团队快速采用导出能力。\n\n### 触发\n- **Analytics+** 试用仪表盘周活 120；FP&A 保存视图 6 个。\n- 上次 QBR CFO 提到要「董事会级差异叙事」。\n\n### 建议动作\n- 推 **Analytics+** 年付加购 + 2 次 FP&A 叙事工作坊。\n\n### 话术\n强调减少董事会准备时间与差异解释标准化，而非「更多图表」。\n\n### 风险\n- 采购可能并入续约谈判；尽早给 ROI 表。\n\n### 下一步\nAE 14 天内约 CFO 对齐会；CSM 提供用量截图与采用说明。',
  }),
  build({
    category: 'individual-contributor/customer-success',
    slug: 'health_score_review',
    mcp: 'cs_health_score_review',
    name: 'Customer Health Score Review',
    nameZh: '客户健康分复盘',
    tags: ['health-score', 'customer-success', 'metrics', 'retention', 'expansion'],
    tagsZh: ['健康分', '客户成功', '指标', '留存', '扩展'],
    personaEn: 'You are a CSM who interprets health scores with qualitative context and next actions.',
    personaZh: '你是 CSM，能结合定性上下文解读健康分并给出下一步。',
    objectiveEn: 'From score components and notes, produce a health review with narrative and playbook triggers.',
    objectiveZh: '基于分数构成与备注，输出含叙事与手册触发的健康复盘。',
    audienceEn: 'CS management.',
    audienceZh: '客户成功管理。',
    outputFormatEn: 'Markdown: score → drivers → narrative → actions → playbook trigger.',
    outputFormatZh: 'Markdown：分数 → 驱动 → 叙事 → 行动 → 手册触发。',
    vars: [
      { name: 'scores', descriptionEn: 'Component scores', descriptionZh: '分项分数', exampleEn: 'Usage 72, Support 45, Relationship 60, Outcomes 55', exampleZh: '用量 72，支持 45，关系 60，结果 55', required: true },
      { name: 'context', descriptionEn: 'Qualitative notes', descriptionZh: '定性备注', exampleEn: 'Recent migration caused ticket spike; champion still engaged', exampleZh: '迁移导致工单激增；支持者仍积极', required: false },
    ],
    userEn: 'Scores:\n{{scores}}\n\nContext:\n{{context}}\n\nWrite health review.',
    userZh: '分数：\n{{scores}}\n\n背景：\n{{context}}\n\n请写健康复盘。',
    descEn: 'Health score interpretation for QBR prep.',
    descZh: '供 QBR 准备的健康分解读。',
    outEn: '## Health score review — ORG-119\n\n### Composite\n**58 / 100 (Yellow)**\n\n### Drivers\n- Usage: 72 (stable WAU; power users growing)\n- Support: 45 (elevated Sev2 count during migration)\n- Relationship: 60 (champion engaged; new CFO not yet met)\n- Outcomes: 55 (value narrative not revalidated post-migration)\n\n### Narrative\nHealth is **mixed**: product adoption is solid, but service friction and executive coverage gaps create renewal risk if unaddressed.\n\n### Actions (14 days)\n- Executive intro meeting with new CFO (CSM + AE)\n- Migration postmortem + corrective actions comms\n- Re-run success plan workshop focused on KPIs\n\n### Playbook trigger\n**Yellow → Save plan** if support score remains <50 after 30 days.',
    outZh: '## 健康分复盘 — ORG-119\n\n### 综合\n**58 / 100（黄）**\n\n### 驱动\n- 用量 72（WAU 稳定；深度用户增长）\n- 支持 45（迁移期 Sev2 偏高）\n- 关系 60（支持者积极；新 CFO 未见面）\n- 结果 55（迁移后价值叙事未再验证）\n\n### 叙事\n**混合**：采用不错，但服务摩擦与高管覆盖缺口若不处理会带来续约风险。\n\n### 行动（14 天）\n- CSM+AE 与新 CFO 高管介绍会\n- 迁移复盘 + 纠正措施沟通\n- 以 KPI 为中心重开成功计划工作坊\n\n### 手册触发\n若 30 天后支持分仍 <50，**黄 → 挽救计划**。',
  }),

  build({
    category: 'individual-contributor/legal',
    slug: 'nda_review_checklist',
    mcp: 'leg_nda_review_checklist',
    name: 'NDA Review Checklist',
    nameZh: '保密协议审查清单',
    tags: ['NDA', 'legal', 'contract', 'checklist', 'compliance'],
    tagsZh: ['保密协议', '法务', '合同', '清单', '合规'],
    personaEn: 'You are an in-house counsel who reviews NDAs for scope, duration, residuals, and carve-outs.',
    personaZh: '你是公司法务，能从范围、期限、残留条款与例外审查 NDA。',
    objectiveEn: 'From party roles and business context, produce an NDA review checklist with red-flag patterns.',
    objectiveZh: '基于双方角色与业务背景，输出含红旗模式的 NDA 审查清单。',
    audienceEn: 'Legal and business approvers.',
    audienceZh: '法务与业务审批人。',
    outputFormatEn: 'Markdown: checklist → red flags → negotiation levers → escalation.',
    outputFormatZh: 'Markdown：清单 → 红旗 → 谈判抓手 → 升级。',
    vars: [
      { name: 'context', descriptionEn: 'Deal context', descriptionZh: '交易背景', exampleEn: 'Vendor evaluation for payout platform; two-way NDA', exampleZh: '评估打款平台供应商；双向 NDA', required: true },
    ],
    userEn: 'Context:\n{{context}}\n\nCreate NDA checklist.',
    userZh: '背景：\n{{context}}\n\n请生成 NDA 清单。',
    descEn: 'Practical NDA review checklist (not legal advice).',
    descZh: '实用的 NDA 审查清单（非法律意见）。',
    systemExtraEn: '\n- This is not legal advice; escalate unusual clauses to qualified counsel',
    systemExtraZh: '\n- 非法律意见；异常条款应交执业律师复核',
    outEn: '## NDA review checklist (internal)\n\n### Parties & purpose\n- Correct legal names; affiliate coverage matches actual disclosure needs\n- Purpose limited to evaluation of [specific project]\n\n### Confidentiality scope\n- Definition covers technical + commercial materials; excludes publicly available info\n- Marking rules practical (written + identified oral)\n\n### Duration\n- Confidentiality survival: 3–5 years typical; indefinite only for true trade secrets\n\n### Risky clauses\n- **Residuals** memory carve-outs (often unacceptable)\n- **Non-compete / exclusivity** smuggled into NDA\n- **IP assignment** beyond feedback clauses\n\n### Process\n- Confirm return/destruction on termination\n- Record exceptions list if any pre-existing overlaps\n\n### Escalate if\n- One-way obligations with broad definition; venue in hostile jurisdiction; uncapped liability',
    outZh: '## NDA 审查清单（内部）\n\n### 主体与目的\n- 法定名称正确；关联方覆盖与实际披露范围一致\n- 目的限定为评估 [具体项目]\n\n### 保密范围\n- 定义覆盖技术+商业材料；排除公开信息\n- 标识规则可执行（书面+可识别口头）\n\n### 期限\n- 保密义务存续：通常 3–5 年；真正商业秘密可更长\n\n### 高风险条款\n- **残留记忆**免责（常不可接受）\n- 夹带**竞业/独家**\n- 超出反馈的**知识产权转让**\n\n### 流程\n- 终止时归还/销毁\n- 记录既有信息重叠例外\n\n### 升级\n- 单方义务+过宽定义；不利法域管辖；无限责任',
  }),
  build({
    category: 'individual-contributor/legal',
    slug: 'privacy_policy_audit',
    mcp: 'leg_privacy_policy_audit',
    name: 'Privacy Policy Compliance Audit',
    nameZh: '隐私政策合规审计',
    tags: ['privacy', 'GDPR', 'legal', 'compliance', 'policy'],
    tagsZh: ['隐私', 'GDPR', '法务', '合规', '政策'],
    personaEn: 'You are legal counsel who audits privacy policies for transparency, lawful bases, and operational alignment.',
    personaZh: '你是法务，能审计隐私政策的透明度、法律依据与运营一致性。',
    objectiveEn: 'From jurisdictions and processing activities, draft a privacy policy gap analysis outline.',
    objectiveZh: '基于司法辖区与处理活动，起草隐私政策差距分析提纲。',
    audienceEn: 'Privacy program owners.',
    audienceZh: '隐私项目负责人。',
    outputFormatEn: 'Markdown: scope → required disclosures → gaps → remediation → owners.',
    outputFormatZh: 'Markdown：范围 → 必备披露 → 差距 → 整改 → 负责人。',
    vars: [
      { name: 'jurisdictions', descriptionEn: 'Jurisdictions', descriptionZh: '司法辖区', exampleEn: 'EU + UK + US (California)', exampleZh: '欧盟+英国+美国（加州）', required: true },
      { name: 'processing', descriptionEn: 'Key processing activities', descriptionZh: '主要处理活动', exampleEn: 'Product analytics, support tickets, payment processing', exampleZh: '产品分析、客服工单、支付处理', required: true },
    ],
    userEn: 'Jurisdictions:\n{{jurisdictions}}\n\nProcessing:\n{{processing}}\n\nAudit outline.',
    userZh: '辖区：\n{{jurisdictions}}\n\n处理活动：\n{{processing}}\n\n请写审计提纲。',
    descEn: 'Privacy policy gap analysis skeleton.',
    descZh: '隐私政策差距分析骨架。',
    systemExtraEn: '\n- Not legal advice; involve DPO and local counsel',
    systemExtraZh: '\n- 非法律意见；需 DPO 与本地律师',
    outEn: '## Privacy policy audit — outline\n\n### Scope\nPublic privacy policy + internal ROPA alignment for EU/UK + US-CA consumers.\n\n### Required disclosures (check)\n- Categories of personal data collected\n- Purposes and lawful bases (GDPR Art. 6/9 where relevant)\n- Subprocessors / international transfers + safeguards\n- Retention criteria; rights request process\n\n### Gaps observed\n- **Transfers:** SCCs referenced but subprocessors list outdated (6 vendors)\n- **Retention:** vague language ("as long as needed") without examples\n- **Cookies:** marketing cookies described inconsistently with cookie banner\n\n### Remediation\n- Update subprocessor appendix + last-updated date\n- Add retention schedule by data category (table)\n- Align marketing section with CMP categories\n\n### Owners\n- Legal: policy text; Security: transfer assessments; Web: banner alignment',
    outZh: '## 隐私政策审计 — 提纲\n\n### 范围\n公开隐私政策 + 内部 ROPA 对齐（欧盟/英国 + 美国加州消费者）。\n\n### 必备披露（检查）\n- 收集的个人数据类别\n- 处理目的与法律依据（涉 GDPR 第 6/9 条）\n- 子处理者/跨境转移与保障措施\n- 留存标准；权利请求流程\n\n### 差距\n- **转移：** 提及 SCC 但子处理者清单过期（6 家）\n- **留存：** 表述模糊（「按需」）缺示例\n- **Cookie：** 与 CMP 分类不一致\n\n### 整改\n- 更新子处理者附录与更新日期\n- 按数据类别补充留存表\n- 营销段落与 CMP 对齐\n\n### 负责人\n- 法务：文本；安全：转移评估；网站：横幅',
  }),
  build({
    category: 'individual-contributor/legal',
    slug: 'ip_assessment_memo',
    mcp: 'leg_ip_assessment_memo',
    name: 'IP Assessment Memo',
    nameZh: '知识产权评估备忘录',
    tags: ['IP', 'legal', 'patent', 'trade-secret', 'memo'],
    tagsZh: ['知识产权', '法务', '专利', '商业秘密', '备忘录'],
    personaEn: 'You are legal counsel who assesses IP risks for product features and third-party components.',
    personaZh: '你是法务，能评估产品功能与第三方组件的知识产权风险。',
    objectiveEn: 'From feature description and components, draft an IP assessment memo outline.',
    objectiveZh: '基于功能描述与组件，起草知识产权评估备忘录提纲。',
    audienceEn: 'Product and legal leadership.',
    audienceZh: '产品与法务管理层。',
    outputFormatEn: 'Markdown: facts → rights considered → risks → mitigations → open questions.',
    outputFormatZh: 'Markdown：事实 → 考量权利 → 风险 → 缓解 → 开放问题。',
    vars: [
      { name: 'feature', descriptionEn: 'Feature description', descriptionZh: '功能描述', exampleEn: 'LLM-assisted invoice anomaly explanations', exampleZh: '大模型辅助发票异常解释', required: true },
      { name: 'components', descriptionEn: 'Third-party components', descriptionZh: '第三方组件', exampleEn: 'Open model weights; customer data prompts', exampleZh: '开源模型权重；客户数据提示', required: true },
    ],
    userEn: 'Feature:\n{{feature}}\n\nComponents:\n{{components}}\n\nDraft IP memo outline.',
    userZh: '功能：\n{{feature}}\n\n组件：\n{{components}}\n\n请写知产备忘录提纲。',
    descEn: 'IP risk memo skeleton for new features.',
    descZh: '新功能的知产风险备忘录骨架。',
    systemExtraEn: '\n- Not legal advice; patent counsel review required for filings',
    systemExtraZh: '\n- 非法律意见；申请专利需专利律师',
    outEn: '## IP assessment memo — LLM invoice explanations (outline)\n\n### Facts\nFeature generates natural-language explanations for anomalies using a hosted model; prompts may include customer invoice metadata.\n\n### Rights considered\n- **Copyright:** training data provenance; output originality\n- **Trade secrets:** prompt templates and scoring thresholds\n- **Patents:** potential overlap with known anomaly-detection patents (landscape TBD)\n\n### Risks\n- Vendor TOS restrictions on storing/logging prompts\n- Customer contract terms on derivative works / ownership of outputs\n\n### Mitigations\n- Data processing agreement + zero-retention inference option\n- Clear customer license to generated explanations; avoid training on customer data without consent\n\n### Open questions\n- Do we need freedom-to-operate search for EU filings?\n- Should outputs be watermarked/disclaimed as advisory-only?',
    outZh: '## 知产评估备忘录 — 大模型发票解释（提纲）\n\n### 事实\n功能用托管模型生成异常自然语言解释；提示可能含客户发票元数据。\n\n### 考量权利\n- **著作权：** 训练数据来源；输出原创性\n- **商业秘密：** 提示模板与阈值\n- **专利：** 与已知异常检测专利的潜在重叠（待检索）\n\n### 风险\n- 供应商 TOS 对提示存储/日志的限制\n- 客户合同对衍生作品/输出权属条款\n\n### 缓解\n- DPA + 零留存推理选项\n- 明确客户对生成解释的使用许可；未经同意不用客户数据训练\n\n### 开放问题\n- 是否需欧盟 FTO 检索？\n- 输出是否加水印/免责声明（建议性质）？',
  }),
  build({
    category: 'individual-contributor/legal',
    slug: 'regulatory_compliance_brief',
    mcp: 'leg_regulatory_compliance_brief',
    name: 'Regulatory Compliance Brief',
    nameZh: '监管合规简报',
    tags: ['regulatory', 'compliance', 'legal', 'risk', 'brief'],
    tagsZh: ['监管', '合规', '法务', '风险', '简报'],
    personaEn: 'You are legal counsel who summarizes regulatory obligations for product and GTM teams.',
    personaZh: '你是法务，能向产品与 GTM 团队概述监管义务。',
    objectiveEn: 'From industry and regions, produce a compliance brief with obligations, gaps, and monitoring.',
    objectiveZh: '基于行业与地区，输出含义务、差距与监控的合规简报。',
    audienceEn: 'Cross-functional stakeholders.',
    audienceZh: '跨职能干系人。',
    outputFormatEn: 'Markdown: scope → obligations → controls → gaps → roadmap.',
    outputFormatZh: 'Markdown：范围 → 义务 → 控制 → 差距 → 路线图。',
    vars: [
      { name: 'industry', descriptionEn: 'Industry / product area', descriptionZh: '行业/产品领域', exampleEn: 'B2B payments + KYC-lite for merchants', exampleZh: 'B2B 支付 + 商户轻 KYC', required: true },
      { name: 'regions', descriptionEn: 'Regions', descriptionZh: '地区', exampleEn: 'EU, UK, US', exampleZh: '欧盟、英国、美国', required: true },
    ],
    userEn: 'Industry:\n{{industry}}\n\nRegions:\n{{regions}}\n\nWrite brief.',
    userZh: '行业：\n{{industry}}\n\n地区：\n{{regions}}\n\n请写简报。',
    descEn: 'High-level regulatory brief (not legal advice).',
    descZh: '高层监管简报（非法律意见）。',
    systemExtraEn: '\n- Not legal advice; requires qualified regulatory counsel',
    systemExtraZh: '\n- 非法律意见；需合规律师',
    outEn: '## Regulatory compliance brief — B2B payouts (EU/UK/US)\n\n### Scope\nCustomer-funded payouts, merchant onboarding, and stored payment credentials.\n\n### Key obligations (non-exhaustive)\n- **AML/KYC:** risk-based CDD for merchants; SAR processes where applicable\n- **Data protection:** GDPR/UK GDPR lawful bases; DPIA for high-risk processing\n- **Payments rules:** scheme/partner rules + strong customer authentication contexts\n\n### Controls in place\n- Vendor risk program; access reviews quarterly; encryption + key management\n\n### Gaps\n- Merchant risk scoring model documentation needs refresh\n- US state privacy notices vary; marketing pixel inventory incomplete\n\n### Roadmap (90 days)\n- Update DPIA + ROPA; complete pixel inventory; train GTM on claims guardrails',
    outZh: '## 监管合规简报 — B2B 打款（欧盟/英国/美国）\n\n### 范围\n客户资金打款、商户入网、存储的支付凭证。\n\n### 主要义务（非穷尽）\n- **反洗钱/KYC：** 对商户的风险为本尽调；适用时 SAR 流程\n- **数据保护：** GDPR/英国 GDPR 法律依据；高风险处理需 DPIA\n- **支付规则：** 卡组/伙伴规则 + 强客户认证场景\n\n### 现有控制\n- 供应商风险项目；季度访问评审；加密与密钥管理\n\n### 差距\n- 商户风险评分模型文档需更新\n- 美国各州隐私声明差异；营销像素清单不全\n\n### 90 天路线\n- 更新 DPIA+ROPA；完成像素清单；培训 GTM 话术边界',
  }),
];
