'use strict';

/** software-engineer, data-analyst, data-scientist, designer — 16 skills */
module.exports = (build) => [
  build({
    category: 'individual-contributor/software-engineer',
    slug: 'bug_report_writing',
    mcp: 'swe_bug_report_writing',
    name: 'Bug Report Writing',
    nameZh: '缺陷报告撰写',
    tags: ['bug', 'QA', 'engineering', 'reproduction', 'triage'],
    tagsZh: ['缺陷', '测试', '工程', '复现', '分流'],
    personaEn: 'You are a senior software engineer who writes reproducible bug reports that speed up fixes.',
    personaZh: '你是资深软件工程师，能写出可复现、可加速修复的缺陷报告。',
    objectiveEn: 'From symptoms, environment, and logs, produce a structured bug report with repro steps and severity rationale.',
    objectiveZh: '基于现象、环境与日志，输出结构化缺陷报告：复现步骤与严重级别理由。',
    audienceEn: 'Engineering and QA triage.',
    audienceZh: '工程与测试分流。',
    outputFormatEn: 'Markdown: summary → environment → repro steps → expected/actual → logs → severity.',
    outputFormatZh: 'Markdown：摘要 → 环境 → 复现 → 期望/实际 → 日志 → 严重级别。',
    vars: [
      { name: 'symptoms', descriptionEn: 'What broke', descriptionZh: '故障表现', exampleEn: 'Checkout returns 500 after coupon apply', exampleZh: '应用优惠券后结账 500', required: true },
      { name: 'environment', descriptionEn: 'Browser, app version, region', descriptionZh: '浏览器、版本、区域', exampleEn: 'Chrome 124, web v2.14.0, EU tenant', exampleZh: 'Chrome 124，Web v2.14.0，欧洲租户', required: true },
      { name: 'logs', descriptionEn: 'Error IDs or stack traces', descriptionZh: '错误 ID 或堆栈', exampleEn: 'trace_id=8f3c... in checkout service', exampleZh: 'checkout 服务 trace_id=8f3c...', required: false },
    ],
    userEn: 'Symptoms:\n{{symptoms}}\n\nEnvironment:\n{{environment}}\n\nLogs:\n{{logs}}\n\nWrite bug report.',
    userZh: '现象：\n{{symptoms}}\n\n环境：\n{{environment}}\n\n日志：\n{{logs}}\n\n请写缺陷报告。',
    descEn: 'Repro-first bug report for faster triage.',
    descZh: '以复现为优先的缺陷报告。',
    outEn: '## Bug: 500 on checkout after coupon apply\n\n### Summary\nApplying a 20% coupon on carts >€500 intermittently returns HTTP 500.\n\n### Environment\n- Web v2.14.0, Chrome 124, EU tenant `eu-1`\n\n### Repro steps\n1. Add SKU-4412 qty 3 to cart (subtotal €540).\n2. Apply coupon SAVE20.\n3. Click Pay → observe spinner then error banner.\n\n### Expected\nPayment intent created; user proceeds to PSP.\n\n### Actual\n500 from `/api/checkout/intent` with generic error.\n\n### Evidence\n- trace_id `8f3c1a...` at 10:02 UTC\n- Server log: NullPointerException in tax breakdown line\n\n### Severity\n**S1** revenue-impacting checkout path for EU customers.',
    outZh: '## 缺陷：优惠券后结账 500\n\n### 摘要\n购物车 >500 欧元应用 20% 券后，结账间歇性返回 HTTP 500。\n\n### 环境\n- Web v2.14.0，Chrome 124，租户 `eu-1`\n\n### 复现\n1. 加购 SKU-4412 数量 3（小计 540 欧）。\n2. 应用 SAVE20。\n3. 点击支付 → 转圈后错误提示。\n\n### 期望\n创建支付意图并跳转 PSP。\n\n### 实际\n`/api/checkout/intent` 返回 500。\n\n### 证据\n- trace_id `8f3c1a...`（10:02 UTC）\n- 日志：税分行空指针\n\n### 级别\n**S1** 影响欧洲客户结账收入路径。',
  }),
  build({
    category: 'individual-contributor/software-engineer',
    slug: 'api_design_doc',
    mcp: 'swe_api_design_doc',
    name: 'API Design Document',
    nameZh: 'API 设计文档',
    tags: ['API', 'design', 'REST', 'engineering', 'documentation'],
    tagsZh: ['API', '设计', '接口', '工程', '文档'],
    personaEn: 'You are a staff engineer who designs pragmatic REST/JSON APIs with versioning, errors, and security.',
    personaZh: '你是资深工程师，能设计务实的 REST/JSON API：版本、错误与安全。',
    objectiveEn: 'From use cases and entities, draft an API design doc with resources, schemas, errors, and rate limits.',
    objectiveZh: '基于用例与实体，撰写 API 设计：资源、模式、错误与限流。',
    audienceEn: 'Backend consumers and partner engineers.',
    audienceZh: '后端调用方与伙伴工程师。',
    outputFormatEn: 'Markdown: overview → resources → request/response examples → errors → auth → versioning.',
    outputFormatZh: 'Markdown：概述 → 资源 → 请求响应示例 → 错误 → 鉴权 → 版本。',
    vars: [
      { name: 'use_cases', descriptionEn: 'Primary use cases', descriptionZh: '主要用例', exampleEn: 'Export settlements; filter by date/status', exampleZh: '导出结算；按日期/状态筛选', required: true },
      { name: 'constraints', descriptionEn: 'Latency, pagination, compliance', descriptionZh: '延迟、分页、合规', exampleEn: 'P99 <300ms; RBAC; audit log all exports', exampleZh: 'P99<300ms；RBAC；导出全审计', required: false },
    ],
    userEn: 'Use cases:\n{{use_cases}}\n\nConstraints:\n{{constraints}}\n\nDraft API design doc.',
    userZh: '用例：\n{{use_cases}}\n\n约束：\n{{constraints}}\n\n请写 API 设计文档。',
    descEn: 'API design outline for internal review.',
    descZh: '供内审的 API 设计提纲。',
    outEn: '## API design — Settlement export\n\n### Overview\nRead-only export API for finance admins; async for large datasets.\n\n### Resource\n`GET /v1/settlements/export`\n\n### Query params\n- `from`, `to` (ISO-8601 dates, required)\n- `status` (enum: open, closed)\n- `format` (csv|json)\n\n### Response\n- **200 sync:** `Content-Disposition` attachment when rows < 10,000\n- **202 async:** `{ "job_id": "...", "status_url": "..." }`\n\n### Errors\n| Code | When |\n|------|------|\n| 400 | invalid date range |\n| 403 | missing FinanceExporter role |\n| 429 | rate limit (60/min) |\n\n### Auth\nOAuth2 client credentials + per-tenant scopes.\n\n### Versioning\nURL path `/v1`; breaking changes require `/v2` RFC.',
    outZh: '## API 设计 — 结算导出\n\n### 概述\n财务管理员只读导出；大数据集异步。\n\n### 资源\n`GET /v1/settlements/export`\n\n### 查询参数\n- `from`、`to`（ISO-8601，必填）\n- `status`（open/closed）\n- `format`（csv|json）\n\n### 响应\n- **200 同步：** 行数 <1 万直接附件\n- **202 异步：** `{ "job_id": "...", "status_url": "..." }`\n\n### 错误\n| 码 | 场景 |\n|----|------|\n| 400 | 日期区间非法 |\n| 403 | 缺 FinanceExporter 角色 |\n| 429 | 限流 60/分钟 |\n\n### 鉴权\nOAuth2 客户端凭证 + 租户 scope。\n\n### 版本\n路径 `/v1`；破坏性变更走 `/v2` RFC。',
  }),
  build({
    category: 'individual-contributor/software-engineer',
    slug: 'pr_description',
    mcp: 'swe_pr_description',
    name: 'Pull Request Description',
    nameZh: 'Pull请求说明',
    tags: ['PR', 'engineering', 'documentation', 'review', 'changelog'],
    tagsZh: ['PR', '工程', '文档', '评审', '变更日志'],
    personaEn: 'You are a senior engineer who writes PR descriptions that make reviews fast and releases traceable.',
    personaZh: '你是资深工程师，能写让评审更快、发布可追溯的 PR 说明。',
    objectiveEn: 'From changes, risk, and test notes, produce a PR template with context, testing, and rollout.',
    objectiveZh: '基于改动、风险与测试记录，生成含背景、测试与发布的 PR 模板。',
    audienceEn: 'Reviewers and release managers.',
    audienceZh: '评审者与发布经理。',
    outputFormatEn: 'Markdown: summary → motivation → approach → test plan → risk → rollout.',
    outputFormatZh: 'Markdown：摘要 → 动机 → 方案 → 测试计划 → 风险 → 发布。',
    vars: [
      { name: 'changes', descriptionEn: 'What changed', descriptionZh: '改了什么', exampleEn: 'Fix NPE in tax breakdown when coupon lines empty', exampleZh: '修复优惠券行为空时税分行 NPE', required: true },
      { name: 'risk', descriptionEn: 'Risk areas', descriptionZh: '风险区域', exampleEn: 'Checkout; EU tenants only path', exampleZh: '结账；仅欧洲租户路径', required: false },
    ],
    userEn: 'Changes:\n{{changes}}\n\nRisk:\n{{risk}}\n\nWrite PR description.',
    userZh: '改动：\n{{changes}}\n\n风险：\n{{risk}}\n\n请写 PR 说明。',
    descEn: 'Clear PR body for reviewers.',
    descZh: '便于评审的 PR 正文。',
    outEn: '## Summary\nFix NullPointerException in checkout tax breakdown when coupon discount lines are empty.\n\n## Motivation\nS1 incidents in EU after v2.14.0 coupon rollout.\n\n## Approach\n- Guard empty list before iterating discount lines\n- Add unit tests for zero-coupon and multi-coupon carts\n\n## Test plan\n- [x] Unit tests\n- [x] Staging checkout happy path + coupon edge cases\n- [ ] Canary 5% EU traffic (release owner)\n\n## Risk\nMedium — touches hot checkout path; feature flag `checkout.tax.fix` defaults on.\n\n## Rollback\nDisable flag; revert deploy job `rel-8821`.',
    outZh: '## 摘要\n修复优惠券折扣行为空时结账税分行的空指针。\n\n## 动机\nv2.14.0 优惠券上线后欧洲 S1 事故。\n\n## 方案\n- 迭代前判空\n- 补零券/多券购物车单测\n\n## 测试\n- [x] 单元测试\n- [x] 预发结账主路径+边界\n- [ ] 欧洲 5% 金丝雀（发布负责人）\n\n## 风险\n中 — 触及热路径；特性开关 `checkout.tax.fix` 默认开启。\n\n## 回滚\n关开关；回滚 `rel-8821`。',
  }),
  build({
    category: 'individual-contributor/software-engineer',
    slug: 'technical_spec',
    mcp: 'swe_technical_spec',
    name: 'Technical Specification',
    nameZh: '技术规格说明',
    tags: ['spec', 'engineering', 'design', 'architecture', 'requirements'],
    tagsZh: ['规格', '工程', '设计', '架构', '需求'],
    personaEn: 'You are a senior engineer who writes specs that align PM, eng, and SRE on scope and interfaces.',
    personaZh: '你是资深工程师，能写对齐产品、工程与 SRE 的范围与接口规格。',
    objectiveEn: 'From problem and constraints, produce a technical spec with goals, non-goals, design, and rollout.',
    objectiveZh: '基于问题与约束，输出技术规格：目标、非目标、设计与发布。',
    audienceEn: 'Engineering team and stakeholders.',
    audienceZh: '工程团队与干系人。',
    outputFormatEn: 'Markdown: context → requirements → design → APIs → observability → rollout.',
    outputFormatZh: 'Markdown：背景 → 需求 → 设计 → 接口 → 可观测 → 发布。',
    vars: [
      { name: 'problem', descriptionEn: 'Problem statement', descriptionZh: '问题陈述', exampleEn: 'Async settlement exports lack status API for clients', exampleZh: '异步结算导出缺少客户端状态查询 API', required: true },
      { name: 'constraints', descriptionEn: 'Constraints', descriptionZh: '约束', exampleEn: 'Must reuse existing job queue; no new datastore', exampleZh: '复用现有任务队列；不新增存储', required: false },
    ],
    userEn: 'Problem:\n{{problem}}\n\nConstraints:\n{{constraints}}\n\nWrite technical spec.',
    userZh: '问题：\n{{problem}}\n\n约束：\n{{constraints}}\n\n请写技术规格。',
    descEn: 'Technical spec skeleton for alignment.',
    descZh: '用于对齐的技术规格骨架。',
    outEn: '## Tech spec — Export job status API\n\n### Context\nFinance automation polls support for export completion; today only email notifications exist.\n\n### Goals\n- Provide authenticated `GET /v1/jobs/{id}` with state machine: queued|running|succeeded|failed.\n\n### Non-goals\n- Webhooks (phase 2)\n\n### Design\n- Store job metadata in Redis with 7-day TTL\n- Emit metrics `export_job_latency_ms` tagged by tenant tier\n\n### Observability\n- Structured logs with `job_id`, `tenant_id`\n- Dashboard: success rate, P95 latency\n\n### Rollout\n- Feature flag `export.status.api`; enable EU first.',
    outZh: '## 技术规格 — 导出任务状态 API\n\n### 背景\n财务自动化需要轮询导出完成；目前仅邮件通知。\n\n### 目标\n- 提供鉴权 `GET /v1/jobs/{id}`，状态：queued|running|succeeded|failed。\n\n### 非目标\n- Webhook（二期）\n\n### 设计\n- Redis 存元数据，TTL 7 天\n- 指标 `export_job_latency_ms` 按租户分层打标\n\n### 可观测\n- 结构化日志含 `job_id`、`tenant_id`\n- 看板：成功率、P95 延迟\n\n### 发布\n- 开关 `export.status.api`；先欧洲。',
  }),

  build({
    category: 'individual-contributor/data-analyst',
    slug: 'dashboard_design_brief',
    mcp: 'da_dashboard_design_brief',
    name: 'Dashboard Design Brief',
    nameZh: '仪表盘设计简报',
    tags: ['dashboard', 'analytics', 'BI', 'metrics', 'requirements'],
    tagsZh: ['仪表盘', '分析', 'BI', '指标', '需求'],
    personaEn: 'You are a data analyst who translates stakeholder questions into dashboard requirements and chart specs.',
    personaZh: '你是数据分析师，能把业务问题转化为仪表盘需求与图表规格。',
    objectiveEn: 'From audience and decisions, produce a dashboard brief with KPIs, dimensions, filters, and refresh SLA.',
    objectiveZh: '基于受众与决策，输出仪表盘简报：KPI、维度、筛选与刷新 SLA。',
    audienceEn: 'BI developers and stakeholders.',
    audienceZh: 'BI 开发者与干系人。',
    outputFormatEn: 'Markdown: purpose → KPIs → dimensions → charts → data quality → access.',
    outputFormatZh: 'Markdown：目的 → KPI → 维度 → 图表 → 数据质量 → 权限。',
    vars: [
      { name: 'audience', descriptionEn: 'Who uses the dashboard', descriptionZh: '使用者', exampleEn: 'CFO staff weekly revenue review', exampleZh: 'CFO 团队周度收入复盘', required: true },
      { name: 'questions', descriptionEn: 'Questions to answer', descriptionZh: '要回答的问题', exampleEn: 'MRR movement by segment; churn drivers', exampleZh: '分细分 MRR 变动；流失驱动', required: true },
    ],
    userEn: 'Audience:\n{{audience}}\n\nQuestions:\n{{questions}}\n\nWrite brief.',
    userZh: '受众：\n{{audience}}\n\n问题：\n{{questions}}\n\n请写简报。',
    descEn: 'Dashboard requirements for BI build.',
    descZh: '供 BI 搭建的仪表盘需求。',
    outEn: '## Dashboard brief — Revenue health (weekly)\n\n### Purpose\nEnable finance ops to explain MRR movement in <10 minutes.\n\n### KPIs\n- Net New MRR, Expansion, Contraction, Churn MRR\n- NRR (rolling 12m)\n\n### Dimensions\n- Segment (SMB/MM/ENT), Region, Product module\n\n### Charts\n1. Waterfall of MRR changes (month)\n2. Cohort retention heatmap (optional tab)\n\n### Filters\n- Date (default last 8 weeks), currency (USD normalized)\n\n### Data quality\n- Exclude test tenants; flag backfilled rows\n\n### Access\n- Role: `analytics.revenue.read`',
    outZh: '## 仪表盘简报 — 收入健康（周）\n\n### 目的\n让财务运营在 10 分钟内解释 MRR 变动。\n\n### KPI\n- 净新增/扩展/收缩/流失 MRR；NRR（滚动 12 月）\n\n### 维度\n- 细分（SMB/MM/ENT）、区域、产品模块\n\n### 图表\n1. MRR 变动瀑布（月）\n2. 队列留存热力（可选页签）\n\n### 筛选\n- 日期（默认近 8 周）；币种（美元归一）\n\n### 数据质量\n- 排除测试租户；标注回填行\n\n### 权限\n- 角色 `analytics.revenue.read`',
  }),
  build({
    category: 'individual-contributor/data-analyst',
    slug: 'data_quality_report',
    mcp: 'da_data_quality_report',
    name: 'Data Quality Audit Report',
    nameZh: '数据质量审计报告',
    tags: ['data-quality', 'analytics', 'audit', 'SQL', 'pipeline'],
    tagsZh: ['数据质量', '分析', '审计', 'SQL', '管道'],
    personaEn: 'You are a data analyst who audits tables for completeness, uniqueness, and timeliness with SQL checks.',
    personaZh: '你是数据分析师，能用 SQL 检查表的完整性、唯一性与时效。',
    objectiveEn: 'From table/schema context, propose data quality checks, expected thresholds, and remediation.',
    objectiveZh: '基于表/字段背景，提出质量检查、阈值与修复建议。',
    audienceEn: 'Data engineering and analytics.',
    audienceZh: '数据工程与分析。',
    outputFormatEn: 'Markdown: scope → checks → findings → severity → fixes.',
    outputFormatZh: 'Markdown：范围 → 检查 → 发现 → 严重度 → 修复。',
    vars: [
      { name: 'table', descriptionEn: 'Table and grain', descriptionZh: '表与粒度', exampleEn: 'fct_subscriptions daily by tenant', exampleZh: 'fct_subscriptions 按租户按日', required: true },
      { name: 'issues', descriptionEn: 'Known symptoms', descriptionZh: '已知症状', exampleEn: 'Duplicate keys; late arriving events', exampleZh: '重复键；晚到事件', required: false },
    ],
    userEn: 'Table:\n{{table}}\n\nIssues:\n{{issues}}\n\nWrite DQ report outline.',
    userZh: '表：\n{{table}}\n\n问题：\n{{issues}}\n\n请写数据质量报告提纲。',
    descEn: 'DQ audit with actionable checks.',
    descZh: '可执行的数据质量审计。',
    outEn: '## Data quality audit — fct_subscriptions\n\n### Scope\nDaily grain, one row per tenant per day; feeds NRR dashboard.\n\n### Checks\n| Check | SQL idea | Threshold |\n|-------|----------|-----------|\n| Uniqueness | count(*) vs count(distinct tenant_id, day) | 0 dupes |\n| Null rates | nulls on mrr_amount | <0.1% |\n| Freshness | max(day) vs current_date | lag <= 1 day |\n\n### Findings\n- **Dupes:** 0.3% rows duplicated on 2026-03-30 due to backfill overlap.\n- **Freshness:** OK\n\n### Severity\nMedium — biases NRR for March close week.\n\n### Fixes\n- Deduplicate by `event_id`; add assert test in dbt.',
    outZh: '## 数据质量审计 — fct_subscriptions\n\n### 范围\n按租户按日一行；供 NRR 看板。\n\n### 检查\n| 检查 | SQL 思路 | 阈值 |\n|------|----------|------|\n| 唯一性 | count vs count(distinct tenant_id, day) | 0 重复 |\n| 空值率 | mrr_amount 空值 | <0.1% |\n| 时效 | max(day) vs 今天 | 延迟 ≤1 天 |\n\n### 发现\n- **重复：** 2026-03-30 因回填重叠约 0.3% 重复。\n- **时效：** 正常\n\n### 严重度\n中 — 影响 3 月关账周 NRR。\n\n### 修复\n- 按 `event_id` 去重；dbt 增加断言测试。',
  }),
  build({
    category: 'individual-contributor/data-analyst',
    slug: 'ab_test_report',
    mcp: 'da_ab_test_report',
    name: 'A/B Test Result Report',
    nameZh: 'A/B 实验结果报告',
    tags: ['A-B-test', 'experiment', 'statistics', 'analytics', 'product'],
    tagsZh: ['AB测试', '实验', '统计', '分析', '产品'],
    personaEn: 'You are a data analyst who reports experiments with methodology, guardrails, and decision guidance.',
    personaZh: '你是数据分析师，能撰写含方法、护栏与决策建议的实验报告。',
    objectiveEn: 'From experiment setup and metrics, produce an A/B report with lift, confidence, and caveats.',
    objectiveZh: '基于实验设置与指标，输出含提升、置信区间与注意点的报告。',
    audienceEn: 'PM and leadership.',
    audienceZh: '产品与管理层。',
    outputFormatEn: 'Markdown: hypothesis → design → results → segments → recommendation.',
    outputFormatZh: 'Markdown：假设 → 设计 → 结果 → 细分 → 建议。',
    vars: [
      { name: 'experiment', descriptionEn: 'Name, duration, variants', descriptionZh: '名称、周期、版本', exampleEn: 'Checkout CTA copy test, 14 days, 50/50', exampleZh: '结账 CTA 文案，14 天，50/50', required: true },
      { name: 'metrics', descriptionEn: 'Primary and guardrail metrics', descriptionZh: '主指标与护栏指标', exampleEn: 'Primary: purchase rate; Guardrail: refund rate', exampleZh: '主：购买率；护栏：退款率', required: true },
    ],
    userEn: 'Experiment:\n{{experiment}}\n\nMetrics:\n{{metrics}}\n\nWrite report.',
    userZh: '实验：\n{{experiment}}\n\n指标：\n{{metrics}}\n\n请写报告。',
    descEn: 'Experiment readout with cautious interpretation.',
    descZh: '谨慎解读的实验复盘。',
    outEn: '## A/B test — Checkout CTA copy\n\n### Hypothesis\nMore specific CTA increases purchase conversion without harming refund rate.\n\n### Design\n- 14 days, 50/50, sticky assignment, ~180k eligible sessions\n\n### Results\n- **Purchase rate:** 3.82% (B) vs 3.61% (A) → **+5.8% relative lift**\n- 95% CI: [+1.1%, +10.9%] using bootstrap\n- **Refund rate:** unchanged (0.41% vs 0.40%)\n\n### Segments\n- Lift concentrated in EU mobile web (+9.2%)\n\n### Recommendation\nShip variant B; monitor refunds 7 days post-rollout.',
    outZh: '## A/B 测试 — 结账 CTA 文案\n\n### 假设\n更具体的 CTA 提升购买转化且不影响退款率。\n\n### 设计\n- 14 天，50/50，粘性分流，约 18 万合格会话\n\n### 结果\n- **购买率：** B 3.82% vs A 3.61% → **相对 +5.8%**\n- 95% CI：Bootstrap [+1.1%, +10.9%]\n- **退款率：** 持平（0.41% vs 0.40%）\n\n### 细分\n- 欧洲移动 Web 提升明显（+9.2%）\n\n### 建议\n全量 B；上线后再观察退款 7 天。',
  }),
  build({
    category: 'individual-contributor/data-analyst',
    slug: 'metric_definition_doc',
    mcp: 'da_metric_definition_doc',
    name: 'Metric Definition Document',
    nameZh: '指标定义文档',
    tags: ['metrics', 'analytics', 'definition', 'governance', 'KPI'],
    tagsZh: ['指标', '分析', '定义', '治理', 'KPI'],
    personaEn: 'You are a data analyst who writes single-source-of-truth metric definitions with formulas and edge cases.',
    personaZh: '你是数据分析师，能撰写单一事实来源的指标定义，含公式与边界。',
    objectiveEn: 'From metric name and business intent, produce a definition doc with formula, dimensions, and caveats.',
    objectiveZh: '基于指标名与业务意图，输出含公式、维度与注意点的定义文档。',
    audienceEn: 'Analytics and business users.',
    audienceZh: '分析与业务用户。',
    outputFormatEn: 'Markdown: definition → formula → inclusion/exclusion → dimensions → caveats.',
    outputFormatZh: 'Markdown：定义 → 公式 → 纳入/排除 → 维度 → 注意点。',
    vars: [
      { name: 'metric', descriptionEn: 'Metric to define', descriptionZh: '要定义的指标', exampleEn: 'Net Revenue Retention (NRR)', exampleZh: '净收入留存（NRR）', required: true },
      { name: 'intent', descriptionEn: 'Business question it answers', descriptionZh: '回答的业务问题', exampleEn: 'Are existing customers growing spend year over year?', exampleZh: '存量客户年度支出是否增长？', required: true },
    ],
    userEn: 'Metric:\n{{metric}}\n\nIntent:\n{{intent}}\n\nWrite definition doc.',
    userZh: '指标：\n{{metric}}\n\n意图：\n{{intent}}\n\n请写定义文档。',
    descEn: 'Canonical metric definition for the org.',
    descZh: '组织级指标口径文档。',
    outEn: '## Metric definition — Net Revenue Retention (NRR)\n\n### Definition\nRevenue retained and expanded from a baseline cohort of customers over a 12-month window, expressed as a percentage of starting revenue.\n\n### Formula\nNRR = (Starting MRR + Expansion - Contraction - Churn) / Starting MRR\n\n### Inclusion\n- Customers active at cohort start date\n- Recognized subscription MRR only (excludes one-time fees)\n\n### Exclusion\n- Test/demo tenants\n- MRR < $50 (noise threshold)\n\n### Dimensions\n- Segment, region, product module\n\n### Caveats\n- Late corrections can restate historical MRR — use locked close snapshots for board reporting.',
    outZh: '## 指标定义 — 净收入留存（NRR）\n\n### 定义\n在 12 个月窗口内，从基线客户群保留并扩展的收入，占起始收入百分比。\n\n### 公式\nNRR = (起始 MRR + 扩展 - 收缩 - 流失) / 起始 MRR\n\n### 纳入\n- 基线日活跃客户\n- 仅订阅 MRR（不含一次性费用）\n\n### 排除\n- 测试/演示租户\n- MRR < 50 美元（噪声阈值）\n\n### 维度\n- 细分、区域、产品模块\n\n### 注意\n- 迟到更正会重述历史 MRR — 董事会报表使用锁定关账快照。',
  }),

  build({
    category: 'individual-contributor/data-scientist',
    slug: 'model_evaluation_report',
    mcp: 'ds_model_evaluation_report',
    name: 'Model Evaluation Report',
    nameZh: '模型评估报告',
    tags: ['ML', 'evaluation', 'data-science', 'metrics', 'testing'],
    tagsZh: ['机器学习', '评估', '数据科学', '指标', '测试'],
    personaEn: 'You are a data scientist who evaluates models with calibration, fairness notes, and deployment risks.',
    personaZh: '你是数据科学家，能评估模型：校准、公平性提示与上线风险。',
    objectiveEn: 'From task type and metrics, produce an evaluation report with splits, baselines, and go/no-go.',
    objectiveZh: '基于任务类型与指标，输出含划分、基线与上线建议的评估报告。',
    audienceEn: 'ML engineers and product.',
    audienceZh: '机器学习工程与产品。',
    outputFormatEn: 'Markdown: task → data → metrics → error analysis → recommendation.',
    outputFormatZh: 'Markdown：任务 → 数据 → 指标 → 误差分析 → 建议。',
    vars: [
      { name: 'task', descriptionEn: 'Prediction task', descriptionZh: '预测任务', exampleEn: 'Binary churn in 30 days', exampleZh: '30 天内二分类流失', required: true },
      { name: 'results', descriptionEn: 'Key metric values', descriptionZh: '关键指标值', exampleEn: 'PR-AUC 0.81 vs 0.78 baseline; ECE 0.04', exampleZh: 'PR-AUC 0.81 vs 基线 0.78；ECE 0.04', required: true },
    ],
    userEn: 'Task:\n{{task}}\n\nResults:\n{{results}}\n\nWrite evaluation report.',
    userZh: '任务：\n{{task}}\n\n结果：\n{{results}}\n\n请写评估报告。',
    descEn: 'Model evaluation summary for release review.',
    descZh: '供发布评审的模型评估摘要。',
    outEn: '## Model evaluation — 30-day churn classifier (v3)\n\n### Task\nPredict probability of churn for paying SMB customers.\n\n### Data\n- Train/val/test time-based split; test covers last 60 days.\n\n### Metrics\n- PR-AUC **0.81** vs logistic baseline **0.78**\n- Calibration (ECE) **0.04** after isotonic calibration\n- Lift@10%: 2.9x vs random\n\n### Error analysis\n- Underperforms on customers with <90d tenure — recommend separate model or feature flags.\n\n### Recommendation\n**Go** with shadow mode for 14 days; monitor calibration drift weekly.',
    outZh: '## 模型评估 — 30 天流失分类 v3\n\n### 任务\n预测付费 SMB 客户流失概率。\n\n### 数据\n- 按时间划分训练/验证/测试；测试覆盖近 60 天。\n\n### 指标\n- PR-AUC **0.81** vs 逻辑回归 **0.78**\n- 等距校准后 ECE **0.04**\n- Top10% 提升倍数 2.9x\n\n### 误差分析\n- 在 tenure<90 天客户上偏弱 — 建议分模型或特征开关。\n\n### 建议\n**可上**，先影子模式 14 天；每周监控校准漂移。',
  }),
  build({
    category: 'individual-contributor/data-scientist',
    slug: 'feature_engineering_doc',
    mcp: 'ds_feature_engineering_doc',
    name: 'Feature Engineering Documentation',
    nameZh: '特征工程文档',
    tags: ['features', 'ML', 'data-science', 'pipeline', 'documentation'],
    tagsZh: ['特征', '机器学习', '数据科学', '管道', '文档'],
    personaEn: 'You are a data scientist who documents features with definitions, freshness, and leakage checks.',
    personaZh: '你是数据科学家，能记录特征定义、时效与泄漏检查。',
    objectiveEn: 'From model context, document feature list, computation, and monitoring hooks.',
    objectiveZh: '基于模型背景，记录特征清单、计算方式与监控挂钩。',
    audienceEn: 'ML platform and reviewers.',
    audienceZh: 'ML 平台与评审者。',
    outputFormatEn: 'Markdown: feature table → computation → leakage → monitoring.',
    outputFormatZh: 'Markdown：特征表 → 计算 → 泄漏 → 监控。',
    vars: [
      { name: 'model', descriptionEn: 'Model name', descriptionZh: '模型名称', exampleEn: 'Churn v3', exampleZh: '流失 v3', required: true },
      { name: 'features', descriptionEn: 'Feature names and rough meaning', descriptionZh: '特征名与含义', exampleEn: 'days_since_login, support_tickets_30d', exampleZh: 'days_since_login, support_tickets_30d', required: true },
    ],
    userEn: 'Model:\n{{model}}\n\nFeatures:\n{{features}}\n\nWrite feature doc.',
    userZh: '模型：\n{{model}}\n\n特征：\n{{features}}\n\n请写特征文档。',
    descEn: 'Feature catalog for ML governance.',
    descZh: '用于 ML 治理的特征目录。',
    outEn: '## Feature documentation — Churn v3\n\n| Feature | Definition | Freshness | Leakage check |\n|---------|------------|-----------|---------------|\n| days_since_login | days since last successful login event | daily batch | point-in-time join at prediction time |\n| support_tickets_30d | count of tickets opened in last 30d | daily | exclude tickets opened after label window |\n| mrr_band | bucketed MRR tier at T-1 | daily | no future MRR |\n\n### Monitoring\n- Track population drift (PSI) weekly; alert PSI >0.2\n- Null rate spikes >3σ',
    outZh: '## 特征文档 — 流失 v3\n\n| 特征 | 定义 | 时效 | 泄漏检查 |\n|------|------|------|----------|\n| days_since_login | 距上次成功登录天数 | 日批 | 预测时点快照 |\n| support_tickets_30d | 近 30 天工单数 | 日批 | 排除标签窗口后工单 |\n| mrr_band | T-1 的 MRR 分桶 | 日批 | 不含未来 MRR |\n\n### 监控\n- 周度 PSI；>0.2 告警\n- 空值率超 3σ 告警',
  }),
  build({
    category: 'individual-contributor/data-scientist',
    slug: 'ml_project_proposal',
    mcp: 'ds_ml_project_proposal',
    name: 'ML Project Proposal',
    nameZh: '机器学习项目提案',
    tags: ['ML', 'proposal', 'data-science', 'ROI', 'planning'],
    tagsZh: ['机器学习', '提案', '数据科学', 'ROI', '规划'],
    personaEn: 'You are a data scientist who proposes ML projects with baselines, data readiness, and success metrics.',
    personaZh: '你是数据科学家，能提出含基线、数据准备度与成功指标的 ML 项目。',
    objectiveEn: 'From business problem, draft ML proposal with scope, milestones, and risks.',
    objectiveZh: '基于业务问题，撰写含范围、里程碑与风险的 ML 提案。',
    audienceEn: 'Product and engineering leadership.',
    audienceZh: '产品与工程管理层。',
    outputFormatEn: 'Markdown: problem → approach → data → milestones → risks → success metrics.',
    outputFormatZh: 'Markdown：问题 → 方法 → 数据 → 里程碑 → 风险 → 成功指标。',
    vars: [
      { name: 'problem', descriptionEn: 'Business problem', descriptionZh: '业务问题', exampleEn: 'Reduce false positives in fraud alerts', exampleZh: '降低欺诈告警误报', required: true },
      { name: 'data', descriptionEn: 'Data availability', descriptionZh: '数据可用性', exampleEn: '2 years labeled alerts; imbalanced 1:40', exampleZh: '2 年标注告警；不平衡 1:40', required: true },
    ],
    userEn: 'Problem:\n{{problem}}\n\nData:\n{{data}}\n\nWrite proposal.',
    userZh: '问题：\n{{problem}}\n\n数据：\n{{data}}\n\n请写提案。',
    descEn: 'ML initiative one-pager.',
    descZh: 'ML 项目一页纸。',
    outEn: '## ML proposal — Fraud alert precision uplift\n\n### Problem\nHigh false positive rate exhausts analysts and delays true cases.\n\n### Approach\n- Gradient boosting with calibrated probabilities; start as shadow scorer alongside rules.\n\n### Data readiness\n- 24 months labels; known selection bias on appealed cases — plan bias audit.\n\n### Milestones\n- M1 (4w): baseline + leakage review\n- M2 (8w): v1 model + offline eval\n- M3 (12w): shadow deployment + monitoring\n\n### Risks\n- Concept drift on new payment methods\n\n### Success metrics\n- Precision@20% review volume +15 pts; maintain recall ≥0.9',
    outZh: '## ML 提案 — 提升欺诈告警精度\n\n### 问题\n误报高导致分析师疲劳并延误真案。\n\n### 方法\n- 梯度提升 + 概率校准；先与规则并行影子评分。\n\n### 数据\n- 24 个月标签；申诉样本有选择偏差 — 需偏差审计。\n\n### 里程碑\n- M1（4 周）：基线 + 泄漏审查\n- M2（8 周）：v1 模型 + 离线评估\n- M3（12 周）：影子上线 + 监控\n\n### 风险\n- 新支付方式概念漂移\n\n### 成功指标\n- 在 20% 审核量下精度 +15 点；召回 ≥0.9',
  }),
  build({
    category: 'individual-contributor/data-scientist',
    slug: 'data_pipeline_design',
    mcp: 'ds_data_pipeline_design',
    name: 'Data Pipeline Design Doc',
    nameZh: '数据管道设计文档',
    tags: ['pipeline', 'ETL', 'data-science', 'engineering', 'orchestration'],
    tagsZh: ['管道', 'ETL', '数据科学', '工程', '编排'],
    personaEn: 'You are a data scientist who designs batch/stream pipelines with SLAs, idempotency, and quality gates.',
    personaZh: '你是数据科学家，能设计含 SLA、幂等与质量门的批/流管道。',
    objectiveEn: 'From source systems and outputs, draft pipeline design with DAG, contracts, and monitoring.',
    objectiveZh: '基于源系统与产出，撰写含 DAG、契约与监控的管道设计。',
    audienceEn: 'Data engineering partners.',
    audienceZh: '数据工程伙伴。',
    outputFormatEn: 'Markdown: sources → DAG → schemas → SLAs → quality checks → failure modes.',
    outputFormatZh: 'Markdown：来源 → DAG → 模式 → SLA → 质量检查 → 故障模式。',
    vars: [
      { name: 'sources', descriptionEn: 'Sources', descriptionZh: '数据源', exampleEn: 'Kafka events, Postgres contracts', exampleZh: 'Kafka 事件，Postgres 合同', required: true },
      { name: 'outputs', descriptionEn: 'Outputs/consumers', descriptionZh: '产出/消费者', exampleEn: 'Feature store for churn model', exampleZh: '流失模型特征库', required: true },
    ],
    userEn: 'Sources:\n{{sources}}\n\nOutputs:\n{{outputs}}\n\nWrite pipeline design.',
    userZh: '来源：\n{{sources}}\n\n产出：\n{{outputs}}\n\n请写管道设计。',
    descEn: 'Pipeline design for ML feature freshness.',
    descZh: '面向 ML 特征时效的管道设计。',
    outEn: '## Pipeline design — Churn feature daily batch\n\n### Sources\n- `billing.subscription_events` (Postgres CDC)\n- `app.login_events` (Kafka topic `auth.login`)\n\n### DAG\n1. ingest → 2. normalize → 3. join @ prediction_time snapshot → 4. publish features\n\n### Schema contract\n- Primary key: `tenant_id, as_of_date`\n- All features nullable-safe defaults documented\n\n### SLAs\n- Complete by 06:00 UTC; 99.5% on-time monthly\n\n### Quality checks\n- Row count within 5% of prior day\n- Duplicate key rate = 0\n\n### Failure modes\n- Late data: re-run with extended lookback window + alert owner',
    outZh: '## 管道设计 — 流失特征日批\n\n### 来源\n- `billing.subscription_events`（Postgres CDC）\n- `app.login_events`（Kafka `auth.login`）\n\n### DAG\n1. 摄取 → 2. 规范化 → 3. 按预测时点快照关联 → 4. 发布特征\n\n### 模式契约\n- 主键：`tenant_id, as_of_date`\n- 特征空值默认值文档化\n\n### SLA\n- 06:00 UTC 前完成；月 99.5% 准时\n\n### 质量\n- 行数较前日 ±5%\n- 重复键率 = 0\n\n### 故障\n- 晚到数据：扩大回看重跑 + 告警负责人',
  }),

  build({
    category: 'individual-contributor/designer',
    slug: 'design_system_spec',
    mcp: 'dsg_design_system_spec',
    name: 'Design System Component Spec',
    nameZh: '设计系统组件规格',
    tags: ['design-system', 'UI', 'components', 'accessibility', 'design'],
    tagsZh: ['设计系统', '界面', '组件', '无障碍', '设计'],
    personaEn: 'You are a product designer who specifies components with states, tokens, and accessibility requirements.',
    personaZh: '你是产品设计师，能定义组件状态、设计令牌与无障碍要求。',
    objectiveEn: 'From component name and use cases, write a design spec with anatomy, variants, and a11y.',
    objectiveZh: '基于组件名与用例，撰写含结构、变体与无障碍的规格。',
    audienceEn: 'Engineering and design systems team.',
    audienceZh: '工程与设计系统团队。',
    outputFormatEn: 'Markdown: overview → anatomy → variants → tokens → a11y → content.',
    outputFormatZh: 'Markdown：概述 → 结构 → 变体 → 令牌 → 无障碍 → 文案。',
    vars: [
      { name: 'component', descriptionEn: 'Component name', descriptionZh: '组件名', exampleEn: 'DataTable toolbar', exampleZh: '数据表工具栏', required: true },
      { name: 'use_cases', descriptionEn: 'Primary use cases', descriptionZh: '主要场景', exampleEn: 'Filter, export, bulk actions', exampleZh: '筛选、导出、批量操作', required: true },
    ],
    userEn: 'Component:\n{{component}}\n\nUse cases:\n{{use_cases}}\n\nWrite spec.',
    userZh: '组件：\n{{component}}\n\n场景：\n{{use_cases}}\n\n请写规格。',
    descEn: 'Component spec for design system alignment.',
    descZh: '对齐设计系统的组件规格。',
    outEn: '## Component spec — DataTable toolbar\n\n### Overview\nToolbar for dense enterprise tables: filtering, export, and bulk actions.\n\n### Anatomy\n- Left: filter chips + "More filters" entry\n- Right: secondary "Export" + primary bulk action\n\n### Variants\n- **Default / Compact** (height 40px vs 32px)\n- **Empty selection** disables destructive bulk actions\n\n### Tokens\n- Spacing: `space-2` between chips; `radius-md` on buttons\n- Color: use `text-secondary` for labels; meet 4.5:1 contrast\n\n### Accessibility\n- All icon buttons require `aria-label`\n- Focus order follows visual left-to-right\n- Bulk menu uses roving tabindex pattern\n\n### Content\n- Export states: idle / running / success / error with retry',
    outZh: '## 组件规格 — 数据表工具栏\n\n### 概述\n面向密集企业表：筛选、导出、批量操作。\n\n### 结构\n- 左：筛选标签 +「更多筛选」入口\n- 右：次要「导出」+ 主要批量操作\n\n### 变体\n- **默认/紧凑**（高 40px / 32px）\n- **未选行** 禁用破坏性批量操作\n\n### 令牌\n- 间距：标签间 `space-2`；按钮 `radius-md`\n- 颜色：`text-secondary`；对比度 ≥4.5:1\n\n### 无障碍\n- 图标按钮需 `aria-label`\n- 焦点顺序与视觉一致\n- 批量菜单用 roving tabindex\n\n### 文案\n- 导出：空闲/进行中/成功/失败可重试',
  }),
  build({
    category: 'individual-contributor/designer',
    slug: 'usability_test_plan',
    mcp: 'dsg_usability_test_plan',
    name: 'Usability Test Plan',
    nameZh: '可用性测试计划',
    tags: ['UX', 'research', 'usability', 'testing', 'design'],
    tagsZh: ['体验', '研究', '可用性', '测试', '设计'],
    personaEn: 'You are a UX designer who plans usability tests with tasks, success criteria, and unbiased scripts.',
    personaZh: '你是体验设计师，能规划含任务、成功标准与中立脚本的可用性测试。',
    objectiveEn: 'From product area and hypotheses, produce a usability test plan with screener, tasks, and metrics.',
    objectiveZh: '基于产品区域与假设，输出含筛选、任务与指标的测试计划。',
    audienceEn: 'Research ops and PM.',
    audienceZh: '研究运营与 PM。',
    outputFormatEn: 'Markdown: goals → participants → script → tasks → metrics → ethics.',
    outputFormatZh: 'Markdown：目标 → 参与者 → 脚本 → 任务 → 指标 → 伦理。',
    vars: [
      { name: 'area', descriptionEn: 'Feature or flow', descriptionZh: '功能或流程', exampleEn: 'New onboarding checklist for admins', exampleZh: '管理员新入职清单', required: true },
      { name: 'hypotheses', descriptionEn: 'Hypotheses to test', descriptionZh: '待验证假设', exampleEn: 'Users miss advanced settings; language unclear', exampleZh: '用户找不到高级设置；文案不清', required: true },
    ],
    userEn: 'Area:\n{{area}}\n\nHypotheses:\n{{hypotheses}}\n\nWrite test plan.',
    userZh: '范围：\n{{area}}\n\n假设：\n{{hypotheses}}\n\n请写测试计划。',
    descEn: 'Moderated usability test plan.',
    descZh: '主持式可用性测试计划。',
    outEn: '## Usability test plan — Admin onboarding checklist\n\n### Goals\n- Validate discoverability of advanced settings\n- Measure time-to-complete for core setup tasks\n\n### Participants\n- n=8 admins from 50–500 employee companies; mix first-time vs returning\n\n### Script (neutral)\n- Intro: think-aloud encouraged; no leading hints\n- Consent + recording notice\n\n### Tasks\n1. Add first teammate and assign roles (success: correct RBAC)\n2. Enable SSO (success: finds advanced settings <90s)\n3. Import users via CSV (success: resolves error state)\n\n### Metrics\n- Task success rate, time on task, SUS survey post-session\n\n### Ethics\n- De-identify recordings; store 90 days',
    outZh: '## 可用性测试计划 — 管理员入职清单\n\n### 目标\n- 验证高级设置可发现性\n- 测量核心配置完成时间\n\n### 参与者\n- n=8，50–500 人公司管理员；新手/回访混合\n\n### 脚本（中立）\n- 鼓励出声思考；不暗示答案\n- 同意与录制说明\n\n### 任务\n1. 添加首位成员并分配角色（成功：RBAC 正确）\n2. 开启 SSO（成功：90 秒内找到高级设置）\n3. CSV 导入用户（成功：处理错误态）\n\n### 指标\n- 任务成功率、耗时、会后 SUS\n\n### 伦理\n- 录制去标识；保存 90 天',
  }),
  build({
    category: 'individual-contributor/designer',
    slug: 'design_handoff_doc',
    mcp: 'dsg_design_handoff_doc',
    name: 'Design Handoff Document',
    nameZh: '设计交付文档',
    tags: ['handoff', 'design', 'engineering', 'specs', 'Figma'],
    tagsZh: ['交付', '设计', '工程', '规格', 'Figma'],
    personaEn: 'You are a product designer who hands off designs with redlines, edge cases, and interaction notes.',
    personaZh: '你是产品设计师，能交付含标注、边界与交互说明的设计稿。',
    objectiveEn: 'From feature summary, produce a handoff checklist for engineering with assets and acceptance notes.',
    objectiveZh: '基于功能摘要，输出给工程的交付清单：资产与验收说明。',
    audienceEn: 'Frontend engineers.',
    audienceZh: '前端工程师。',
    outputFormatEn: 'Markdown: scope → screens → interactions → states → assets → open questions.',
    outputFormatZh: 'Markdown：范围 → 页面 → 交互 → 状态 → 资产 → 开放问题。',
    vars: [
      { name: 'feature', descriptionEn: 'Feature name', descriptionZh: '功能名', exampleEn: 'Bulk role assignment', exampleZh: '批量角色分配', required: true },
      { name: 'figma', descriptionEn: 'Figma link or frame IDs', descriptionZh: 'Figma 链接或画板', exampleEn: 'https://figma.com/file/abc (frames 12–18)', exampleZh: 'https://figma.com/file/abc（画板 12–18）', required: false },
    ],
    userEn: 'Feature:\n{{feature}}\n\nFigma:\n{{figma}}\n\nWrite handoff doc.',
    userZh: '功能：\n{{feature}}\n\nFigma：\n{{figma}}\n\n请写交付文档。',
    descEn: 'Engineering-ready design handoff.',
    descZh: '面向工程的设计交付。',
    outEn: '## Handoff — Bulk role assignment\n\n### Scope\nAdmin can assign a role to up to 200 users via table selection + modal confirm.\n\n### Screens\n- Table selection state, sticky toolbar, modal summary, progress + success/error\n\n### Interactions\n- Shift-click range select; Cmd/Ctrl multi-select\n- Confirm modal lists impacted users (first 10 + "and N more")\n\n### States\n- Loading: disable confirm; show spinner in toolbar\n- Partial failure: row-level error with retry\n\n### Assets\n- Icons exported as SVG from Figma `icons/bulk`\n- Motion: 200ms ease on modal\n\n### Open questions\n- Should we support undo within 10s? (PM decision pending)',
    outZh: '## 交付 — 批量角色分配\n\n### 范围\n管理员可在表中多选最多 200 人并通过弹窗确认分配角色。\n\n### 页面\n- 多选态、粘性工具栏、确认弹窗、进度与成功/失败\n\n### 交互\n- Shift 连续选；Cmd/Ctrl 多选\n- 确认弹窗列出受影响用户（前 10 +「另有 N 人」）\n\n### 状态\n- 加载：禁用确认；工具栏转圈\n- 部分失败：行级错误可重试\n\n### 资产\n- 图标自 Figma `icons/bulk` 导出 SVG\n- 动效：弹窗 200ms ease\n\n### 开放问题\n- 是否支持 10 秒内撤销？（待 PM）',
  }),
  build({
    category: 'individual-contributor/designer',
    slug: 'accessibility_audit',
    mcp: 'dsg_accessibility_audit',
    name: 'Accessibility Audit Report',
    nameZh: '无障碍审计报告',
    tags: ['a11y', 'WCAG', 'design', 'audit', 'inclusive'],
    tagsZh: ['无障碍', 'WCAG', '设计', '审计', '包容'],
    personaEn: 'You are a UX designer who audits interfaces against WCAG 2.2 patterns with prioritized fixes.',
    personaZh: '你是体验设计师，能按 WCAG 2.2 模式审计界面并排序修复项。',
    objectiveEn: 'From page/flow notes, produce an accessibility audit with severity and remediation.',
    objectiveZh: '基于页面/流程记录，输出含严重度与修复建议的无障碍审计。',
    audienceEn: 'Engineering and compliance.',
    audienceZh: '工程与合规。',
    outputFormatEn: 'Markdown: scope → issues table → WCAG mapping → retest plan.',
    outputFormatZh: 'Markdown：范围 → 问题表 → WCAG 映射 → 复测计划。',
    vars: [
      { name: 'scope', descriptionEn: 'URLs or flows', descriptionZh: 'URL 或流程', exampleEn: 'Checkout + Settings → SSO', exampleZh: '结账 + 设置→SSO', required: true },
      { name: 'findings', descriptionEn: 'Observed issues', descriptionZh: '观察到的问题', exampleEn: 'Low contrast on secondary buttons; missing labels on icon-only', exampleZh: '次要按钮对比度不足；纯图标缺标签', required: true },
    ],
    userEn: 'Scope:\n{{scope}}\n\nFindings:\n{{findings}}\n\nWrite audit.',
    userZh: '范围：\n{{scope}}\n\n发现：\n{{findings}}\n\n请写审计。',
    descEn: 'WCAG-oriented audit summary.',
    descZh: '面向 WCAG 的审计摘要。',
    outEn: '## Accessibility audit — Checkout + SSO settings\n\n### Scope\nWeb responsive; tested keyboard + VoiceOver (Safari).\n\n### Issues\n| ID | Description | WCAG | Severity |\n|----|-------------|------|----------|\n| A1 | Secondary button text contrast 3.8:1 | 1.4.3 | High |\n| A2 | Icon-only export missing accessible name | 4.1.2 | High |\n| A3 | Focus outline removed on links | 2.4.7 | Medium |\n\n### Remediation\n- A1: darken `text-secondary` token to 4.6:1 on white\n- A2: add `aria-label` + tooltip for export icon\n- A3: restore `:focus-visible` ring 2px\n\n### Retest\n- Re-run after merge; attach screenshots + axe scan',
    outZh: '## 无障碍审计 — 结账 + SSO 设置\n\n### 范围\nWeb 响应式；键盘 + VoiceOver（Safari）。\n\n### 问题\n| ID | 描述 | WCAG | 严重度 |\n|----|------|------|--------|\n| A1 | 次要按钮对比度 3.8:1 | 1.4.3 | 高 |\n| A2 | 纯图标导出缺可访问名称 | 4.1.2 | 高 |\n| A3 | 链接焦点环被移除 | 2.4.7 | 中 |\n\n### 修复\n- A1：加深 `text-secondary` 至白底 4.6:1\n- A2：为导出图标加 `aria-label` + 提示\n- A3：恢复 `:focus-visible` 2px 环\n\n### 复测\n- 合并后重测；附截图与 axe 扫描',
  }),
];
