#!/usr/bin/env node
/**
 * Generate docs/SKILL_INDEX.md — one row per skill id (locale-per-file pairs)
 * Run: npm run build-index
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const skillsDir = join(rootDir, 'skills');
const outDir = join(rootDir, 'docs');
const outFile = join(outDir, 'SKILL_INDEX.md');

function findLocaleSkillFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory() && !entry.startsWith('.')) {
      files.push(...findLocaleSkillFiles(fullPath));
    } else if (entry.endsWith('.zh.skill.md')) {
      files.push(fullPath);
    }
  }
  return files.sort((a, b) => relative(rootDir, a).localeCompare(relative(rootDir, b)));
}

const skillPaths = findLocaleSkillFiles(skillsDir);
const lines = [
  '<!-- Generated by npm run build-index. Do not edit by hand. · 由脚本生成，请勿手改。 -->',
  '',
  '# Skill index · 技能索引',
  '',
  '**中文：** 下列为每个技能 `id` 一行（`.zh.skill.md` + `.en.skill.md` 配对）。',
  '',
  '**English:** One row per skill `id` (paired `.zh.skill.md` + `.en.skill.md`).',
  '',
  '| id · 标识 | zh path | en path | Title (zh) · 名称 |',
  '|-----------|---------|---------|-------------------|',
];

const byId = new Map();

for (const abs of skillPaths) {
  const rel = relative(rootDir, abs).replace(/\\/g, '/');
  const raw = readFileSync(abs, 'utf8');
  let id = rel;
  let nameZh = rel;
  try {
    const { data } = matter(raw);
    if (data.id) id = data.id;
    if (data.name) nameZh = String(data.name).trim();
  } catch {
    // keep defaults
  }
  const enRel = rel.replace(/\.zh\.skill\.md$/, '.en.skill.md');
  byId.set(id, { zh: rel, en: enRel, nameZh });
}

for (const [id, row] of [...byId.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  const safeName = row.nameZh.replace(/\|/g, '\\|');
  lines.push(`| \`${id}\` | [\`${row.zh}\`](../${row.zh}) | [\`${row.en}\`](../${row.en}) | ${safeName} |`);
}

lines.push('');
lines.push(`**Total · 总计:** ${byId.size} skills (${byId.size * 2} files)`);
lines.push('');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`Wrote ${relative(rootDir, outFile)} (${byId.size} skills)`);
