#!/usr/bin/env node
/**
 * Generate docs/SKILL_INDEX.md — flat list of all .skill.md files with titles from frontmatter.
 * Run: npm run build-index
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const skillsDir = join(rootDir, 'skills');
const outDir = join(rootDir, 'docs');
const outFile = join(outDir, 'SKILL_INDEX.md');

function findSkillFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory() && !entry.startsWith('.')) {
      files.push(...findSkillFiles(fullPath));
    } else if (entry.endsWith('.skill.md')) {
      files.push(fullPath);
    }
  }
  return files.sort((a, b) => relative(rootDir, a).localeCompare(relative(rootDir, b)));
}

function titleFromFrontmatter(raw, relPath) {
  try {
    const { data } = matter(raw);
    if (data.name && String(data.name).trim()) return String(data.name).trim();
    if (data.id && String(data.id).trim()) return String(data.id).trim();
  } catch {
    // fall through
  }
  return relPath;
}

const skillPaths = findSkillFiles(skillsDir);
const lines = [
  '<!-- Generated by npm run build-index. Do not edit by hand. · 由脚本生成，请勿手改。 -->',
  '',
  '# Skill index · 技能索引',
  '',
  '**中文：** 下列为全部 `.skill.md` 的路径列表（按路径排序）。人类可读的目录与说明见 [README.md](../README.md)、[SKILL_SCHEMA.md](../SKILL_SCHEMA.md)。',
  '',
  '**English:** Auto-generated list of all `.skill.md` files (sorted by path). For the human-friendly directory, see [README.md](../README.md) and [SKILL_SCHEMA.md](../SKILL_SCHEMA.md).',
  '',
  '| Path · 路径 | Title · 名称 |',
  '|-------------|--------------|',
];

for (const abs of skillPaths) {
  const rel = relative(rootDir, abs).replace(/\\/g, '/');
  let title = rel;
  try {
    const raw = readFileSync(abs, 'utf8');
    title = titleFromFrontmatter(raw, rel);
  } catch {
    // keep path as title
  }
  const safeTitle = title.replace(/\|/g, '\\|');
  lines.push(`| [\`${rel}\`](../${rel}) | ${safeTitle} |`);
}

lines.push('');
lines.push(`**Total · 总计:** ${skillPaths.length} skills`);
lines.push('');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`Wrote ${relative(rootDir, outFile)} (${skillPaths.length} skills)`);
