#!/usr/bin/env node
/**
 * 1) WRITE_MIRROR=1 → write docs/wiki-mirror/*.md (works with GITHUB_TOKEN commit in Actions; no PAT).
 * 2) PROJECTS_WIKI_PAT → git push to GitHub Wiki + Project v2 draft items (needs PAT; GITHUB_TOKEN cannot push wiki).
 * Env: GITHUB_REPOSITORY=owner/repo, PROJECT_OWNER (default owner), PROJECT_NUMBER (optional).
 * DRY_RUN=1 — no writes / no git / no GraphQL mutations.
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdtempSync, rmSync, mkdirSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { execSync } from 'child_process';

const pat = (process.env.PROJECTS_WIKI_PAT || '').trim();
const repoFull = process.env.GITHUB_REPOSITORY || '';
const [owner, repo] = repoFull.includes('/') ? repoFull.split('/') : ['', ''];
const projectOwner = process.env.PROJECT_OWNER || owner;
const projectNumber = parseInt(process.env.PROJECT_NUMBER || '0', 10) || 0;
const dryRun = process.env.DRY_RUN === '1';
const writeMirror = process.env.WRITE_MIRROR === '1';

function log(...a) {
  console.log('[sync-github]', ...a);
}

function blob(pathInRepo) {
  return `https://github.com/${owner}/${repo}/blob/master/${pathInRepo}`;
}

function countSkillsByCategory() {
  const skillsDir = join(process.cwd(), 'skills');
  const counts = {};
  let total = 0;
  for (const cat of readdirSync(skillsDir)) {
    const p = join(skillsDir, cat);
    if (!statSync(p).isDirectory()) continue;
    let n = 0;
    function walk(d) {
      for (const e of readdirSync(d)) {
        const fp = join(d, e);
        if (statSync(fp).isDirectory()) walk(fp);
        else if (e.endsWith('.skill.md')) n += 1;
      }
    }
    walk(p);
    counts[cat] = n;
    total += n;
  }
  return { counts, total };
}

function loadRoadmap() {
  const p = join(process.cwd(), 'data', 'roadmap.json');
  return JSON.parse(readFileSync(p, 'utf8'));
}

function renderRoadmapWiki(data) {
  const iso = new Date().toISOString();
  let md = `<!-- Auto-generated by OpenSkill GitHub Actions — do not edit by hand. 请勿手改 -->\n\n`;
  md += `# Roadmap · 路线图\n\n`;
  md += `_Last sync · 最后同步: ${iso}_\n\n`;
  md += `**Source · 数据源:** [data/roadmap.json](${blob('data/roadmap.json')})\n\n`;
  md += `## Vision · 愿景\n\n`;
  md += `**中文：** ${data.vision.zh}\n\n`;
  md += `**English:** ${data.vision.en}\n\n`;

  for (const phase of ['now', 'next', 'later']) {
    const label = { now: 'Now · 当前', next: 'Next · 下一波', later: 'Later · 后续' }[phase];
    md += `## ${label}\n\n`;
    const items = data.phases[phase] || [];
    for (const it of items) {
      md += `### \`${it.id}\` — ${it.title_zh} · ${it.title_en}\n\n`;
      md += `- **中文：** ${it.body_zh}\n`;
      md += `- **English:** ${it.body_en}\n\n`;
    }
  }
  return md;
}

/** @param {'github-wiki' | 'repo-mirror'} variant */
function renderHomeWiki(data, total, variant) {
  const iso = new Date().toISOString();
  const road = variant === 'repo-mirror'
    ? `[Roadmap · 路线图](${blob('docs/wiki-mirror/Roadmap.md')})`
    : `[Roadmap (generated) · 路线图](Roadmap)`;
  const stats = variant === 'repo-mirror'
    ? `[Skill stats · 技能统计](${blob('docs/wiki-mirror/Skill-stats.md')})`
    : `[Skill stats · 技能统计](Skill-stats)`;
  const automation = variant === 'repo-mirror'
    ? `[Automation · 说明](${blob('docs/wiki-mirror/Automation.md')})`
    : `[Automation · 说明](Automation)`;

  const mirrorNote =
    variant === 'repo-mirror'
      ? `\n**中文：** 本页为仓库内 **wiki 镜像**（\`docs/wiki-mirror/\`），无需 PAT 即可在网页阅读；与 [GitHub Wiki](https://github.com/${owner}/${repo}/wiki) 内容应在配置 PAT 后保持一致。\n\n**English:** This is the **in-repo wiki mirror** (\`docs/wiki-mirror/\`) — readable without a PAT; [GitHub Wiki](https://github.com/${owner}/${repo}/wiki) should match when PAT is configured.\n\n`
      : '\n';

  return `<!-- Auto-generated — do not edit by hand. -->\n\n` +
    `# OpenSkill · Home\n\n` +
    `_Synced · 同步时间: ${iso}_\n\n` +
    mirrorNote +
    `**中文：** 主仓库 [OpenSkill](https://github.com/${owner}/${repo}) 路线图与技能统计由 Actions 从 \`data/roadmap.json\` 与 \`skills/**\` 生成。\n\n` +
    `**English:** Roadmap and skill stats are generated by Actions from \`data/roadmap.json\` and \`skills/**\`.\n\n` +
    `## Quick links · 快速链接\n\n` +
    `- ${road}\n` +
    `- ${stats}\n` +
    `- ${automation}\n` +
    `- [README · 仓库首页](https://github.com/${owner}/${repo}#readme)\n` +
    `- [Contributing · 贡献指南](${blob('CONTRIBUTING.md')})\n` +
    `- [GitHub Projects · 项目看板](https://github.com/${owner}/${repo}/projects)\n\n` +
    `**Skills in repo · 仓库技能总数:** **${total}**\n`;
}

function renderSkillStatsWiki(counts, total) {
  const iso = new Date().toISOString();
  let md = `<!-- Auto-generated — do not edit by hand. -->\n\n# Skill stats · 技能统计\n\n`;
  md += `_Last sync · 最后同步: ${iso}_\n\n`;
  md += `| Category · 分类 | .skill.md count |\n|---|---:|\n`;
  for (const k of Object.keys(counts).sort()) {
    md += `| \`${k}/\` | ${counts[k]} |\n`;
  }
  md += `| **Total · 总计** | **${total}** |\n`;
  return md;
}

function renderAutomationWiki() {
  return `<!-- Auto-generated — do not edit by hand. -->\n\n# Automation · 自动化说明\n\n` +
    `## 无需 PAT（默认）· No PAT (default)\n\n` +
    `**中文：** 工作流把路线图与统计写入 **[\`docs/wiki-mirror/\`](${blob('docs/wiki-mirror/Home.md')})** 并 \`git push\` 到默认分支，使用 \`GITHUB_TOKEN\`。打开 [Home](${blob('docs/wiki-mirror/Home.md')}) 即可阅读。\n\n` +
    `**English:** The workflow writes pages under **[\`docs/wiki-mirror/\`](${blob('docs/wiki-mirror/Home.md')})** and pushes with \`GITHUB_TOKEN\`. Start at [Home](${blob('docs/wiki-mirror/Home.md')}).\n\n` +
    `## 可选：GitHub Wiki · Optional: GitHub Wiki\n\n` +
    `**中文：** 在仓库 **Settings → General → Wiki** 启用 Wiki。添加 Secret \`PROJECTS_WIKI_PAT\`（classic PAT 勾选 \`repo\`，或 fine-grained 含 **Contents** 读写含 wiki）。Actions 会额外 \`git push\` 到 \`.wiki\` 远程。\n\n` +
    `**English:** Enable **Wiki** in **Settings → General**. Add secret \`PROJECTS_WIKI_PAT\` (\`repo\` scope or fine-grained with wiki/content access). The workflow will also push to the \`.wiki\` remote.\n\n` +
    `## 可选：GitHub Projects · Optional: Projects\n\n` +
    `**中文：** [Projects 列表](https://github.com/${owner}/${repo}/projects) 若为 **0**，请先在组织或用户下 **New project** 建一个 Project（表格或看板均可），从浏览器地址栏或项目 **Settings** 查看 **Project number**，在仓库 **Settings → Secrets and variables → Actions → Variables** 添加 \`PROJECT_NUMBER\`（整数）。再配置 \`PROJECTS_WIKI_PAT\`（需含 **project** 权限）。工作流会为 \`data/roadmap.json\` 中尚未存在的条目创建 **草稿**（标题形如 \`[Roadmap:now:skill-coverage]\`）。\n\n` +
    `**English:** If [Projects](https://github.com/${owner}/${repo}/projects) is empty, create **New project**, read its **number**, set variable \`PROJECT_NUMBER\`, and provide \`PROJECTS_WIKI_PAT\` with **project** scope. Draft items are created per roadmap entry.\n\n` +
    `**Workflow file · 工作流文件:** [\`sync-github-project-wiki.yml\`](${blob('.github/workflows/sync-github-project-wiki.yml')})\n`;
}

async function graphql(query, variables = {}) {
  if (!pat) throw new Error('graphql called without PROJECTS_WIKI_PAT');
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${pat}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${JSON.stringify(json)}`);
  if (json.errors?.length) throw new Error(JSON.stringify(json.errors));
  return json.data;
}

function markerTitle(phase, id) {
  return `[Roadmap:${phase}:${id}]`;
}

function parseProjectItems(proj) {
  const titles = new Set();
  for (const node of proj.items?.nodes || []) {
    const t = node.content?.title;
    if (t) titles.add(t);
  }
  return { projectId: proj.id, projectTitle: proj.title, existingTitles: titles };
}

async function fetchProjectAndExistingTitles() {
  const qOrganization = `
    query($login: String!, $n: Int!) {
      organization(login: $login) {
        projectV2(number: $n) {
          id
          title
          items(first: 100) {
            nodes {
              content {
                __typename
                ... on DraftIssue { title }
                ... on Issue { title }
              }
            }
          }
        }
      }
    }
  `;
  const qUser = `
    query($login: String!, $n: Int!) {
      user(login: $login) {
        projectV2(number: $n) {
          id
          title
          items(first: 100) {
            nodes {
              content {
                __typename
                ... on DraftIssue { title }
                ... on Issue { title }
              }
            }
          }
        }
      }
    }
  `;

  let proj;
  try {
    const d = await graphql(qOrganization, { login: projectOwner, n: projectNumber });
    proj = d.organization?.projectV2;
  } catch (e) {
    log('Organization project query failed:', e.message);
  }
  if (!proj) {
    try {
      const d = await graphql(qUser, { login: projectOwner, n: projectNumber });
      proj = d.user?.projectV2;
    } catch (e) {
      log('User project query failed:', e.message);
    }
  }
  if (!proj) {
    log(`No projectV2 #${projectNumber} for "${projectOwner}" — skip project sync`);
    return null;
  }
  return parseProjectItems(proj);
}

async function addDraftIssue(projectId, title, body) {
  const m = `
    mutation($pid: ID!, $title: String!, $body: String) {
      addProjectV2DraftIssue(input: { projectId: $pid, title: $title, body: $body }) {
        projectItem { id }
      }
    }
  `;
  await graphql(m, { pid: projectId, title, body });
}

function syncWikiGitPush(filesWiki) {
  if (!pat) {
    log('No PROJECTS_WIKI_PAT — skip GitHub Wiki git push (pages are in docs/wiki-mirror/)');
    return;
  }
  if (!owner || !repo) {
    log('GITHUB_REPOSITORY unset — skip Wiki push');
    return;
  }

  const tmp = mkdtempSync(join(tmpdir(), 'openskill-wiki-'));
  const remote = `https://x-access-token:${encodeURIComponent(pat)}@github.com/${owner}/${repo}.wiki.git`;

  try {
    try {
      execSync(`git clone --depth 1 "${remote}" "${tmp}"`, { stdio: 'inherit' });
    } catch {
      log('Wiki clone failed — initializing new wiki repo');
      execSync('git init', { cwd: tmp, stdio: 'inherit' });
      execSync(`git remote add origin "${remote}"`, { cwd: tmp, stdio: 'inherit' });
    }

    for (const [name, content] of Object.entries(filesWiki)) {
      writeFileSync(join(tmp, name), content, 'utf8');
    }

    execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"', { cwd: tmp });
    execSync('git config user.name "github-actions[bot]"', { cwd: tmp });
    execSync('git add -A', { cwd: tmp, stdio: 'inherit' });
    try {
      execSync(`git commit -m "chore(wiki): auto-sync from ${repoFull}"`, { cwd: tmp, stdio: 'inherit' });
    } catch {
      log('No wiki changes to commit');
      return;
    }
    if (dryRun) {
      log('DRY_RUN: skip wiki git push');
      return;
    }
    execSync('git branch -M master', { cwd: tmp, stdio: 'inherit' });
    execSync('git push -u origin master', { cwd: tmp, stdio: 'inherit' });
    log('Wiki git push OK');
  } catch (e) {
    log('Wiki git push failed:', e.message);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function writeRepoMirror(filesMirror) {
  if (!writeMirror) return;
  const dir = join(process.cwd(), 'docs', 'wiki-mirror');
  if (dryRun) {
    log('DRY_RUN: would write', Object.keys(filesMirror).length, 'files to', dir);
    return;
  }
  mkdirSync(dir, { recursive: true });
  for (const [name, content] of Object.entries(filesMirror)) {
    writeFileSync(join(dir, name), content, 'utf8');
  }
  log('Wrote docs/wiki-mirror:', Object.keys(filesMirror).join(', '));
}

async function syncProjectItems(data) {
  if (!pat) {
    log('No PROJECTS_WIKI_PAT — skip Project v2 sync');
    return;
  }
  if (!projectNumber) {
    log('PROJECT_NUMBER unset or 0 — skip Project sync (create a project and set the variable)');
    return;
  }

  let meta;
  try {
    meta = await fetchProjectAndExistingTitles();
  } catch (e) {
    log('Project GraphQL error:', e.message);
    return;
  }
  if (!meta) return;

  log(`Project: ${meta.projectTitle} (${meta.projectId})`);

  for (const phase of ['now', 'next', 'later']) {
    const items = data.phases[phase] || [];
    for (const it of items) {
      const title = markerTitle(phase, it.id);
      if (meta.existingTitles.has(title)) {
        log('Exists, skip:', title);
        continue;
      }
      const body =
        `**Phase · 阶段:** ${phase}\n\n` +
        `**中文**\n${it.body_zh}\n\n` +
        `**English**\n${it.body_en}\n\n` +
        `---\n` +
        `Source: ${blob('data/roadmap.json')}`;

      if (dryRun) {
        log('DRY_RUN would add draft:', title);
        continue;
      }
      try {
        await addDraftIssue(meta.projectId, title, body);
        log('Added draft:', title);
        meta.existingTitles.add(title);
      } catch (e) {
        log('Failed to add draft', title, e.message);
      }
    }
  }
}

async function main() {
  const data = loadRoadmap();
  const { counts, total } = countSkillsByCategory();

  const shared = {
    'Roadmap.md': renderRoadmapWiki(data),
    'Skill-stats.md': renderSkillStatsWiki(counts, total),
    'Automation.md': renderAutomationWiki(),
  };

  const filesWiki = {
    'Home.md': renderHomeWiki(data, total, 'github-wiki'),
    ...shared,
  };

  const filesMirror = {
    'Home.md': renderHomeWiki(data, total, 'repo-mirror'),
    ...shared,
  };

  if (dryRun) {
    log('DRY_RUN: sizes wiki', Object.fromEntries(Object.entries(filesWiki).map(([k, v]) => [k, v.length])));
  }

  writeRepoMirror(filesMirror);
  syncWikiGitPush(filesWiki);
  await syncProjectItems(data);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
