#!/usr/bin/env node
/**
 * Sync OpenSkill roadmap + skill stats to GitHub Wiki, and roadmap items to GitHub Project v2 (draft issues).
 * Env: SYNC_GITHUB_TOKEN (PAT: repo, project, read:org), GITHUB_REPOSITORY=owner/repo,
 *      PROJECT_OWNER (default: owner), PROJECT_NUMBER (optional int; skip project if unset/0).
 *      DRY_RUN=1 — print actions only, no git push / no GraphQL mutations.
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdtempSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { execSync } from 'child_process';

const token = process.env.SYNC_GITHUB_TOKEN || process.env.GITHUB_TOKEN;
const repoFull = process.env.GITHUB_REPOSITORY || '';
const [owner, repo] = repoFull.includes('/') ? repoFull.split('/') : ['', ''];
const projectOwner = process.env.PROJECT_OWNER || owner;
const projectNumber = parseInt(process.env.PROJECT_NUMBER || '0', 10) || 0;
const dryRun = process.env.DRY_RUN === '1';

function log(...a) {
  console.log('[sync-github]', ...a);
}

function countSkillsByCategory() {
  const skillsDir = join(process.cwd(), 'skills');
  const counts = {};
  let total = 0;
  for (const cat of readdirSync(skillsDir)) {
    const p = join(skillsDir, cat);
    if (!statSync(p).isDirectory()) continue;
    let n = 0;
    function walk(d) {
      for (const e of readdirSync(d)) {
        const fp = join(d, e);
        if (statSync(fp).isDirectory()) walk(fp);
        else if (e.endsWith('.skill.md')) n += 1;
      }
    }
    walk(p);
    counts[cat] = n;
    total += n;
  }
  return { counts, total };
}

function loadRoadmap() {
  const p = join(process.cwd(), 'data', 'roadmap.json');
  return JSON.parse(readFileSync(p, 'utf8'));
}

function renderRoadmapWiki(data) {
  const iso = new Date().toISOString();
  let md = `<!-- Auto-generated by OpenSkill GitHub Actions — do not edit by hand. 请勿手改 -->\n\n`;
  md += `# Roadmap · 路线图\n\n`;
  md += `_Last sync · 最后同步: ${iso}_\n\n`;
  md += `**Source · 数据源:** [data/roadmap.json](https://github.com/${owner}/${repo}/blob/master/data/roadmap.json)\n\n`;
  md += `## Vision · 愿景\n\n`;
  md += `**中文：** ${data.vision.zh}\n\n`;
  md += `**English:** ${data.vision.en}\n\n`;

  for (const phase of ['now', 'next', 'later']) {
    const label = { now: 'Now · 当前', next: 'Next · 下一波', later: 'Later · 后续' }[phase];
    md += `## ${label}\n\n`;
    const items = data.phases[phase] || [];
    for (const it of items) {
      md += `### \`${it.id}\` — ${it.title_zh} · ${it.title_en}\n\n`;
      md += `- **中文：** ${it.body_zh}\n`;
      md += `- **English:** ${it.body_en}\n\n`;
    }
  }
  return md;
}

function renderHomeWiki(data, total) {
  const iso = new Date().toISOString();
  return `<!-- Auto-generated — do not edit by hand. -->\n\n` +
    `# OpenSkill Wiki · Home\n\n` +
    `_Synced · 同步时间: ${iso}_\n\n` +
    `**中文：** 本 Wiki 由主仓库 [OpenSkill](https://github.com/${owner}/${repo}) 的 **GitHub Actions** 自动更新（路线图、技能统计）。协作规范仍以仓库内 \`CONTRIBUTING.md\` 为准。\n\n` +
    `**English:** This wiki is **auto-updated** from the main repo (roadmap + skill stats). Contribution rules live in \`CONTRIBUTING.md\` in the repo.\n\n` +
    `## Quick links · 快速链接\n\n` +
    `- [Roadmap (generated) · 路线图](Roadmap)\n` +
    `- [Skill stats · 技能统计](Skill-stats)\n` +
    `- [Repository README · 仓库首页](https://github.com/${owner}/${repo}#readme)\n` +
    `- [Contributing · 贡献指南](https://github.com/${owner}/${repo}/blob/master/CONTRIBUTING.md)\n` +
    `- [GitHub Projects · 项目看板](https://github.com/${owner}/${repo}/projects)\n\n` +
    `**Skills in repo · 仓库技能总数:** **${total}**\n`;
}

function renderSkillStatsWiki(counts, total) {
  const iso = new Date().toISOString();
  let md = `<!-- Auto-generated — do not edit by hand. -->\n\n# Skill stats · 技能统计\n\n`;
  md += `_Last sync · 最后同步: ${iso}_\n\n`;
  md += `| Category · 分类 | .skill.md count |\n|---|---:|\n`;
  for (const k of Object.keys(counts).sort()) {
    md += `| \`${k}/\` | ${counts[k]} |\n`;
  }
  md += `| **Total · 总计** | **${total}** |\n`;
  return md;
}

function renderAutomationWiki() {
  return `<!-- Auto-generated — do not edit by hand. -->\n\n# Automation · 自动化说明\n\n` +
    `**中文：** \`.github/workflows/sync-github-project-wiki.yml\` 在推送 \`data/roadmap.json\`、\`skills/**\` 等变更时运行 \`node tools/sync_github.mjs\`，更新本 Wiki 与（若配置）GitHub Project v2。需要在仓库 **Secrets** 中设置 \`PROJECTS_WIKI_PAT\`（PAT 需 \`repo\`、\`read:org\`、\`project\` 权限），在 **Variables** 中设置 \`PROJECT_NUMBER\`（组织或用户下 Project 的编号）。\n\n` +
    `**English:** Workflow \`.github/workflows/sync-github-project-wiki.yml\` runs \`tools/sync_github.mjs\` on relevant pushes. Set secret \`PROJECTS_WIKI_PAT\` (scopes: \`repo\`, \`read:org\`, \`project\`) and variable \`PROJECT_NUMBER\` for your Project v2 board.\n`;
}

async function graphql(query, variables = {}) {
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${JSON.stringify(json)}`);
  if (json.errors?.length) throw new Error(JSON.stringify(json.errors));
  return json.data;
}

function markerTitle(phase, id) {
  return `[Roadmap:${phase}:${id}]`;
}

function parseProjectItems(proj) {
  const titles = new Set();
  for (const node of proj.items?.nodes || []) {
    const t = node.content?.title;
    if (t) titles.add(t);
  }
  return { projectId: proj.id, projectTitle: proj.title, existingTitles: titles };
}

async function fetchProjectAndExistingTitles() {
  const qOrganization = `
    query($login: String!, $n: Int!) {
      organization(login: $login) {
        projectV2(number: $n) {
          id
          title
          items(first: 100) {
            nodes {
              content {
                __typename
                ... on DraftIssue { title }
                ... on Issue { title }
              }
            }
          }
        }
      }
    }
  `;
  const qUser = `
    query($login: String!, $n: Int!) {
      user(login: $login) {
        projectV2(number: $n) {
          id
          title
          items(first: 100) {
            nodes {
              content {
                __typename
                ... on DraftIssue { title }
                ... on Issue { title }
              }
            }
          }
        }
      }
    }
  `;

  let proj;
  try {
    const d = await graphql(qOrganization, { login: projectOwner, n: projectNumber });
    proj = d.organization?.projectV2;
  } catch (e) {
    log('Organization project query failed:', e.message);
  }
  if (!proj) {
    try {
      const d = await graphql(qUser, { login: projectOwner, n: projectNumber });
      proj = d.user?.projectV2;
    } catch (e) {
      log('User project query failed:', e.message);
    }
  }
  if (!proj) {
    log(`No projectV2 #${projectNumber} for "${projectOwner}" (tried org + user) — skip project sync`);
    return null;
  }
  return parseProjectItems(proj);
}

async function addDraftIssue(projectId, title, body) {
  const m = `
    mutation($pid: ID!, $title: String!, $body: String) {
      addProjectV2DraftIssue(input: { projectId: $pid, title: $title, body: $body }) {
        projectItem { id }
      }
    }
  `;
  await graphql(m, { pid: projectId, title, body });
}

function syncWikiFiles(files) {
  if (!token) {
    log('No SYNC_GITHUB_TOKEN / GITHUB_TOKEN — skip Wiki push');
    return;
  }
  if (!owner || !repo) {
    log('GITHUB_REPOSITORY unset — skip Wiki push');
    return;
  }

  const tmp = mkdtempSync(join(tmpdir(), 'openskill-wiki-'));
  const remote = `https://x-access-token:${encodeURIComponent(token)}@github.com/${owner}/${repo}.wiki.git`;

  try {
    try {
      execSync(`git clone --depth 1 "${remote}" "${tmp}"`, { stdio: 'inherit' });
    } catch {
      log('Wiki clone failed — initializing new wiki repo');
      execSync('git init', { cwd: tmp, stdio: 'inherit' });
      execSync(`git remote add origin "${remote}"`, { cwd: tmp, stdio: 'inherit' });
    }

    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(tmp, name), content, 'utf8');
    }

    execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"', { cwd: tmp });
    execSync('git config user.name "github-actions[bot]"', { cwd: tmp });
    execSync('git add -A', { cwd: tmp, stdio: 'inherit' });
    try {
      execSync(`git commit -m "chore(wiki): auto-sync from ${repoFull}"`, { cwd: tmp, stdio: 'inherit' });
    } catch {
      log('No wiki changes to commit');
      return;
    }
    if (dryRun) {
      log('DRY_RUN: skip git push');
      return;
    }
    execSync('git branch -M master', { cwd: tmp, stdio: 'inherit' });
    execSync('git push -u origin master', { cwd: tmp, stdio: 'inherit' });
    log('Wiki push OK');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

async function syncProjectItems(data) {
  if (!token) {
    log('No token — skip Project sync');
    return;
  }
  if (!projectNumber) {
    log('PROJECT_NUMBER unset — skip Project sync');
    return;
  }

  let meta;
  try {
    meta = await fetchProjectAndExistingTitles();
  } catch (e) {
    log('Project GraphQL error (org project only in this script):', e.message);
    return;
  }
  if (!meta) return;

  log(`Project: ${meta.projectTitle} (${meta.projectId})`);

  for (const phase of ['now', 'next', 'later']) {
    const items = data.phases[phase] || [];
    for (const it of items) {
      const title = markerTitle(phase, it.id);
      if (meta.existingTitles.has(title)) {
        log('Exists, skip:', title);
        continue;
      }
      const body =
        `**Phase · 阶段:** ${phase}\n\n` +
        `**中文**\n${it.body_zh}\n\n` +
        `**English**\n${it.body_en}\n\n` +
        `---\n` +
        `Source: https://github.com/${owner}/${repo}/blob/master/data/roadmap.json`;

      if (dryRun) {
        log('DRY_RUN would add draft:', title);
        continue;
      }
      try {
        await addDraftIssue(meta.projectId, title, body);
        log('Added draft:', title);
        meta.existingTitles.add(title);
      } catch (e) {
        log('Failed to add draft', title, e.message);
      }
    }
  }
}

async function main() {
  const data = loadRoadmap();
  const { counts, total } = countSkillsByCategory();

  const files = {
    'Home.md': renderHomeWiki(data, total),
    'Roadmap.md': renderRoadmapWiki(data),
    'Skill-stats.md': renderSkillStatsWiki(counts, total),
    'Automation.md': renderAutomationWiki(),
  };

  if (dryRun) {
    log('DRY_RUN: generated wiki page sizes:', Object.fromEntries(Object.entries(files).map(([k, v]) => [k, v.length])));
  }

  syncWikiFiles(files);
  await syncProjectItems(data);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
